// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/interfaces.go -destination=internal/mocks/mock_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/kamil5b/lumen-pg/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthUsecase is a mock of AuthUsecase interface.
type MockAuthUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockAuthUsecaseMockRecorder
	isgomock struct{}
}

// MockAuthUsecaseMockRecorder is the mock recorder for MockAuthUsecase.
type MockAuthUsecaseMockRecorder struct {
	mock *MockAuthUsecase
}

// NewMockAuthUsecase creates a new mock instance.
func NewMockAuthUsecase(ctrl *gomock.Controller) *MockAuthUsecase {
	mock := &MockAuthUsecase{ctrl: ctrl}
	mock.recorder = &MockAuthUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthUsecase) EXPECT() *MockAuthUsecaseMockRecorder {
	return m.recorder
}

// GetAccessibleResources mocks base method.
func (m *MockAuthUsecase) GetAccessibleResources(ctx context.Context, username string) (*domain.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessibleResources", ctx, username)
	ret0, _ := ret[0].(*domain.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessibleResources indicates an expected call of GetAccessibleResources.
func (mr *MockAuthUsecaseMockRecorder) GetAccessibleResources(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessibleResources", reflect.TypeOf((*MockAuthUsecase)(nil).GetAccessibleResources), ctx, username)
}

// Login mocks base method.
func (m *MockAuthUsecase) Login(ctx context.Context, username, password string) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, username, password)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthUsecaseMockRecorder) Login(ctx, username, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthUsecase)(nil).Login), ctx, username, password)
}

// Logout mocks base method.
func (m *MockAuthUsecase) Logout(ctx context.Context, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthUsecaseMockRecorder) Logout(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthUsecase)(nil).Logout), ctx, username)
}

// ReAuthenticate mocks base method.
func (m *MockAuthUsecase) ReAuthenticate(ctx context.Context, username, encryptedPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReAuthenticate", ctx, username, encryptedPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReAuthenticate indicates an expected call of ReAuthenticate.
func (mr *MockAuthUsecaseMockRecorder) ReAuthenticate(ctx, username, encryptedPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReAuthenticate", reflect.TypeOf((*MockAuthUsecase)(nil).ReAuthenticate), ctx, username, encryptedPassword)
}

// ValidateSession mocks base method.
func (m *MockAuthUsecase) ValidateSession(session *domain.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSession", session)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateSession indicates an expected call of ValidateSession.
func (mr *MockAuthUsecaseMockRecorder) ValidateSession(session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSession", reflect.TypeOf((*MockAuthUsecase)(nil).ValidateSession), session)
}

// MockMetadataUsecase is a mock of MetadataUsecase interface.
type MockMetadataUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockMetadataUsecaseMockRecorder
	isgomock struct{}
}

// MockMetadataUsecaseMockRecorder is the mock recorder for MockMetadataUsecase.
type MockMetadataUsecaseMockRecorder struct {
	mock *MockMetadataUsecase
}

// NewMockMetadataUsecase creates a new mock instance.
func NewMockMetadataUsecase(ctrl *gomock.Controller) *MockMetadataUsecase {
	mock := &MockMetadataUsecase{ctrl: ctrl}
	mock.recorder = &MockMetadataUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetadataUsecase) EXPECT() *MockMetadataUsecaseMockRecorder {
	return m.recorder
}

// GetERDData mocks base method.
func (m *MockMetadataUsecase) GetERDData(ctx context.Context, database, schema string) (*domain.ERDData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetERDData", ctx, database, schema)
	ret0, _ := ret[0].(*domain.ERDData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetERDData indicates an expected call of GetERDData.
func (mr *MockMetadataUsecaseMockRecorder) GetERDData(ctx, database, schema any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetERDData", reflect.TypeOf((*MockMetadataUsecase)(nil).GetERDData), ctx, database, schema)
}

// GetMetadata mocks base method.
func (m *MockMetadataUsecase) GetMetadata() *domain.Metadata {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadata")
	ret0, _ := ret[0].(*domain.Metadata)
	return ret0
}

// GetMetadata indicates an expected call of GetMetadata.
func (mr *MockMetadataUsecaseMockRecorder) GetMetadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadata", reflect.TypeOf((*MockMetadataUsecase)(nil).GetMetadata))
}

// GetRBACMapping mocks base method.
func (m *MockMetadataUsecase) GetRBACMapping() map[string]*domain.Role {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRBACMapping")
	ret0, _ := ret[0].(map[string]*domain.Role)
	return ret0
}

// GetRBACMapping indicates an expected call of GetRBACMapping.
func (mr *MockMetadataUsecaseMockRecorder) GetRBACMapping() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRBACMapping", reflect.TypeOf((*MockMetadataUsecase)(nil).GetRBACMapping))
}

// InitializeMetadata mocks base method.
func (m *MockMetadataUsecase) InitializeMetadata(ctx context.Context, connStr string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitializeMetadata", ctx, connStr)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitializeMetadata indicates an expected call of InitializeMetadata.
func (mr *MockMetadataUsecaseMockRecorder) InitializeMetadata(ctx, connStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitializeMetadata", reflect.TypeOf((*MockMetadataUsecase)(nil).InitializeMetadata), ctx, connStr)
}

// RefreshMetadata mocks base method.
func (m *MockMetadataUsecase) RefreshMetadata(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshMetadata", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefreshMetadata indicates an expected call of RefreshMetadata.
func (mr *MockMetadataUsecaseMockRecorder) RefreshMetadata(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshMetadata", reflect.TypeOf((*MockMetadataUsecase)(nil).RefreshMetadata), ctx)
}

// MockDataExplorerUsecase is a mock of DataExplorerUsecase interface.
type MockDataExplorerUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockDataExplorerUsecaseMockRecorder
	isgomock struct{}
}

// MockDataExplorerUsecaseMockRecorder is the mock recorder for MockDataExplorerUsecase.
type MockDataExplorerUsecaseMockRecorder struct {
	mock *MockDataExplorerUsecase
}

// NewMockDataExplorerUsecase creates a new mock instance.
func NewMockDataExplorerUsecase(ctrl *gomock.Controller) *MockDataExplorerUsecase {
	mock := &MockDataExplorerUsecase{ctrl: ctrl}
	mock.recorder = &MockDataExplorerUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataExplorerUsecase) EXPECT() *MockDataExplorerUsecaseMockRecorder {
	return m.recorder
}

// GetReferencingTables mocks base method.
func (m *MockDataExplorerUsecase) GetReferencingTables(ctx context.Context, database, schema, table, pkColumn string, pkValue any) ([]domain.ReferencingTable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReferencingTables", ctx, database, schema, table, pkColumn, pkValue)
	ret0, _ := ret[0].([]domain.ReferencingTable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReferencingTables indicates an expected call of GetReferencingTables.
func (mr *MockDataExplorerUsecaseMockRecorder) GetReferencingTables(ctx, database, schema, table, pkColumn, pkValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReferencingTables", reflect.TypeOf((*MockDataExplorerUsecase)(nil).GetReferencingTables), ctx, database, schema, table, pkColumn, pkValue)
}

// GetTotalRowCount mocks base method.
func (m *MockDataExplorerUsecase) GetTotalRowCount(ctx context.Context, database, schema, table, whereClause string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalRowCount", ctx, database, schema, table, whereClause)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalRowCount indicates an expected call of GetTotalRowCount.
func (mr *MockDataExplorerUsecaseMockRecorder) GetTotalRowCount(ctx, database, schema, table, whereClause any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalRowCount", reflect.TypeOf((*MockDataExplorerUsecase)(nil).GetTotalRowCount), ctx, database, schema, table, whereClause)
}

// LoadTableData mocks base method.
func (m *MockDataExplorerUsecase) LoadTableData(ctx context.Context, database, schema, table string, cursor *domain.Cursor, orderBy, orderDir, whereClause string) (*domain.CursorPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadTableData", ctx, database, schema, table, cursor, orderBy, orderDir, whereClause)
	ret0, _ := ret[0].(*domain.CursorPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadTableData indicates an expected call of LoadTableData.
func (mr *MockDataExplorerUsecaseMockRecorder) LoadTableData(ctx, database, schema, table, cursor, orderBy, orderDir, whereClause any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadTableData", reflect.TypeOf((*MockDataExplorerUsecase)(nil).LoadTableData), ctx, database, schema, table, cursor, orderBy, orderDir, whereClause)
}

// NavigateToForeignKey mocks base method.
func (m *MockDataExplorerUsecase) NavigateToForeignKey(ctx context.Context, database, schema, table, column string, value any) (*domain.CursorPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NavigateToForeignKey", ctx, database, schema, table, column, value)
	ret0, _ := ret[0].(*domain.CursorPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NavigateToForeignKey indicates an expected call of NavigateToForeignKey.
func (mr *MockDataExplorerUsecaseMockRecorder) NavigateToForeignKey(ctx, database, schema, table, column, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NavigateToForeignKey", reflect.TypeOf((*MockDataExplorerUsecase)(nil).NavigateToForeignKey), ctx, database, schema, table, column, value)
}

// MockQueryUsecase is a mock of QueryUsecase interface.
type MockQueryUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockQueryUsecaseMockRecorder
	isgomock struct{}
}

// MockQueryUsecaseMockRecorder is the mock recorder for MockQueryUsecase.
type MockQueryUsecaseMockRecorder struct {
	mock *MockQueryUsecase
}

// NewMockQueryUsecase creates a new mock instance.
func NewMockQueryUsecase(ctrl *gomock.Controller) *MockQueryUsecase {
	mock := &MockQueryUsecase{ctrl: ctrl}
	mock.recorder = &MockQueryUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryUsecase) EXPECT() *MockQueryUsecaseMockRecorder {
	return m.recorder
}

// ExecuteQueries mocks base method.
func (m *MockQueryUsecase) ExecuteQueries(ctx context.Context, database, sql string) ([]domain.QueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteQueries", ctx, database, sql)
	ret0, _ := ret[0].([]domain.QueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteQueries indicates an expected call of ExecuteQueries.
func (mr *MockQueryUsecaseMockRecorder) ExecuteQueries(ctx, database, sql any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteQueries", reflect.TypeOf((*MockQueryUsecase)(nil).ExecuteQueries), ctx, database, sql)
}

// ExecuteQuery mocks base method.
func (m *MockQueryUsecase) ExecuteQuery(ctx context.Context, database, query string) (*domain.QueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteQuery", ctx, database, query)
	ret0, _ := ret[0].(*domain.QueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteQuery indicates an expected call of ExecuteQuery.
func (mr *MockQueryUsecaseMockRecorder) ExecuteQuery(ctx, database, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteQuery", reflect.TypeOf((*MockQueryUsecase)(nil).ExecuteQuery), ctx, database, query)
}

// ExecuteQueryWithPagination mocks base method.
func (m *MockQueryUsecase) ExecuteQueryWithPagination(ctx context.Context, database, query string, offset, limit int) (*domain.QueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteQueryWithPagination", ctx, database, query, offset, limit)
	ret0, _ := ret[0].(*domain.QueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteQueryWithPagination indicates an expected call of ExecuteQueryWithPagination.
func (mr *MockQueryUsecaseMockRecorder) ExecuteQueryWithPagination(ctx, database, query, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteQueryWithPagination", reflect.TypeOf((*MockQueryUsecase)(nil).ExecuteQueryWithPagination), ctx, database, query, offset, limit)
}

// MockTransactionUsecase is a mock of TransactionUsecase interface.
type MockTransactionUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionUsecaseMockRecorder
	isgomock struct{}
}

// MockTransactionUsecaseMockRecorder is the mock recorder for MockTransactionUsecase.
type MockTransactionUsecaseMockRecorder struct {
	mock *MockTransactionUsecase
}

// NewMockTransactionUsecase creates a new mock instance.
func NewMockTransactionUsecase(ctrl *gomock.Controller) *MockTransactionUsecase {
	mock := &MockTransactionUsecase{ctrl: ctrl}
	mock.recorder = &MockTransactionUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionUsecase) EXPECT() *MockTransactionUsecaseMockRecorder {
	return m.recorder
}

// AddOperation mocks base method.
func (m *MockTransactionUsecase) AddOperation(ctx context.Context, sessionID string, op domain.BufferedOperation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOperation", ctx, sessionID, op)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddOperation indicates an expected call of AddOperation.
func (mr *MockTransactionUsecaseMockRecorder) AddOperation(ctx, sessionID, op any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOperation", reflect.TypeOf((*MockTransactionUsecase)(nil).AddOperation), ctx, sessionID, op)
}

// Commit mocks base method.
func (m *MockTransactionUsecase) Commit(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockTransactionUsecaseMockRecorder) Commit(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockTransactionUsecase)(nil).Commit), ctx, sessionID)
}

// GetTransaction mocks base method.
func (m *MockTransactionUsecase) GetTransaction(sessionID string) (*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransaction", sessionID)
	ret0, _ := ret[0].(*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransaction indicates an expected call of GetTransaction.
func (mr *MockTransactionUsecaseMockRecorder) GetTransaction(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransaction", reflect.TypeOf((*MockTransactionUsecase)(nil).GetTransaction), sessionID)
}

// Rollback mocks base method.
func (m *MockTransactionUsecase) Rollback(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockTransactionUsecaseMockRecorder) Rollback(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockTransactionUsecase)(nil).Rollback), ctx, sessionID)
}

// StartTransaction mocks base method.
func (m *MockTransactionUsecase) StartTransaction(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartTransaction", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartTransaction indicates an expected call of StartTransaction.
func (mr *MockTransactionUsecaseMockRecorder) StartTransaction(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartTransaction", reflect.TypeOf((*MockTransactionUsecase)(nil).StartTransaction), ctx, sessionID)
}
