// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/interfaces.go -destination=internal/mocks/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/kamil5b/lumen-pg/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockConnectionRepository is a mock of ConnectionRepository interface.
type MockConnectionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockConnectionRepositoryMockRecorder
	isgomock struct{}
}

// MockConnectionRepositoryMockRecorder is the mock recorder for MockConnectionRepository.
type MockConnectionRepositoryMockRecorder struct {
	mock *MockConnectionRepository
}

// NewMockConnectionRepository creates a new mock instance.
func NewMockConnectionRepository(ctrl *gomock.Controller) *MockConnectionRepository {
	mock := &MockConnectionRepository{ctrl: ctrl}
	mock.recorder = &MockConnectionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectionRepository) EXPECT() *MockConnectionRepositoryMockRecorder {
	return m.recorder
}

// Connect mocks base method.
func (m *MockConnectionRepository) Connect(ctx context.Context, config *domain.ConnectionConfig) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", ctx, config)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Connect indicates an expected call of Connect.
func (mr *MockConnectionRepositoryMockRecorder) Connect(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockConnectionRepository)(nil).Connect), ctx, config)
}

// ParseConnectionString mocks base method.
func (m *MockConnectionRepository) ParseConnectionString(connStr string) (*domain.ConnectionConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseConnectionString", connStr)
	ret0, _ := ret[0].(*domain.ConnectionConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseConnectionString indicates an expected call of ParseConnectionString.
func (mr *MockConnectionRepositoryMockRecorder) ParseConnectionString(connStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseConnectionString", reflect.TypeOf((*MockConnectionRepository)(nil).ParseConnectionString), connStr)
}

// ProbeConnection mocks base method.
func (m *MockConnectionRepository) ProbeConnection(ctx context.Context, username, password, host string, port int, sslMode string, accessibleDBs []string) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProbeConnection", ctx, username, password, host, port, sslMode, accessibleDBs)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProbeConnection indicates an expected call of ProbeConnection.
func (mr *MockConnectionRepositoryMockRecorder) ProbeConnection(ctx, username, password, host, port, sslMode, accessibleDBs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProbeConnection", reflect.TypeOf((*MockConnectionRepository)(nil).ProbeConnection), ctx, username, password, host, port, sslMode, accessibleDBs)
}

// TestConnection mocks base method.
func (m *MockConnectionRepository) TestConnection(ctx context.Context, connStr string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TestConnection", ctx, connStr)
	ret0, _ := ret[0].(error)
	return ret0
}

// TestConnection indicates an expected call of TestConnection.
func (mr *MockConnectionRepositoryMockRecorder) TestConnection(ctx, connStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestConnection", reflect.TypeOf((*MockConnectionRepository)(nil).TestConnection), ctx, connStr)
}

// ValidateConnectionString mocks base method.
func (m *MockConnectionRepository) ValidateConnectionString(connStr string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateConnectionString", connStr)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateConnectionString indicates an expected call of ValidateConnectionString.
func (mr *MockConnectionRepositoryMockRecorder) ValidateConnectionString(connStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateConnectionString", reflect.TypeOf((*MockConnectionRepository)(nil).ValidateConnectionString), connStr)
}

// MockMetadataRepository is a mock of MetadataRepository interface.
type MockMetadataRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMetadataRepositoryMockRecorder
	isgomock struct{}
}

// MockMetadataRepositoryMockRecorder is the mock recorder for MockMetadataRepository.
type MockMetadataRepositoryMockRecorder struct {
	mock *MockMetadataRepository
}

// NewMockMetadataRepository creates a new mock instance.
func NewMockMetadataRepository(ctrl *gomock.Controller) *MockMetadataRepository {
	mock := &MockMetadataRepository{ctrl: ctrl}
	mock.recorder = &MockMetadataRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetadataRepository) EXPECT() *MockMetadataRepositoryMockRecorder {
	return m.recorder
}

// GenerateERDData mocks base method.
func (m *MockMetadataRepository) GenerateERDData(ctx context.Context, database, schema string) (*domain.ERDData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateERDData", ctx, database, schema)
	ret0, _ := ret[0].(*domain.ERDData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateERDData indicates an expected call of GenerateERDData.
func (mr *MockMetadataRepositoryMockRecorder) GenerateERDData(ctx, database, schema any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateERDData", reflect.TypeOf((*MockMetadataRepository)(nil).GenerateERDData), ctx, database, schema)
}

// GetAccessibleResources mocks base method.
func (m *MockMetadataRepository) GetAccessibleResources(ctx context.Context, roleName string) (*domain.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessibleResources", ctx, roleName)
	ret0, _ := ret[0].(*domain.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessibleResources indicates an expected call of GetAccessibleResources.
func (mr *MockMetadataRepositoryMockRecorder) GetAccessibleResources(ctx, roleName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessibleResources", reflect.TypeOf((*MockMetadataRepository)(nil).GetAccessibleResources), ctx, roleName)
}

// LoadAllMetadata mocks base method.
func (m *MockMetadataRepository) LoadAllMetadata(ctx context.Context) (*domain.Metadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadAllMetadata", ctx)
	ret0, _ := ret[0].(*domain.Metadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadAllMetadata indicates an expected call of LoadAllMetadata.
func (mr *MockMetadataRepositoryMockRecorder) LoadAllMetadata(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadAllMetadata", reflect.TypeOf((*MockMetadataRepository)(nil).LoadAllMetadata), ctx)
}

// LoadColumns mocks base method.
func (m *MockMetadataRepository) LoadColumns(ctx context.Context, database, schema, table string) ([]domain.Column, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadColumns", ctx, database, schema, table)
	ret0, _ := ret[0].([]domain.Column)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadColumns indicates an expected call of LoadColumns.
func (mr *MockMetadataRepositoryMockRecorder) LoadColumns(ctx, database, schema, table any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadColumns", reflect.TypeOf((*MockMetadataRepository)(nil).LoadColumns), ctx, database, schema, table)
}

// LoadDatabases mocks base method.
func (m *MockMetadataRepository) LoadDatabases(ctx context.Context) ([]domain.Database, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadDatabases", ctx)
	ret0, _ := ret[0].([]domain.Database)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadDatabases indicates an expected call of LoadDatabases.
func (mr *MockMetadataRepositoryMockRecorder) LoadDatabases(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadDatabases", reflect.TypeOf((*MockMetadataRepository)(nil).LoadDatabases), ctx)
}

// LoadForeignKeys mocks base method.
func (m *MockMetadataRepository) LoadForeignKeys(ctx context.Context, database, schema, table string) ([]domain.ForeignKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadForeignKeys", ctx, database, schema, table)
	ret0, _ := ret[0].([]domain.ForeignKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadForeignKeys indicates an expected call of LoadForeignKeys.
func (mr *MockMetadataRepositoryMockRecorder) LoadForeignKeys(ctx, database, schema, table any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadForeignKeys", reflect.TypeOf((*MockMetadataRepository)(nil).LoadForeignKeys), ctx, database, schema, table)
}

// LoadRoles mocks base method.
func (m *MockMetadataRepository) LoadRoles(ctx context.Context) ([]domain.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadRoles", ctx)
	ret0, _ := ret[0].([]domain.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadRoles indicates an expected call of LoadRoles.
func (mr *MockMetadataRepositoryMockRecorder) LoadRoles(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadRoles", reflect.TypeOf((*MockMetadataRepository)(nil).LoadRoles), ctx)
}

// LoadSchemas mocks base method.
func (m *MockMetadataRepository) LoadSchemas(ctx context.Context, database string) ([]domain.Schema, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadSchemas", ctx, database)
	ret0, _ := ret[0].([]domain.Schema)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadSchemas indicates an expected call of LoadSchemas.
func (mr *MockMetadataRepositoryMockRecorder) LoadSchemas(ctx, database any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadSchemas", reflect.TypeOf((*MockMetadataRepository)(nil).LoadSchemas), ctx, database)
}

// LoadTables mocks base method.
func (m *MockMetadataRepository) LoadTables(ctx context.Context, database, schema string) ([]domain.Table, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadTables", ctx, database, schema)
	ret0, _ := ret[0].([]domain.Table)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadTables indicates an expected call of LoadTables.
func (mr *MockMetadataRepositoryMockRecorder) LoadTables(ctx, database, schema any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadTables", reflect.TypeOf((*MockMetadataRepository)(nil).LoadTables), ctx, database, schema)
}

// MockQueryRepository is a mock of QueryRepository interface.
type MockQueryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockQueryRepositoryMockRecorder
	isgomock struct{}
}

// MockQueryRepositoryMockRecorder is the mock recorder for MockQueryRepository.
type MockQueryRepositoryMockRecorder struct {
	mock *MockQueryRepository
}

// NewMockQueryRepository creates a new mock instance.
func NewMockQueryRepository(ctrl *gomock.Controller) *MockQueryRepository {
	mock := &MockQueryRepository{ctrl: ctrl}
	mock.recorder = &MockQueryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryRepository) EXPECT() *MockQueryRepositoryMockRecorder {
	return m.recorder
}

// ExecuteQueries mocks base method.
func (m *MockQueryRepository) ExecuteQueries(ctx context.Context, database string, queries []string) ([]domain.QueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteQueries", ctx, database, queries)
	ret0, _ := ret[0].([]domain.QueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteQueries indicates an expected call of ExecuteQueries.
func (mr *MockQueryRepositoryMockRecorder) ExecuteQueries(ctx, database, queries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteQueries", reflect.TypeOf((*MockQueryRepository)(nil).ExecuteQueries), ctx, database, queries)
}

// ExecuteQuery mocks base method.
func (m *MockQueryRepository) ExecuteQuery(ctx context.Context, database, query string, params ...any) (*domain.QueryResult, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, database, query}
	for _, a := range params {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExecuteQuery", varargs...)
	ret0, _ := ret[0].(*domain.QueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteQuery indicates an expected call of ExecuteQuery.
func (mr *MockQueryRepositoryMockRecorder) ExecuteQuery(ctx, database, query any, params ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, database, query}, params...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteQuery", reflect.TypeOf((*MockQueryRepository)(nil).ExecuteQuery), varargs...)
}

// ExecuteTransaction mocks base method.
func (m *MockQueryRepository) ExecuteTransaction(ctx context.Context, database string, operations []domain.BufferedOperation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteTransaction", ctx, database, operations)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteTransaction indicates an expected call of ExecuteTransaction.
func (mr *MockQueryRepositoryMockRecorder) ExecuteTransaction(ctx, database, operations any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteTransaction", reflect.TypeOf((*MockQueryRepository)(nil).ExecuteTransaction), ctx, database, operations)
}

// GetReferencingTables mocks base method.
func (m *MockQueryRepository) GetReferencingTables(ctx context.Context, database, schema, table, pkColumn string, pkValue any) ([]domain.ReferencingTable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReferencingTables", ctx, database, schema, table, pkColumn, pkValue)
	ret0, _ := ret[0].([]domain.ReferencingTable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReferencingTables indicates an expected call of GetReferencingTables.
func (mr *MockQueryRepositoryMockRecorder) GetReferencingTables(ctx, database, schema, table, pkColumn, pkValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReferencingTables", reflect.TypeOf((*MockQueryRepository)(nil).GetReferencingTables), ctx, database, schema, table, pkColumn, pkValue)
}

// GetTotalRowCount mocks base method.
func (m *MockQueryRepository) GetTotalRowCount(ctx context.Context, database, schema, table, whereClause string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalRowCount", ctx, database, schema, table, whereClause)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalRowCount indicates an expected call of GetTotalRowCount.
func (mr *MockQueryRepositoryMockRecorder) GetTotalRowCount(ctx, database, schema, table, whereClause any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalRowCount", reflect.TypeOf((*MockQueryRepository)(nil).GetTotalRowCount), ctx, database, schema, table, whereClause)
}

// LoadTableData mocks base method.
func (m *MockQueryRepository) LoadTableData(ctx context.Context, database, schema, table string, cursor *domain.Cursor, orderBy, orderDir, whereClause string) (*domain.CursorPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadTableData", ctx, database, schema, table, cursor, orderBy, orderDir, whereClause)
	ret0, _ := ret[0].(*domain.CursorPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadTableData indicates an expected call of LoadTableData.
func (mr *MockQueryRepositoryMockRecorder) LoadTableData(ctx, database, schema, table, cursor, orderBy, orderDir, whereClause any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadTableData", reflect.TypeOf((*MockQueryRepository)(nil).LoadTableData), ctx, database, schema, table, cursor, orderBy, orderDir, whereClause)
}
