// Code generated by MockGen. DO NOT EDIT.
// Source: internal/session/manager.go
//
// Generated by this command:
//
//	mockgen -source=internal/session/manager.go -destination=internal/mocks/mock_session.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	domain "github.com/kamil5b/lumen-pg/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
	isgomock struct{}
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// ClearSessionCookies mocks base method.
func (m *MockManager) ClearSessionCookies(w http.ResponseWriter) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClearSessionCookies", w)
}

// ClearSessionCookies indicates an expected call of ClearSessionCookies.
func (mr *MockManagerMockRecorder) ClearSessionCookies(w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearSessionCookies", reflect.TypeOf((*MockManager)(nil).ClearSessionCookies), w)
}

// CreateSessionCookies mocks base method.
func (m *MockManager) CreateSessionCookies(w http.ResponseWriter, username, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSessionCookies", w, username, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSessionCookies indicates an expected call of CreateSessionCookies.
func (mr *MockManagerMockRecorder) CreateSessionCookies(w, username, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSessionCookies", reflect.TypeOf((*MockManager)(nil).CreateSessionCookies), w, username, password)
}

// GetSessionFromCookies mocks base method.
func (m *MockManager) GetSessionFromCookies(r *http.Request) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionFromCookies", r)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionFromCookies indicates an expected call of GetSessionFromCookies.
func (mr *MockManagerMockRecorder) GetSessionFromCookies(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionFromCookies", reflect.TypeOf((*MockManager)(nil).GetSessionFromCookies), r)
}

// ValidateCookie mocks base method.
func (m *MockManager) ValidateCookie(cookie *http.Cookie) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateCookie", cookie)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateCookie indicates an expected call of ValidateCookie.
func (mr *MockManagerMockRecorder) ValidateCookie(cookie any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateCookie", reflect.TypeOf((*MockManager)(nil).ValidateCookie), cookie)
}
