// Code generated by MockGen. DO NOT EDIT.
// Source: /home/kamil5b/REDIKRU/lumen-pg/internal/interfaces/usecase/rbac_usecase.go

// Package mockusecase is a generated GoMock package.
package mockusecase

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/kamil5b/lumen-pg/internal/domain"
)

// MockRBACUseCase is a mock of RBACUseCase interface.
type MockRBACUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockRBACUseCaseMockRecorder
}

// MockRBACUseCaseMockRecorder is the mock recorder for MockRBACUseCase.
type MockRBACUseCaseMockRecorder struct {
	mock *MockRBACUseCase
}

// NewMockRBACUseCase creates a new mock instance.
func NewMockRBACUseCase(ctrl *gomock.Controller) *MockRBACUseCase {
	mock := &MockRBACUseCase{ctrl: ctrl}
	mock.recorder = &MockRBACUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRBACUseCase) EXPECT() *MockRBACUseCaseMockRecorder {
	return m.recorder
}

// CheckDatabaseAccess mocks base method.
func (m *MockRBACUseCase) CheckDatabaseAccess(ctx context.Context, username, database string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckDatabaseAccess", ctx, username, database)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckDatabaseAccess indicates an expected call of CheckDatabaseAccess.
func (mr *MockRBACUseCaseMockRecorder) CheckDatabaseAccess(ctx, username, database interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckDatabaseAccess", reflect.TypeOf((*MockRBACUseCase)(nil).CheckDatabaseAccess), ctx, username, database)
}

// CheckDeletePermission mocks base method.
func (m *MockRBACUseCase) CheckDeletePermission(ctx context.Context, username, database, schema, table string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckDeletePermission", ctx, username, database, schema, table)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckDeletePermission indicates an expected call of CheckDeletePermission.
func (mr *MockRBACUseCaseMockRecorder) CheckDeletePermission(ctx, username, database, schema, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckDeletePermission", reflect.TypeOf((*MockRBACUseCase)(nil).CheckDeletePermission), ctx, username, database, schema, table)
}

// CheckInsertPermission mocks base method.
func (m *MockRBACUseCase) CheckInsertPermission(ctx context.Context, username, database, schema, table string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckInsertPermission", ctx, username, database, schema, table)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckInsertPermission indicates an expected call of CheckInsertPermission.
func (mr *MockRBACUseCaseMockRecorder) CheckInsertPermission(ctx, username, database, schema, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckInsertPermission", reflect.TypeOf((*MockRBACUseCase)(nil).CheckInsertPermission), ctx, username, database, schema, table)
}

// CheckSchemaAccess mocks base method.
func (m *MockRBACUseCase) CheckSchemaAccess(ctx context.Context, username, database, schema string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckSchemaAccess", ctx, username, database, schema)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckSchemaAccess indicates an expected call of CheckSchemaAccess.
func (mr *MockRBACUseCaseMockRecorder) CheckSchemaAccess(ctx, username, database, schema interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckSchemaAccess", reflect.TypeOf((*MockRBACUseCase)(nil).CheckSchemaAccess), ctx, username, database, schema)
}

// CheckSelectPermission mocks base method.
func (m *MockRBACUseCase) CheckSelectPermission(ctx context.Context, username, database, schema, table string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckSelectPermission", ctx, username, database, schema, table)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckSelectPermission indicates an expected call of CheckSelectPermission.
func (mr *MockRBACUseCaseMockRecorder) CheckSelectPermission(ctx, username, database, schema, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckSelectPermission", reflect.TypeOf((*MockRBACUseCase)(nil).CheckSelectPermission), ctx, username, database, schema, table)
}

// CheckTableAccess mocks base method.
func (m *MockRBACUseCase) CheckTableAccess(ctx context.Context, username, database, schema, table string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckTableAccess", ctx, username, database, schema, table)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckTableAccess indicates an expected call of CheckTableAccess.
func (mr *MockRBACUseCaseMockRecorder) CheckTableAccess(ctx, username, database, schema, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckTableAccess", reflect.TypeOf((*MockRBACUseCase)(nil).CheckTableAccess), ctx, username, database, schema, table)
}

// CheckUpdatePermission mocks base method.
func (m *MockRBACUseCase) CheckUpdatePermission(ctx context.Context, username, database, schema, table string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUpdatePermission", ctx, username, database, schema, table)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUpdatePermission indicates an expected call of CheckUpdatePermission.
func (mr *MockRBACUseCaseMockRecorder) CheckUpdatePermission(ctx, username, database, schema, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUpdatePermission", reflect.TypeOf((*MockRBACUseCase)(nil).CheckUpdatePermission), ctx, username, database, schema, table)
}

// GetTablePermissions mocks base method.
func (m *MockRBACUseCase) GetTablePermissions(ctx context.Context, username, database, schema, table string) (*domain.PermissionSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTablePermissions", ctx, username, database, schema, table)
	ret0, _ := ret[0].(*domain.PermissionSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTablePermissions indicates an expected call of GetTablePermissions.
func (mr *MockRBACUseCaseMockRecorder) GetTablePermissions(ctx, username, database, schema, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTablePermissions", reflect.TypeOf((*MockRBACUseCase)(nil).GetTablePermissions), ctx, username, database, schema, table)
}

// GetUserAccessibleDatabases mocks base method.
func (m *MockRBACUseCase) GetUserAccessibleDatabases(ctx context.Context, username string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAccessibleDatabases", ctx, username)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAccessibleDatabases indicates an expected call of GetUserAccessibleDatabases.
func (mr *MockRBACUseCaseMockRecorder) GetUserAccessibleDatabases(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAccessibleDatabases", reflect.TypeOf((*MockRBACUseCase)(nil).GetUserAccessibleDatabases), ctx, username)
}

// GetUserAccessibleSchemas mocks base method.
func (m *MockRBACUseCase) GetUserAccessibleSchemas(ctx context.Context, username, database string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAccessibleSchemas", ctx, username, database)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAccessibleSchemas indicates an expected call of GetUserAccessibleSchemas.
func (mr *MockRBACUseCaseMockRecorder) GetUserAccessibleSchemas(ctx, username, database interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAccessibleSchemas", reflect.TypeOf((*MockRBACUseCase)(nil).GetUserAccessibleSchemas), ctx, username, database)
}

// GetUserAccessibleTables mocks base method.
func (m *MockRBACUseCase) GetUserAccessibleTables(ctx context.Context, username, database, schema string) ([]domain.AccessibleTable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAccessibleTables", ctx, username, database, schema)
	ret0, _ := ret[0].([]domain.AccessibleTable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAccessibleTables indicates an expected call of GetUserAccessibleTables.
func (mr *MockRBACUseCaseMockRecorder) GetUserAccessibleTables(ctx, username, database, schema interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAccessibleTables", reflect.TypeOf((*MockRBACUseCase)(nil).GetUserAccessibleTables), ctx, username, database, schema)
}

// GetUserRole mocks base method.
func (m *MockRBACUseCase) GetUserRole(ctx context.Context, username string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRole", ctx, username)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRole indicates an expected call of GetUserRole.
func (mr *MockRBACUseCaseMockRecorder) GetUserRole(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRole", reflect.TypeOf((*MockRBACUseCase)(nil).GetUserRole), ctx, username)
}

// IsTableReadOnly mocks base method.
func (m *MockRBACUseCase) IsTableReadOnly(ctx context.Context, username, database, schema, table string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTableReadOnly", ctx, username, database, schema, table)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsTableReadOnly indicates an expected call of IsTableReadOnly.
func (mr *MockRBACUseCaseMockRecorder) IsTableReadOnly(ctx, username, database, schema, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTableReadOnly", reflect.TypeOf((*MockRBACUseCase)(nil).IsTableReadOnly), ctx, username, database, schema, table)
}

// ValidateUserAccessToResource mocks base method.
func (m *MockRBACUseCase) ValidateUserAccessToResource(ctx context.Context, username, resourceType, database, schema, table string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateUserAccessToResource", ctx, username, resourceType, database, schema, table)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateUserAccessToResource indicates an expected call of ValidateUserAccessToResource.
func (mr *MockRBACUseCaseMockRecorder) ValidateUserAccessToResource(ctx, username, resourceType, database, schema, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateUserAccessToResource", reflect.TypeOf((*MockRBACUseCase)(nil).ValidateUserAccessToResource), ctx, username, resourceType, database, schema, table)
}

// VerifyUserPermissions mocks base method.
func (m *MockRBACUseCase) VerifyUserPermissions(ctx context.Context, username, database, schema, table string) (*domain.PermissionSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyUserPermissions", ctx, username, database, schema, table)
	ret0, _ := ret[0].(*domain.PermissionSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyUserPermissions indicates an expected call of VerifyUserPermissions.
func (mr *MockRBACUseCaseMockRecorder) VerifyUserPermissions(ctx, username, database, schema, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyUserPermissions", reflect.TypeOf((*MockRBACUseCase)(nil).VerifyUserPermissions), ctx, username, database, schema, table)
}
