// Code generated by MockGen. DO NOT EDIT.
// Source: /home/kamil5b/REDIKRU/lumen-pg/internal/interfaces/usecase/security_usecase.go

// Package mockusecase is a generated GoMock package.
package mockusecase

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/kamil5b/lumen-pg/internal/domain"
)

// MockSecurityUseCase is a mock of SecurityUseCase interface.
type MockSecurityUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockSecurityUseCaseMockRecorder
}

// MockSecurityUseCaseMockRecorder is the mock recorder for MockSecurityUseCase.
type MockSecurityUseCaseMockRecorder struct {
	mock *MockSecurityUseCase
}

// NewMockSecurityUseCase creates a new mock instance.
func NewMockSecurityUseCase(ctrl *gomock.Controller) *MockSecurityUseCase {
	mock := &MockSecurityUseCase{ctrl: ctrl}
	mock.recorder = &MockSecurityUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecurityUseCase) EXPECT() *MockSecurityUseCaseMockRecorder {
	return m.recorder
}

// CheckPasswordExpiry mocks base method.
func (m *MockSecurityUseCase) CheckPasswordExpiry(ctx context.Context, username, encryptedPassword string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPasswordExpiry", ctx, username, encryptedPassword)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckPasswordExpiry indicates an expected call of CheckPasswordExpiry.
func (mr *MockSecurityUseCaseMockRecorder) CheckPasswordExpiry(ctx, username, encryptedPassword interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPasswordExpiry", reflect.TypeOf((*MockSecurityUseCase)(nil).CheckPasswordExpiry), ctx, username, encryptedPassword)
}

// CheckSessionTimeout mocks base method.
func (m *MockSecurityUseCase) CheckSessionTimeout(ctx context.Context, sessionID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckSessionTimeout", ctx, sessionID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckSessionTimeout indicates an expected call of CheckSessionTimeout.
func (mr *MockSecurityUseCaseMockRecorder) CheckSessionTimeout(ctx, sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckSessionTimeout", reflect.TypeOf((*MockSecurityUseCase)(nil).CheckSessionTimeout), ctx, sessionID)
}

// DecryptPassword mocks base method.
func (m *MockSecurityUseCase) DecryptPassword(ctx context.Context, encryptedPassword string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptPassword", ctx, encryptedPassword)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecryptPassword indicates an expected call of DecryptPassword.
func (mr *MockSecurityUseCaseMockRecorder) DecryptPassword(ctx, encryptedPassword interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptPassword", reflect.TypeOf((*MockSecurityUseCase)(nil).DecryptPassword), ctx, encryptedPassword)
}

// EncryptPassword mocks base method.
func (m *MockSecurityUseCase) EncryptPassword(ctx context.Context, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptPassword", ctx, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncryptPassword indicates an expected call of EncryptPassword.
func (mr *MockSecurityUseCaseMockRecorder) EncryptPassword(ctx, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptPassword", reflect.TypeOf((*MockSecurityUseCase)(nil).EncryptPassword), ctx, password)
}

// GenerateCookieSignature mocks base method.
func (m *MockSecurityUseCase) GenerateCookieSignature(ctx context.Context, cookieData *domain.CookieData) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateCookieSignature", ctx, cookieData)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateCookieSignature indicates an expected call of GenerateCookieSignature.
func (mr *MockSecurityUseCaseMockRecorder) GenerateCookieSignature(ctx, cookieData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateCookieSignature", reflect.TypeOf((*MockSecurityUseCase)(nil).GenerateCookieSignature), ctx, cookieData)
}

// GenerateSecureSessionID mocks base method.
func (m *MockSecurityUseCase) GenerateSecureSessionID(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSecureSessionID", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateSecureSessionID indicates an expected call of GenerateSecureSessionID.
func (mr *MockSecurityUseCaseMockRecorder) GenerateSecureSessionID(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSecureSessionID", reflect.TypeOf((*MockSecurityUseCase)(nil).GenerateSecureSessionID), ctx)
}

// IsHTTPSEnabled mocks base method.
func (m *MockSecurityUseCase) IsHTTPSEnabled(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsHTTPSEnabled", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsHTTPSEnabled indicates an expected call of IsHTTPSEnabled.
func (mr *MockSecurityUseCaseMockRecorder) IsHTTPSEnabled(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsHTTPSEnabled", reflect.TypeOf((*MockSecurityUseCase)(nil).IsHTTPSEnabled), ctx)
}

// SanitizeWhereClause mocks base method.
func (m *MockSecurityUseCase) SanitizeWhereClause(ctx context.Context, whereClause string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SanitizeWhereClause", ctx, whereClause)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SanitizeWhereClause indicates an expected call of SanitizeWhereClause.
func (mr *MockSecurityUseCaseMockRecorder) SanitizeWhereClause(ctx, whereClause interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SanitizeWhereClause", reflect.TypeOf((*MockSecurityUseCase)(nil).SanitizeWhereClause), ctx, whereClause)
}

// ValidateCookieIntegrity mocks base method.
func (m *MockSecurityUseCase) ValidateCookieIntegrity(ctx context.Context, cookieData *domain.CookieData, signature string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateCookieIntegrity", ctx, cookieData, signature)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateCookieIntegrity indicates an expected call of ValidateCookieIntegrity.
func (mr *MockSecurityUseCaseMockRecorder) ValidateCookieIntegrity(ctx, cookieData, signature interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateCookieIntegrity", reflect.TypeOf((*MockSecurityUseCase)(nil).ValidateCookieIntegrity), ctx, cookieData, signature)
}

// ValidateQueryForInjection mocks base method.
func (m *MockSecurityUseCase) ValidateQueryForInjection(ctx context.Context, query string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateQueryForInjection", ctx, query)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateQueryForInjection indicates an expected call of ValidateQueryForInjection.
func (mr *MockSecurityUseCaseMockRecorder) ValidateQueryForInjection(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateQueryForInjection", reflect.TypeOf((*MockSecurityUseCase)(nil).ValidateQueryForInjection), ctx, query)
}
