// Code generated by MockGen. DO NOT EDIT.
// Source: /home/kamil5b/REDIKRU/lumen-pg/internal/interfaces/usecase/authentication_usecase.go

// Package mockusecase is a generated GoMock package.
package mockusecase

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/kamil5b/lumen-pg/internal/domain"
)

// MockAuthenticationUseCase is a mock of AuthenticationUseCase interface.
type MockAuthenticationUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticationUseCaseMockRecorder
}

// MockAuthenticationUseCaseMockRecorder is the mock recorder for MockAuthenticationUseCase.
type MockAuthenticationUseCaseMockRecorder struct {
	mock *MockAuthenticationUseCase
}

// NewMockAuthenticationUseCase creates a new mock instance.
func NewMockAuthenticationUseCase(ctrl *gomock.Controller) *MockAuthenticationUseCase {
	mock := &MockAuthenticationUseCase{ctrl: ctrl}
	mock.recorder = &MockAuthenticationUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthenticationUseCase) EXPECT() *MockAuthenticationUseCaseMockRecorder {
	return m.recorder
}

// CreateSession mocks base method.
func (m *MockAuthenticationUseCase) CreateSession(ctx context.Context, username, password, database, schema, table string) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, username, password, database, schema, table)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockAuthenticationUseCaseMockRecorder) CreateSession(ctx, username, password, database, schema, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockAuthenticationUseCase)(nil).CreateSession), ctx, username, password, database, schema, table)
}

// GetFirstAccessibleDatabase mocks base method.
func (m *MockAuthenticationUseCase) GetFirstAccessibleDatabase(ctx context.Context, username string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFirstAccessibleDatabase", ctx, username)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFirstAccessibleDatabase indicates an expected call of GetFirstAccessibleDatabase.
func (mr *MockAuthenticationUseCaseMockRecorder) GetFirstAccessibleDatabase(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFirstAccessibleDatabase", reflect.TypeOf((*MockAuthenticationUseCase)(nil).GetFirstAccessibleDatabase), ctx, username)
}

// GetFirstAccessibleSchema mocks base method.
func (m *MockAuthenticationUseCase) GetFirstAccessibleSchema(ctx context.Context, username, database string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFirstAccessibleSchema", ctx, username, database)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFirstAccessibleSchema indicates an expected call of GetFirstAccessibleSchema.
func (mr *MockAuthenticationUseCaseMockRecorder) GetFirstAccessibleSchema(ctx, username, database interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFirstAccessibleSchema", reflect.TypeOf((*MockAuthenticationUseCase)(nil).GetFirstAccessibleSchema), ctx, username, database)
}

// GetFirstAccessibleTable mocks base method.
func (m *MockAuthenticationUseCase) GetFirstAccessibleTable(ctx context.Context, username, database, schema string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFirstAccessibleTable", ctx, username, database, schema)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFirstAccessibleTable indicates an expected call of GetFirstAccessibleTable.
func (mr *MockAuthenticationUseCaseMockRecorder) GetFirstAccessibleTable(ctx, username, database, schema interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFirstAccessibleTable", reflect.TypeOf((*MockAuthenticationUseCase)(nil).GetFirstAccessibleTable), ctx, username, database, schema)
}

// GetSessionUser mocks base method.
func (m *MockAuthenticationUseCase) GetSessionUser(ctx context.Context, sessionID string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionUser", ctx, sessionID)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionUser indicates an expected call of GetSessionUser.
func (mr *MockAuthenticationUseCaseMockRecorder) GetSessionUser(ctx, sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionUser", reflect.TypeOf((*MockAuthenticationUseCase)(nil).GetSessionUser), ctx, sessionID)
}

// GetUserAccessibleResources mocks base method.
func (m *MockAuthenticationUseCase) GetUserAccessibleResources(ctx context.Context, username string) (*domain.RoleMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAccessibleResources", ctx, username)
	ret0, _ := ret[0].(*domain.RoleMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAccessibleResources indicates an expected call of GetUserAccessibleResources.
func (mr *MockAuthenticationUseCaseMockRecorder) GetUserAccessibleResources(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAccessibleResources", reflect.TypeOf((*MockAuthenticationUseCase)(nil).GetUserAccessibleResources), ctx, username)
}

// IsUserAuthenticated mocks base method.
func (m *MockAuthenticationUseCase) IsUserAuthenticated(ctx context.Context, sessionID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserAuthenticated", ctx, sessionID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsUserAuthenticated indicates an expected call of IsUserAuthenticated.
func (mr *MockAuthenticationUseCaseMockRecorder) IsUserAuthenticated(ctx, sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserAuthenticated", reflect.TypeOf((*MockAuthenticationUseCase)(nil).IsUserAuthenticated), ctx, sessionID)
}

// Login mocks base method.
func (m *MockAuthenticationUseCase) Login(ctx context.Context, req domain.LoginRequest) (*domain.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, req)
	ret0, _ := ret[0].(*domain.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthenticationUseCaseMockRecorder) Login(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthenticationUseCase)(nil).Login), ctx, req)
}

// Logout mocks base method.
func (m *MockAuthenticationUseCase) Logout(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthenticationUseCaseMockRecorder) Logout(ctx, sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthenticationUseCase)(nil).Logout), ctx, sessionID)
}

// ProbeConnection mocks base method.
func (m *MockAuthenticationUseCase) ProbeConnection(ctx context.Context, username, password string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProbeConnection", ctx, username, password)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProbeConnection indicates an expected call of ProbeConnection.
func (mr *MockAuthenticationUseCaseMockRecorder) ProbeConnection(ctx, username, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProbeConnection", reflect.TypeOf((*MockAuthenticationUseCase)(nil).ProbeConnection), ctx, username, password)
}

// ReAuthenticateWithPassword mocks base method.
func (m *MockAuthenticationUseCase) ReAuthenticateWithPassword(ctx context.Context, username, encryptedPassword string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReAuthenticateWithPassword", ctx, username, encryptedPassword)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReAuthenticateWithPassword indicates an expected call of ReAuthenticateWithPassword.
func (mr *MockAuthenticationUseCaseMockRecorder) ReAuthenticateWithPassword(ctx, username, encryptedPassword interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReAuthenticateWithPassword", reflect.TypeOf((*MockAuthenticationUseCase)(nil).ReAuthenticateWithPassword), ctx, username, encryptedPassword)
}

// RefreshSession mocks base method.
func (m *MockAuthenticationUseCase) RefreshSession(ctx context.Context, sessionID string) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshSession", ctx, sessionID)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshSession indicates an expected call of RefreshSession.
func (mr *MockAuthenticationUseCaseMockRecorder) RefreshSession(ctx, sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshSession", reflect.TypeOf((*MockAuthenticationUseCase)(nil).RefreshSession), ctx, sessionID)
}

// ValidateLoginForm mocks base method.
func (m *MockAuthenticationUseCase) ValidateLoginForm(ctx context.Context, req domain.LoginRequest) ([]domain.ValidationError, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateLoginForm", ctx, req)
	ret0, _ := ret[0].([]domain.ValidationError)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateLoginForm indicates an expected call of ValidateLoginForm.
func (mr *MockAuthenticationUseCaseMockRecorder) ValidateLoginForm(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateLoginForm", reflect.TypeOf((*MockAuthenticationUseCase)(nil).ValidateLoginForm), ctx, req)
}

// ValidateSession mocks base method.
func (m *MockAuthenticationUseCase) ValidateSession(ctx context.Context, sessionID string) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSession", ctx, sessionID)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateSession indicates an expected call of ValidateSession.
func (mr *MockAuthenticationUseCaseMockRecorder) ValidateSession(ctx, sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSession", reflect.TypeOf((*MockAuthenticationUseCase)(nil).ValidateSession), ctx, sessionID)
}
