// Code generated by MockGen. DO NOT EDIT.
// Source: /home/kamil5b/REDIKRU/lumen-pg/internal/interfaces/usecase/setup_usecase.go

// Package mockusecase is a generated GoMock package.
package mockusecase

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/kamil5b/lumen-pg/internal/domain"
)

// MockSetupUseCase is a mock of SetupUseCase interface.
type MockSetupUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockSetupUseCaseMockRecorder
}

// MockSetupUseCaseMockRecorder is the mock recorder for MockSetupUseCase.
type MockSetupUseCaseMockRecorder struct {
	mock *MockSetupUseCase
}

// NewMockSetupUseCase creates a new mock instance.
func NewMockSetupUseCase(ctrl *gomock.Controller) *MockSetupUseCase {
	mock := &MockSetupUseCase{ctrl: ctrl}
	mock.recorder = &MockSetupUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSetupUseCase) EXPECT() *MockSetupUseCaseMockRecorder {
	return m.recorder
}

// GetAllRoles mocks base method.
func (m *MockSetupUseCase) GetAllRoles(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllRoles", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllRoles indicates an expected call of GetAllRoles.
func (mr *MockSetupUseCaseMockRecorder) GetAllRoles(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllRoles", reflect.TypeOf((*MockSetupUseCase)(nil).GetAllRoles), ctx)
}

// GetRoleAccessibility mocks base method.
func (m *MockSetupUseCase) GetRoleAccessibility(ctx context.Context, role string) (*domain.RoleMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleAccessibility", ctx, role)
	ret0, _ := ret[0].(*domain.RoleMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoleAccessibility indicates an expected call of GetRoleAccessibility.
func (mr *MockSetupUseCaseMockRecorder) GetRoleAccessibility(ctx, role interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleAccessibility", reflect.TypeOf((*MockSetupUseCase)(nil).GetRoleAccessibility), ctx, role)
}

// InitializeMetadata mocks base method.
func (m *MockSetupUseCase) InitializeMetadata(ctx context.Context, connString string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitializeMetadata", ctx, connString)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitializeMetadata indicates an expected call of InitializeMetadata.
func (mr *MockSetupUseCaseMockRecorder) InitializeMetadata(ctx, connString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitializeMetadata", reflect.TypeOf((*MockSetupUseCase)(nil).InitializeMetadata), ctx, connString)
}

// InitializeRBAC mocks base method.
func (m *MockSetupUseCase) InitializeRBAC(ctx context.Context, connString string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitializeRBAC", ctx, connString)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitializeRBAC indicates an expected call of InitializeRBAC.
func (mr *MockSetupUseCaseMockRecorder) InitializeRBAC(ctx, connString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitializeRBAC", reflect.TypeOf((*MockSetupUseCase)(nil).InitializeRBAC), ctx, connString)
}

// IsInitialized mocks base method.
func (m *MockSetupUseCase) IsInitialized(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsInitialized", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsInitialized indicates an expected call of IsInitialized.
func (mr *MockSetupUseCaseMockRecorder) IsInitialized(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsInitialized", reflect.TypeOf((*MockSetupUseCase)(nil).IsInitialized), ctx)
}

// ParseConnectionString mocks base method.
func (m *MockSetupUseCase) ParseConnectionString(ctx context.Context, connString string) (*domain.ConnectionString, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseConnectionString", ctx, connString)
	ret0, _ := ret[0].(*domain.ConnectionString)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseConnectionString indicates an expected call of ParseConnectionString.
func (mr *MockSetupUseCaseMockRecorder) ParseConnectionString(ctx, connString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseConnectionString", reflect.TypeOf((*MockSetupUseCase)(nil).ParseConnectionString), ctx, connString)
}

// RefreshMetadata mocks base method.
func (m *MockSetupUseCase) RefreshMetadata(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshMetadata", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefreshMetadata indicates an expected call of RefreshMetadata.
func (mr *MockSetupUseCaseMockRecorder) RefreshMetadata(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshMetadata", reflect.TypeOf((*MockSetupUseCase)(nil).RefreshMetadata), ctx)
}

// RefreshRBACMetadata mocks base method.
func (m *MockSetupUseCase) RefreshRBACMetadata(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshRBACMetadata", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefreshRBACMetadata indicates an expected call of RefreshRBACMetadata.
func (mr *MockSetupUseCaseMockRecorder) RefreshRBACMetadata(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshRBACMetadata", reflect.TypeOf((*MockSetupUseCase)(nil).RefreshRBACMetadata), ctx)
}

// TestSuperadminConnection mocks base method.
func (m *MockSetupUseCase) TestSuperadminConnection(ctx context.Context, connString string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TestSuperadminConnection", ctx, connString)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TestSuperadminConnection indicates an expected call of TestSuperadminConnection.
func (mr *MockSetupUseCaseMockRecorder) TestSuperadminConnection(ctx, connString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestSuperadminConnection", reflect.TypeOf((*MockSetupUseCase)(nil).TestSuperadminConnection), ctx, connString)
}

// ValidateConnectionString mocks base method.
func (m *MockSetupUseCase) ValidateConnectionString(ctx context.Context, connString string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateConnectionString", ctx, connString)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateConnectionString indicates an expected call of ValidateConnectionString.
func (mr *MockSetupUseCaseMockRecorder) ValidateConnectionString(ctx, connString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateConnectionString", reflect.TypeOf((*MockSetupUseCase)(nil).ValidateConnectionString), ctx, connString)
}
