// Code generated by MockGen. DO NOT EDIT.
// Source: /home/kamil5b/REDIKRU/lumen-pg/internal/interfaces/usecase/dataview_usecase.go

// Package mockusecase is a generated GoMock package.
package mockusecase

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/kamil5b/lumen-pg/internal/domain"
)

// MockDataViewUseCase is a mock of DataViewUseCase interface.
type MockDataViewUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockDataViewUseCaseMockRecorder
}

// MockDataViewUseCaseMockRecorder is the mock recorder for MockDataViewUseCase.
type MockDataViewUseCaseMockRecorder struct {
	mock *MockDataViewUseCase
}

// NewMockDataViewUseCase creates a new mock instance.
func NewMockDataViewUseCase(ctrl *gomock.Controller) *MockDataViewUseCase {
	mock := &MockDataViewUseCase{ctrl: ctrl}
	mock.recorder = &MockDataViewUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataViewUseCase) EXPECT() *MockDataViewUseCaseMockRecorder {
	return m.recorder
}

// FilterTableData mocks base method.
func (m *MockDataViewUseCase) FilterTableData(ctx context.Context, username, database, schema, table, whereClause string, offset, limit int) (*domain.QueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterTableData", ctx, username, database, schema, table, whereClause, offset, limit)
	ret0, _ := ret[0].(*domain.QueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterTableData indicates an expected call of FilterTableData.
func (mr *MockDataViewUseCaseMockRecorder) FilterTableData(ctx, username, database, schema, table, whereClause, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterTableData", reflect.TypeOf((*MockDataViewUseCase)(nil).FilterTableData), ctx, username, database, schema, table, whereClause, offset, limit)
}

// GetChildTableReferences mocks base method.
func (m *MockDataViewUseCase) GetChildTableReferences(ctx context.Context, username, database, schema, table string, pkValues map[string]interface{}) ([]domain.ChildTableReference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChildTableReferences", ctx, username, database, schema, table, pkValues)
	ret0, _ := ret[0].([]domain.ChildTableReference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChildTableReferences indicates an expected call of GetChildTableReferences.
func (mr *MockDataViewUseCaseMockRecorder) GetChildTableReferences(ctx, username, database, schema, table, pkValues interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChildTableReferences", reflect.TypeOf((*MockDataViewUseCase)(nil).GetChildTableReferences), ctx, username, database, schema, table, pkValues)
}

// GetChildTableRowCount mocks base method.
func (m *MockDataViewUseCase) GetChildTableRowCount(ctx context.Context, username, database, schema, childTable, parentTable, fkColumn, pkValue string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChildTableRowCount", ctx, username, database, schema, childTable, parentTable, fkColumn, pkValue)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChildTableRowCount indicates an expected call of GetChildTableRowCount.
func (mr *MockDataViewUseCaseMockRecorder) GetChildTableRowCount(ctx, username, database, schema, childTable, parentTable, fkColumn, pkValue interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChildTableRowCount", reflect.TypeOf((*MockDataViewUseCase)(nil).GetChildTableRowCount), ctx, username, database, schema, childTable, parentTable, fkColumn, pkValue)
}

// GetForeignKeyInfo mocks base method.
func (m *MockDataViewUseCase) GetForeignKeyInfo(ctx context.Context, username, database, schema, table string) ([]domain.ForeignKeyInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetForeignKeyInfo", ctx, username, database, schema, table)
	ret0, _ := ret[0].([]domain.ForeignKeyInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetForeignKeyInfo indicates an expected call of GetForeignKeyInfo.
func (mr *MockDataViewUseCaseMockRecorder) GetForeignKeyInfo(ctx, username, database, schema, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetForeignKeyInfo", reflect.TypeOf((*MockDataViewUseCase)(nil).GetForeignKeyInfo), ctx, username, database, schema, table)
}

// GetPrimaryKeyInfo mocks base method.
func (m *MockDataViewUseCase) GetPrimaryKeyInfo(ctx context.Context, username, database, schema, table string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrimaryKeyInfo", ctx, username, database, schema, table)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrimaryKeyInfo indicates an expected call of GetPrimaryKeyInfo.
func (mr *MockDataViewUseCaseMockRecorder) GetPrimaryKeyInfo(ctx, username, database, schema, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrimaryKeyInfo", reflect.TypeOf((*MockDataViewUseCase)(nil).GetPrimaryKeyInfo), ctx, username, database, schema, table)
}

// GetTableDataWithCursorPagination mocks base method.
func (m *MockDataViewUseCase) GetTableDataWithCursorPagination(ctx context.Context, username, database, schema, table, cursor string, limit int) (*domain.QueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTableDataWithCursorPagination", ctx, username, database, schema, table, cursor, limit)
	ret0, _ := ret[0].(*domain.QueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTableDataWithCursorPagination indicates an expected call of GetTableDataWithCursorPagination.
func (mr *MockDataViewUseCaseMockRecorder) GetTableDataWithCursorPagination(ctx, username, database, schema, table, cursor, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTableDataWithCursorPagination", reflect.TypeOf((*MockDataViewUseCase)(nil).GetTableDataWithCursorPagination), ctx, username, database, schema, table, cursor, limit)
}

// GetTableRowCount mocks base method.
func (m *MockDataViewUseCase) GetTableRowCount(ctx context.Context, username, database, schema, table string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTableRowCount", ctx, username, database, schema, table)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTableRowCount indicates an expected call of GetTableRowCount.
func (mr *MockDataViewUseCaseMockRecorder) GetTableRowCount(ctx, username, database, schema, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTableRowCount", reflect.TypeOf((*MockDataViewUseCase)(nil).GetTableRowCount), ctx, username, database, schema, table)
}

// GetTableRowCountWithFilter mocks base method.
func (m *MockDataViewUseCase) GetTableRowCountWithFilter(ctx context.Context, username, database, schema, table, whereClause string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTableRowCountWithFilter", ctx, username, database, schema, table, whereClause)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTableRowCountWithFilter indicates an expected call of GetTableRowCountWithFilter.
func (mr *MockDataViewUseCaseMockRecorder) GetTableRowCountWithFilter(ctx, username, database, schema, table, whereClause interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTableRowCountWithFilter", reflect.TypeOf((*MockDataViewUseCase)(nil).GetTableRowCountWithFilter), ctx, username, database, schema, table, whereClause)
}

// IsTableReadOnly mocks base method.
func (m *MockDataViewUseCase) IsTableReadOnly(ctx context.Context, username, database, schema, table string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTableReadOnly", ctx, username, database, schema, table)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsTableReadOnly indicates an expected call of IsTableReadOnly.
func (mr *MockDataViewUseCaseMockRecorder) IsTableReadOnly(ctx, username, database, schema, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTableReadOnly", reflect.TypeOf((*MockDataViewUseCase)(nil).IsTableReadOnly), ctx, username, database, schema, table)
}

// LoadTableData mocks base method.
func (m *MockDataViewUseCase) LoadTableData(ctx context.Context, username string, params domain.TableDataParams) (*domain.QueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadTableData", ctx, username, params)
	ret0, _ := ret[0].(*domain.QueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadTableData indicates an expected call of LoadTableData.
func (mr *MockDataViewUseCaseMockRecorder) LoadTableData(ctx, username, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadTableData", reflect.TypeOf((*MockDataViewUseCase)(nil).LoadTableData), ctx, username, params)
}

// NavigateToChildRows mocks base method.
func (m *MockDataViewUseCase) NavigateToChildRows(ctx context.Context, username, database, schema, childTable, parentTable, fkColumn, pkColumn, pkValue string) (*domain.QueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NavigateToChildRows", ctx, username, database, schema, childTable, parentTable, fkColumn, pkColumn, pkValue)
	ret0, _ := ret[0].(*domain.QueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NavigateToChildRows indicates an expected call of NavigateToChildRows.
func (mr *MockDataViewUseCaseMockRecorder) NavigateToChildRows(ctx, username, database, schema, childTable, parentTable, fkColumn, pkColumn, pkValue interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NavigateToChildRows", reflect.TypeOf((*MockDataViewUseCase)(nil).NavigateToChildRows), ctx, username, database, schema, childTable, parentTable, fkColumn, pkColumn, pkValue)
}

// NavigateToParentRow mocks base method.
func (m *MockDataViewUseCase) NavigateToParentRow(ctx context.Context, username, database, schema, table, columnName string, value interface{}) (*domain.QueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NavigateToParentRow", ctx, username, database, schema, table, columnName, value)
	ret0, _ := ret[0].(*domain.QueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NavigateToParentRow indicates an expected call of NavigateToParentRow.
func (mr *MockDataViewUseCaseMockRecorder) NavigateToParentRow(ctx, username, database, schema, table, columnName, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NavigateToParentRow", reflect.TypeOf((*MockDataViewUseCase)(nil).NavigateToParentRow), ctx, username, database, schema, table, columnName, value)
}

// SortTableData mocks base method.
func (m *MockDataViewUseCase) SortTableData(ctx context.Context, username, database, schema, table, orderBy, orderDir string, offset, limit int) (*domain.QueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SortTableData", ctx, username, database, schema, table, orderBy, orderDir, offset, limit)
	ret0, _ := ret[0].(*domain.QueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SortTableData indicates an expected call of SortTableData.
func (mr *MockDataViewUseCaseMockRecorder) SortTableData(ctx, username, database, schema, table, orderBy, orderDir, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SortTableData", reflect.TypeOf((*MockDataViewUseCase)(nil).SortTableData), ctx, username, database, schema, table, orderBy, orderDir, offset, limit)
}

// ValidateWhereClause mocks base method.
func (m *MockDataViewUseCase) ValidateWhereClause(ctx context.Context, whereClause string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateWhereClause", ctx, whereClause)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateWhereClause indicates an expected call of ValidateWhereClause.
func (mr *MockDataViewUseCaseMockRecorder) ValidateWhereClause(ctx, whereClause interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateWhereClause", reflect.TypeOf((*MockDataViewUseCase)(nil).ValidateWhereClause), ctx, whereClause)
}
