// Code generated by MockGen. DO NOT EDIT.
// Source: /home/kamil5b/REDIKRU/lumen-pg/internal/interfaces/usecase/transaction_usecase.go

// Package mockusecase is a generated GoMock package.
package mockusecase

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/kamil5b/lumen-pg/internal/domain"
)

// MockTransactionUseCase is a mock of TransactionUseCase interface.
type MockTransactionUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionUseCaseMockRecorder
}

// MockTransactionUseCaseMockRecorder is the mock recorder for MockTransactionUseCase.
type MockTransactionUseCaseMockRecorder struct {
	mock *MockTransactionUseCase
}

// NewMockTransactionUseCase creates a new mock instance.
func NewMockTransactionUseCase(ctrl *gomock.Controller) *MockTransactionUseCase {
	mock := &MockTransactionUseCase{ctrl: ctrl}
	mock.recorder = &MockTransactionUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionUseCase) EXPECT() *MockTransactionUseCaseMockRecorder {
	return m.recorder
}

// CancelExpiredTransactions mocks base method.
func (m *MockTransactionUseCase) CancelExpiredTransactions(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelExpiredTransactions", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelExpiredTransactions indicates an expected call of CancelExpiredTransactions.
func (mr *MockTransactionUseCaseMockRecorder) CancelExpiredTransactions(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelExpiredTransactions", reflect.TypeOf((*MockTransactionUseCase)(nil).CancelExpiredTransactions), ctx)
}

// CheckActiveTransaction mocks base method.
func (m *MockTransactionUseCase) CheckActiveTransaction(ctx context.Context, username string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckActiveTransaction", ctx, username)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckActiveTransaction indicates an expected call of CheckActiveTransaction.
func (mr *MockTransactionUseCaseMockRecorder) CheckActiveTransaction(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckActiveTransaction", reflect.TypeOf((*MockTransactionUseCase)(nil).CheckActiveTransaction), ctx, username)
}

// CommitTransaction mocks base method.
func (m *MockTransactionUseCase) CommitTransaction(ctx context.Context, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitTransaction", ctx, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitTransaction indicates an expected call of CommitTransaction.
func (mr *MockTransactionUseCaseMockRecorder) CommitTransaction(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitTransaction", reflect.TypeOf((*MockTransactionUseCase)(nil).CommitTransaction), ctx, username)
}

// DeleteRow mocks base method.
func (m *MockTransactionUseCase) DeleteRow(ctx context.Context, username, database, schema, table string, rowIndex int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRow", ctx, username, database, schema, table, rowIndex)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRow indicates an expected call of DeleteRow.
func (mr *MockTransactionUseCaseMockRecorder) DeleteRow(ctx, username, database, schema, table, rowIndex interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRow", reflect.TypeOf((*MockTransactionUseCase)(nil).DeleteRow), ctx, username, database, schema, table, rowIndex)
}

// EditCell mocks base method.
func (m *MockTransactionUseCase) EditCell(ctx context.Context, username, database, schema, table string, rowIndex int, columnName string, newValue interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditCell", ctx, username, database, schema, table, rowIndex, columnName, newValue)
	ret0, _ := ret[0].(error)
	return ret0
}

// EditCell indicates an expected call of EditCell.
func (mr *MockTransactionUseCaseMockRecorder) EditCell(ctx, username, database, schema, table, rowIndex, columnName, newValue interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditCell", reflect.TypeOf((*MockTransactionUseCase)(nil).EditCell), ctx, username, database, schema, table, rowIndex, columnName, newValue)
}

// GetActiveTransaction mocks base method.
func (m *MockTransactionUseCase) GetActiveTransaction(ctx context.Context, username string) (*domain.TransactionState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveTransaction", ctx, username)
	ret0, _ := ret[0].(*domain.TransactionState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveTransaction indicates an expected call of GetActiveTransaction.
func (mr *MockTransactionUseCaseMockRecorder) GetActiveTransaction(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveTransaction", reflect.TypeOf((*MockTransactionUseCase)(nil).GetActiveTransaction), ctx, username)
}

// GetTransactionDeletes mocks base method.
func (m *MockTransactionUseCase) GetTransactionDeletes(ctx context.Context, username string) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionDeletes", ctx, username)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionDeletes indicates an expected call of GetTransactionDeletes.
func (mr *MockTransactionUseCaseMockRecorder) GetTransactionDeletes(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionDeletes", reflect.TypeOf((*MockTransactionUseCase)(nil).GetTransactionDeletes), ctx, username)
}

// GetTransactionEdits mocks base method.
func (m *MockTransactionUseCase) GetTransactionEdits(ctx context.Context, username string) (map[int]domain.RowEdit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionEdits", ctx, username)
	ret0, _ := ret[0].(map[int]domain.RowEdit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionEdits indicates an expected call of GetTransactionEdits.
func (mr *MockTransactionUseCaseMockRecorder) GetTransactionEdits(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionEdits", reflect.TypeOf((*MockTransactionUseCase)(nil).GetTransactionEdits), ctx, username)
}

// GetTransactionInserts mocks base method.
func (m *MockTransactionUseCase) GetTransactionInserts(ctx context.Context, username string) ([]domain.RowInsert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionInserts", ctx, username)
	ret0, _ := ret[0].([]domain.RowInsert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionInserts indicates an expected call of GetTransactionInserts.
func (mr *MockTransactionUseCaseMockRecorder) GetTransactionInserts(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionInserts", reflect.TypeOf((*MockTransactionUseCase)(nil).GetTransactionInserts), ctx, username)
}

// GetTransactionRemainingTime mocks base method.
func (m *MockTransactionUseCase) GetTransactionRemainingTime(ctx context.Context, username string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionRemainingTime", ctx, username)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionRemainingTime indicates an expected call of GetTransactionRemainingTime.
func (mr *MockTransactionUseCaseMockRecorder) GetTransactionRemainingTime(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionRemainingTime", reflect.TypeOf((*MockTransactionUseCase)(nil).GetTransactionRemainingTime), ctx, username)
}

// InsertRow mocks base method.
func (m *MockTransactionUseCase) InsertRow(ctx context.Context, username, database, schema, table string, values map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertRow", ctx, username, database, schema, table, values)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertRow indicates an expected call of InsertRow.
func (mr *MockTransactionUseCaseMockRecorder) InsertRow(ctx, username, database, schema, table, values interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertRow", reflect.TypeOf((*MockTransactionUseCase)(nil).InsertRow), ctx, username, database, schema, table, values)
}

// IsTransactionExpired mocks base method.
func (m *MockTransactionUseCase) IsTransactionExpired(ctx context.Context, username string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTransactionExpired", ctx, username)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsTransactionExpired indicates an expected call of IsTransactionExpired.
func (mr *MockTransactionUseCaseMockRecorder) IsTransactionExpired(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTransactionExpired", reflect.TypeOf((*MockTransactionUseCase)(nil).IsTransactionExpired), ctx, username)
}

// RollbackTransaction mocks base method.
func (m *MockTransactionUseCase) RollbackTransaction(ctx context.Context, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackTransaction", ctx, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// RollbackTransaction indicates an expected call of RollbackTransaction.
func (mr *MockTransactionUseCaseMockRecorder) RollbackTransaction(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackTransaction", reflect.TypeOf((*MockTransactionUseCase)(nil).RollbackTransaction), ctx, username)
}

// StartTransaction mocks base method.
func (m *MockTransactionUseCase) StartTransaction(ctx context.Context, username, database, schema, table string) (*domain.TransactionState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartTransaction", ctx, username, database, schema, table)
	ret0, _ := ret[0].(*domain.TransactionState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartTransaction indicates an expected call of StartTransaction.
func (mr *MockTransactionUseCaseMockRecorder) StartTransaction(ctx, username, database, schema, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartTransaction", reflect.TypeOf((*MockTransactionUseCase)(nil).StartTransaction), ctx, username, database, schema, table)
}
