// Code generated by MockGen. DO NOT EDIT.
// Source: /home/kamil5b/REDIKRU/lumen-pg/internal/interfaces/usecase/erd_usecase.go

// Package mockusecase is a generated GoMock package.
package mockusecase

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/kamil5b/lumen-pg/internal/domain"
)

// MockERDUseCase is a mock of ERDUseCase interface.
type MockERDUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockERDUseCaseMockRecorder
}

// MockERDUseCaseMockRecorder is the mock recorder for MockERDUseCase.
type MockERDUseCaseMockRecorder struct {
	mock *MockERDUseCase
}

// NewMockERDUseCase creates a new mock instance.
func NewMockERDUseCase(ctrl *gomock.Controller) *MockERDUseCase {
	mock := &MockERDUseCase{ctrl: ctrl}
	mock.recorder = &MockERDUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockERDUseCase) EXPECT() *MockERDUseCaseMockRecorder {
	return m.recorder
}

// GenerateERD mocks base method.
func (m *MockERDUseCase) GenerateERD(ctx context.Context, username, database, schema string) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateERD", ctx, username, database, schema)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateERD indicates an expected call of GenerateERD.
func (mr *MockERDUseCaseMockRecorder) GenerateERD(ctx, username, database, schema interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateERD", reflect.TypeOf((*MockERDUseCase)(nil).GenerateERD), ctx, username, database, schema)
}

// GetAvailableSchemas mocks base method.
func (m *MockERDUseCase) GetAvailableSchemas(ctx context.Context, username, database string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableSchemas", ctx, username, database)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableSchemas indicates an expected call of GetAvailableSchemas.
func (mr *MockERDUseCaseMockRecorder) GetAvailableSchemas(ctx, username, database interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableSchemas", reflect.TypeOf((*MockERDUseCase)(nil).GetAvailableSchemas), ctx, username, database)
}

// GetERDRelationships mocks base method.
func (m *MockERDUseCase) GetERDRelationships(ctx context.Context, username, database, schema string) ([]domain.ForeignKeyMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetERDRelationships", ctx, username, database, schema)
	ret0, _ := ret[0].([]domain.ForeignKeyMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetERDRelationships indicates an expected call of GetERDRelationships.
func (mr *MockERDUseCaseMockRecorder) GetERDRelationships(ctx, username, database, schema interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetERDRelationships", reflect.TypeOf((*MockERDUseCase)(nil).GetERDRelationships), ctx, username, database, schema)
}

// GetERDTables mocks base method.
func (m *MockERDUseCase) GetERDTables(ctx context.Context, username, database, schema string) ([]domain.TableMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetERDTables", ctx, username, database, schema)
	ret0, _ := ret[0].([]domain.TableMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetERDTables indicates an expected call of GetERDTables.
func (mr *MockERDUseCaseMockRecorder) GetERDTables(ctx, username, database, schema interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetERDTables", reflect.TypeOf((*MockERDUseCase)(nil).GetERDTables), ctx, username, database, schema)
}

// GetRelationshipLines mocks base method.
func (m *MockERDUseCase) GetRelationshipLines(ctx context.Context, username, database, schema string) ([]map[string]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRelationshipLines", ctx, username, database, schema)
	ret0, _ := ret[0].([]map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRelationshipLines indicates an expected call of GetRelationshipLines.
func (mr *MockERDUseCaseMockRecorder) GetRelationshipLines(ctx, username, database, schema interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRelationshipLines", reflect.TypeOf((*MockERDUseCase)(nil).GetRelationshipLines), ctx, username, database, schema)
}

// GetTableBoxData mocks base method.
func (m *MockERDUseCase) GetTableBoxData(ctx context.Context, username, database, schema, table string) (*domain.TableMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTableBoxData", ctx, username, database, schema, table)
	ret0, _ := ret[0].(*domain.TableMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTableBoxData indicates an expected call of GetTableBoxData.
func (mr *MockERDUseCaseMockRecorder) GetTableBoxData(ctx, username, database, schema, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTableBoxData", reflect.TypeOf((*MockERDUseCase)(nil).GetTableBoxData), ctx, username, database, schema, table)
}

// IsSchemaEmpty mocks base method.
func (m *MockERDUseCase) IsSchemaEmpty(ctx context.Context, username, database, schema string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSchemaEmpty", ctx, username, database, schema)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSchemaEmpty indicates an expected call of IsSchemaEmpty.
func (mr *MockERDUseCaseMockRecorder) IsSchemaEmpty(ctx, username, database, schema interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSchemaEmpty", reflect.TypeOf((*MockERDUseCase)(nil).IsSchemaEmpty), ctx, username, database, schema)
}
