// Code generated by MockGen. DO NOT EDIT.
// Source: /home/kamil5b/REDIKRU/lumen-pg/internal/interfaces/repository/rbac_repository.go

// Package mockrepository is a generated GoMock package.
package mockrepository

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/kamil5b/lumen-pg/internal/domain"
)

// MockRBACRepository is a mock of RBACRepository interface.
type MockRBACRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRBACRepositoryMockRecorder
}

// MockRBACRepositoryMockRecorder is the mock recorder for MockRBACRepository.
type MockRBACRepositoryMockRecorder struct {
	mock *MockRBACRepository
}

// NewMockRBACRepository creates a new mock instance.
func NewMockRBACRepository(ctrl *gomock.Controller) *MockRBACRepository {
	mock := &MockRBACRepository{ctrl: ctrl}
	mock.recorder = &MockRBACRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRBACRepository) EXPECT() *MockRBACRepositoryMockRecorder {
	return m.recorder
}

// CanAccessTable mocks base method.
func (m *MockRBACRepository) CanAccessTable(ctx context.Context, role, database, schema, table string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanAccessTable", ctx, role, database, schema, table)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanAccessTable indicates an expected call of CanAccessTable.
func (mr *MockRBACRepositoryMockRecorder) CanAccessTable(ctx, role, database, schema, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanAccessTable", reflect.TypeOf((*MockRBACRepository)(nil).CanAccessTable), ctx, role, database, schema, table)
}

// GetAccessibleDatabases mocks base method.
func (m *MockRBACRepository) GetAccessibleDatabases(ctx context.Context, role string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessibleDatabases", ctx, role)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessibleDatabases indicates an expected call of GetAccessibleDatabases.
func (mr *MockRBACRepositoryMockRecorder) GetAccessibleDatabases(ctx, role interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessibleDatabases", reflect.TypeOf((*MockRBACRepository)(nil).GetAccessibleDatabases), ctx, role)
}

// GetAccessibleSchemas mocks base method.
func (m *MockRBACRepository) GetAccessibleSchemas(ctx context.Context, role, database string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessibleSchemas", ctx, role, database)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessibleSchemas indicates an expected call of GetAccessibleSchemas.
func (mr *MockRBACRepositoryMockRecorder) GetAccessibleSchemas(ctx, role, database interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessibleSchemas", reflect.TypeOf((*MockRBACRepository)(nil).GetAccessibleSchemas), ctx, role, database)
}

// GetAccessibleTables mocks base method.
func (m *MockRBACRepository) GetAccessibleTables(ctx context.Context, role, database, schema string) ([]domain.AccessibleTable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessibleTables", ctx, role, database, schema)
	ret0, _ := ret[0].([]domain.AccessibleTable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessibleTables indicates an expected call of GetAccessibleTables.
func (mr *MockRBACRepositoryMockRecorder) GetAccessibleTables(ctx, role, database, schema interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessibleTables", reflect.TypeOf((*MockRBACRepository)(nil).GetAccessibleTables), ctx, role, database, schema)
}

// GetAllRoles mocks base method.
func (m *MockRBACRepository) GetAllRoles(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllRoles", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllRoles indicates an expected call of GetAllRoles.
func (mr *MockRBACRepositoryMockRecorder) GetAllRoles(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllRoles", reflect.TypeOf((*MockRBACRepository)(nil).GetAllRoles), ctx)
}

// GetRoleMetadata mocks base method.
func (m *MockRBACRepository) GetRoleMetadata(ctx context.Context, role string) (*domain.RoleMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleMetadata", ctx, role)
	ret0, _ := ret[0].(*domain.RoleMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoleMetadata indicates an expected call of GetRoleMetadata.
func (mr *MockRBACRepositoryMockRecorder) GetRoleMetadata(ctx, role interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleMetadata", reflect.TypeOf((*MockRBACRepository)(nil).GetRoleMetadata), ctx, role)
}

// GetRolePermissions mocks base method.
func (m *MockRBACRepository) GetRolePermissions(ctx context.Context, role, database, schema, table string) (*domain.PermissionSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRolePermissions", ctx, role, database, schema, table)
	ret0, _ := ret[0].(*domain.PermissionSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRolePermissions indicates an expected call of GetRolePermissions.
func (mr *MockRBACRepositoryMockRecorder) GetRolePermissions(ctx, role, database, schema, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRolePermissions", reflect.TypeOf((*MockRBACRepository)(nil).GetRolePermissions), ctx, role, database, schema, table)
}

// GetUserRole mocks base method.
func (m *MockRBACRepository) GetUserRole(ctx context.Context, username string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRole", ctx, username)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRole indicates an expected call of GetUserRole.
func (mr *MockRBACRepositoryMockRecorder) GetUserRole(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRole", reflect.TypeOf((*MockRBACRepository)(nil).GetUserRole), ctx, username)
}

// HasDatabaseConnectPermission mocks base method.
func (m *MockRBACRepository) HasDatabaseConnectPermission(ctx context.Context, role, database string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasDatabaseConnectPermission", ctx, role, database)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasDatabaseConnectPermission indicates an expected call of HasDatabaseConnectPermission.
func (mr *MockRBACRepositoryMockRecorder) HasDatabaseConnectPermission(ctx, role, database interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasDatabaseConnectPermission", reflect.TypeOf((*MockRBACRepository)(nil).HasDatabaseConnectPermission), ctx, role, database)
}

// HasDeletePermission mocks base method.
func (m *MockRBACRepository) HasDeletePermission(ctx context.Context, role, database, schema, table string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasDeletePermission", ctx, role, database, schema, table)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasDeletePermission indicates an expected call of HasDeletePermission.
func (mr *MockRBACRepositoryMockRecorder) HasDeletePermission(ctx, role, database, schema, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasDeletePermission", reflect.TypeOf((*MockRBACRepository)(nil).HasDeletePermission), ctx, role, database, schema, table)
}

// HasInsertPermission mocks base method.
func (m *MockRBACRepository) HasInsertPermission(ctx context.Context, role, database, schema, table string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasInsertPermission", ctx, role, database, schema, table)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasInsertPermission indicates an expected call of HasInsertPermission.
func (mr *MockRBACRepositoryMockRecorder) HasInsertPermission(ctx, role, database, schema, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasInsertPermission", reflect.TypeOf((*MockRBACRepository)(nil).HasInsertPermission), ctx, role, database, schema, table)
}

// HasSchemaUsagePermission mocks base method.
func (m *MockRBACRepository) HasSchemaUsagePermission(ctx context.Context, role, database, schema string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasSchemaUsagePermission", ctx, role, database, schema)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasSchemaUsagePermission indicates an expected call of HasSchemaUsagePermission.
func (mr *MockRBACRepositoryMockRecorder) HasSchemaUsagePermission(ctx, role, database, schema interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasSchemaUsagePermission", reflect.TypeOf((*MockRBACRepository)(nil).HasSchemaUsagePermission), ctx, role, database, schema)
}

// HasSelectPermission mocks base method.
func (m *MockRBACRepository) HasSelectPermission(ctx context.Context, role, database, schema, table string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasSelectPermission", ctx, role, database, schema, table)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasSelectPermission indicates an expected call of HasSelectPermission.
func (mr *MockRBACRepositoryMockRecorder) HasSelectPermission(ctx, role, database, schema, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasSelectPermission", reflect.TypeOf((*MockRBACRepository)(nil).HasSelectPermission), ctx, role, database, schema, table)
}

// HasUpdatePermission mocks base method.
func (m *MockRBACRepository) HasUpdatePermission(ctx context.Context, role, database, schema, table string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasUpdatePermission", ctx, role, database, schema, table)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasUpdatePermission indicates an expected call of HasUpdatePermission.
func (mr *MockRBACRepositoryMockRecorder) HasUpdatePermission(ctx, role, database, schema, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasUpdatePermission", reflect.TypeOf((*MockRBACRepository)(nil).HasUpdatePermission), ctx, role, database, schema, table)
}

// IsReadOnlyRole mocks base method.
func (m *MockRBACRepository) IsReadOnlyRole(ctx context.Context, role, database, schema, table string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsReadOnlyRole", ctx, role, database, schema, table)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsReadOnlyRole indicates an expected call of IsReadOnlyRole.
func (mr *MockRBACRepositoryMockRecorder) IsReadOnlyRole(ctx, role, database, schema, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsReadOnlyRole", reflect.TypeOf((*MockRBACRepository)(nil).IsReadOnlyRole), ctx, role, database, schema, table)
}

// ValidateUserAccessToResource mocks base method.
func (m *MockRBACRepository) ValidateUserAccessToResource(ctx context.Context, username, resourceType, database, schema, table string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateUserAccessToResource", ctx, username, resourceType, database, schema, table)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateUserAccessToResource indicates an expected call of ValidateUserAccessToResource.
func (mr *MockRBACRepositoryMockRecorder) ValidateUserAccessToResource(ctx, username, resourceType, database, schema, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateUserAccessToResource", reflect.TypeOf((*MockRBACRepository)(nil).ValidateUserAccessToResource), ctx, username, resourceType, database, schema, table)
}
