// Code generated by MockGen. DO NOT EDIT.
// Source: /home/kamil5b/REDIKRU/lumen-pg/internal/interfaces/repository/metadata_repository.go

// Package mockrepository is a generated GoMock package.
package mockrepository

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/kamil5b/lumen-pg/internal/domain"
)

// MockMetadataRepository is a mock of MetadataRepository interface.
type MockMetadataRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMetadataRepositoryMockRecorder
}

// MockMetadataRepositoryMockRecorder is the mock recorder for MockMetadataRepository.
type MockMetadataRepositoryMockRecorder struct {
	mock *MockMetadataRepository
}

// NewMockMetadataRepository creates a new mock instance.
func NewMockMetadataRepository(ctrl *gomock.Controller) *MockMetadataRepository {
	mock := &MockMetadataRepository{ctrl: ctrl}
	mock.recorder = &MockMetadataRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetadataRepository) EXPECT() *MockMetadataRepositoryMockRecorder {
	return m.recorder
}

// GetAccessibleDatabases mocks base method.
func (m *MockMetadataRepository) GetAccessibleDatabases(ctx context.Context, role string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessibleDatabases", ctx, role)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessibleDatabases indicates an expected call of GetAccessibleDatabases.
func (mr *MockMetadataRepositoryMockRecorder) GetAccessibleDatabases(ctx, role interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessibleDatabases", reflect.TypeOf((*MockMetadataRepository)(nil).GetAccessibleDatabases), ctx, role)
}

// GetAccessibleSchemas mocks base method.
func (m *MockMetadataRepository) GetAccessibleSchemas(ctx context.Context, role, database string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessibleSchemas", ctx, role, database)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessibleSchemas indicates an expected call of GetAccessibleSchemas.
func (mr *MockMetadataRepositoryMockRecorder) GetAccessibleSchemas(ctx, role, database interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessibleSchemas", reflect.TypeOf((*MockMetadataRepository)(nil).GetAccessibleSchemas), ctx, role, database)
}

// GetAccessibleTables mocks base method.
func (m *MockMetadataRepository) GetAccessibleTables(ctx context.Context, role, database, schema string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessibleTables", ctx, role, database, schema)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessibleTables indicates an expected call of GetAccessibleTables.
func (mr *MockMetadataRepositoryMockRecorder) GetAccessibleTables(ctx, role, database, schema interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessibleTables", reflect.TypeOf((*MockMetadataRepository)(nil).GetAccessibleTables), ctx, role, database, schema)
}

// GetAllRolesMetadata mocks base method.
func (m *MockMetadataRepository) GetAllRolesMetadata(ctx context.Context) (map[string]*domain.RoleMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllRolesMetadata", ctx)
	ret0, _ := ret[0].(map[string]*domain.RoleMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllRolesMetadata indicates an expected call of GetAllRolesMetadata.
func (mr *MockMetadataRepositoryMockRecorder) GetAllRolesMetadata(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllRolesMetadata", reflect.TypeOf((*MockMetadataRepository)(nil).GetAllRolesMetadata), ctx)
}

// GetMetadata mocks base method.
func (m *MockMetadataRepository) GetMetadata(ctx context.Context, database string) (*domain.DatabaseMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadata", ctx, database)
	ret0, _ := ret[0].(*domain.DatabaseMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetadata indicates an expected call of GetMetadata.
func (mr *MockMetadataRepositoryMockRecorder) GetMetadata(ctx, database interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadata", reflect.TypeOf((*MockMetadataRepository)(nil).GetMetadata), ctx, database)
}

// GetRoleMetadata mocks base method.
func (m *MockMetadataRepository) GetRoleMetadata(ctx context.Context, role string) (*domain.RoleMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleMetadata", ctx, role)
	ret0, _ := ret[0].(*domain.RoleMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoleMetadata indicates an expected call of GetRoleMetadata.
func (mr *MockMetadataRepositoryMockRecorder) GetRoleMetadata(ctx, role interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleMetadata", reflect.TypeOf((*MockMetadataRepository)(nil).GetRoleMetadata), ctx, role)
}

// GetTablePermissions mocks base method.
func (m *MockMetadataRepository) GetTablePermissions(ctx context.Context, role, database, schema, table string) (*domain.AccessibleTable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTablePermissions", ctx, role, database, schema, table)
	ret0, _ := ret[0].(*domain.AccessibleTable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTablePermissions indicates an expected call of GetTablePermissions.
func (mr *MockMetadataRepositoryMockRecorder) GetTablePermissions(ctx, role, database, schema, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTablePermissions", reflect.TypeOf((*MockMetadataRepository)(nil).GetTablePermissions), ctx, role, database, schema, table)
}

// InvalidateAllMetadata mocks base method.
func (m *MockMetadataRepository) InvalidateAllMetadata(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateAllMetadata", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateAllMetadata indicates an expected call of InvalidateAllMetadata.
func (mr *MockMetadataRepositoryMockRecorder) InvalidateAllMetadata(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateAllMetadata", reflect.TypeOf((*MockMetadataRepository)(nil).InvalidateAllMetadata), ctx)
}

// InvalidateMetadata mocks base method.
func (m *MockMetadataRepository) InvalidateMetadata(ctx context.Context, database string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateMetadata", ctx, database)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateMetadata indicates an expected call of InvalidateMetadata.
func (mr *MockMetadataRepositoryMockRecorder) InvalidateMetadata(ctx, database interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateMetadata", reflect.TypeOf((*MockMetadataRepository)(nil).InvalidateMetadata), ctx, database)
}

// InvalidateRoleMetadata mocks base method.
func (m *MockMetadataRepository) InvalidateRoleMetadata(ctx context.Context, role string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateRoleMetadata", ctx, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateRoleMetadata indicates an expected call of InvalidateRoleMetadata.
func (mr *MockMetadataRepositoryMockRecorder) InvalidateRoleMetadata(ctx, role interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateRoleMetadata", reflect.TypeOf((*MockMetadataRepository)(nil).InvalidateRoleMetadata), ctx, role)
}

// IsTableAccessible mocks base method.
func (m *MockMetadataRepository) IsTableAccessible(ctx context.Context, role, database, schema, table string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTableAccessible", ctx, role, database, schema, table)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsTableAccessible indicates an expected call of IsTableAccessible.
func (mr *MockMetadataRepositoryMockRecorder) IsTableAccessible(ctx, role, database, schema, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTableAccessible", reflect.TypeOf((*MockMetadataRepository)(nil).IsTableAccessible), ctx, role, database, schema, table)
}

// StoreAllRolesMetadata mocks base method.
func (m *MockMetadataRepository) StoreAllRolesMetadata(ctx context.Context, roles map[string]*domain.RoleMetadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreAllRolesMetadata", ctx, roles)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreAllRolesMetadata indicates an expected call of StoreAllRolesMetadata.
func (mr *MockMetadataRepositoryMockRecorder) StoreAllRolesMetadata(ctx, roles interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreAllRolesMetadata", reflect.TypeOf((*MockMetadataRepository)(nil).StoreAllRolesMetadata), ctx, roles)
}

// StoreMetadata mocks base method.
func (m *MockMetadataRepository) StoreMetadata(ctx context.Context, metadata *domain.DatabaseMetadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreMetadata", ctx, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreMetadata indicates an expected call of StoreMetadata.
func (mr *MockMetadataRepositoryMockRecorder) StoreMetadata(ctx, metadata interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreMetadata", reflect.TypeOf((*MockMetadataRepository)(nil).StoreMetadata), ctx, metadata)
}

// StoreRoleMetadata mocks base method.
func (m *MockMetadataRepository) StoreRoleMetadata(ctx context.Context, role string, metadata *domain.RoleMetadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreRoleMetadata", ctx, role, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreRoleMetadata indicates an expected call of StoreRoleMetadata.
func (mr *MockMetadataRepositoryMockRecorder) StoreRoleMetadata(ctx, role, metadata interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreRoleMetadata", reflect.TypeOf((*MockMetadataRepository)(nil).StoreRoleMetadata), ctx, role, metadata)
}
