// Code generated by MockGen. DO NOT EDIT.
// Source: /home/kamil5b/REDIKRU/lumen-pg/internal/interfaces/repository/encryption_repository.go

// Package mockrepository is a generated GoMock package.
package mockrepository

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockEncryptionRepository is a mock of EncryptionRepository interface.
type MockEncryptionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEncryptionRepositoryMockRecorder
}

// MockEncryptionRepositoryMockRecorder is the mock recorder for MockEncryptionRepository.
type MockEncryptionRepositoryMockRecorder struct {
	mock *MockEncryptionRepository
}

// NewMockEncryptionRepository creates a new mock instance.
func NewMockEncryptionRepository(ctrl *gomock.Controller) *MockEncryptionRepository {
	mock := &MockEncryptionRepository{ctrl: ctrl}
	mock.recorder = &MockEncryptionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEncryptionRepository) EXPECT() *MockEncryptionRepositoryMockRecorder {
	return m.recorder
}

// ComparePasswordHash mocks base method.
func (m *MockEncryptionRepository) ComparePasswordHash(ctx context.Context, password, hash string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComparePasswordHash", ctx, password, hash)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ComparePasswordHash indicates an expected call of ComparePasswordHash.
func (mr *MockEncryptionRepositoryMockRecorder) ComparePasswordHash(ctx, password, hash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComparePasswordHash", reflect.TypeOf((*MockEncryptionRepository)(nil).ComparePasswordHash), ctx, password, hash)
}

// Decrypt mocks base method.
func (m *MockEncryptionRepository) Decrypt(ctx context.Context, ciphertext string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt", ctx, ciphertext)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockEncryptionRepositoryMockRecorder) Decrypt(ctx, ciphertext interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockEncryptionRepository)(nil).Decrypt), ctx, ciphertext)
}

// Encrypt mocks base method.
func (m *MockEncryptionRepository) Encrypt(ctx context.Context, plaintext string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encrypt", ctx, plaintext)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encrypt indicates an expected call of Encrypt.
func (mr *MockEncryptionRepositoryMockRecorder) Encrypt(ctx, plaintext interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encrypt", reflect.TypeOf((*MockEncryptionRepository)(nil).Encrypt), ctx, plaintext)
}

// GenerateNonce mocks base method.
func (m *MockEncryptionRepository) GenerateNonce(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateNonce", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateNonce indicates an expected call of GenerateNonce.
func (mr *MockEncryptionRepositoryMockRecorder) GenerateNonce(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateNonce", reflect.TypeOf((*MockEncryptionRepository)(nil).GenerateNonce), ctx)
}

// GenerateSecureToken mocks base method.
func (m *MockEncryptionRepository) GenerateSecureToken(ctx context.Context, length int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSecureToken", ctx, length)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateSecureToken indicates an expected call of GenerateSecureToken.
func (mr *MockEncryptionRepositoryMockRecorder) GenerateSecureToken(ctx, length interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSecureToken", reflect.TypeOf((*MockEncryptionRepository)(nil).GenerateSecureToken), ctx, length)
}

// GenerateSignature mocks base method.
func (m *MockEncryptionRepository) GenerateSignature(ctx context.Context, data string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSignature", ctx, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateSignature indicates an expected call of GenerateSignature.
func (mr *MockEncryptionRepositoryMockRecorder) GenerateSignature(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSignature", reflect.TypeOf((*MockEncryptionRepository)(nil).GenerateSignature), ctx, data)
}

// HashPassword mocks base method.
func (m *MockEncryptionRepository) HashPassword(ctx context.Context, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashPassword", ctx, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HashPassword indicates an expected call of HashPassword.
func (mr *MockEncryptionRepositoryMockRecorder) HashPassword(ctx, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashPassword", reflect.TypeOf((*MockEncryptionRepository)(nil).HashPassword), ctx, password)
}

// ValidateSignature mocks base method.
func (m *MockEncryptionRepository) ValidateSignature(ctx context.Context, data, signature string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSignature", ctx, data, signature)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateSignature indicates an expected call of ValidateSignature.
func (mr *MockEncryptionRepositoryMockRecorder) ValidateSignature(ctx, data, signature interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSignature", reflect.TypeOf((*MockEncryptionRepository)(nil).ValidateSignature), ctx, data, signature)
}
