// Code generated by MockGen. DO NOT EDIT.
// Source: /home/kamil5b/REDIKRU/lumen-pg/internal/interfaces/repository/logger_repository.go

// Package mockrepository is a generated GoMock package.
package mockrepository

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLoggerRepository is a mock of LoggerRepository interface.
type MockLoggerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerRepositoryMockRecorder
}

// MockLoggerRepositoryMockRecorder is the mock recorder for MockLoggerRepository.
type MockLoggerRepositoryMockRecorder struct {
	mock *MockLoggerRepository
}

// NewMockLoggerRepository creates a new mock instance.
func NewMockLoggerRepository(ctrl *gomock.Controller) *MockLoggerRepository {
	mock := &MockLoggerRepository{ctrl: ctrl}
	mock.recorder = &MockLoggerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoggerRepository) EXPECT() *MockLoggerRepositoryMockRecorder {
	return m.recorder
}

// LogDebug mocks base method.
func (m *MockLoggerRepository) LogDebug(ctx context.Context, message string, fields map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogDebug", ctx, message, fields)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogDebug indicates an expected call of LogDebug.
func (mr *MockLoggerRepositoryMockRecorder) LogDebug(ctx, message, fields interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogDebug", reflect.TypeOf((*MockLoggerRepository)(nil).LogDebug), ctx, message, fields)
}

// LogError mocks base method.
func (m *MockLoggerRepository) LogError(ctx context.Context, message string, err error, fields map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogError", ctx, message, err, fields)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogError indicates an expected call of LogError.
func (mr *MockLoggerRepositoryMockRecorder) LogError(ctx, message, err, fields interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogError", reflect.TypeOf((*MockLoggerRepository)(nil).LogError), ctx, message, err, fields)
}

// LogInfo mocks base method.
func (m *MockLoggerRepository) LogInfo(ctx context.Context, message string, fields map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogInfo", ctx, message, fields)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogInfo indicates an expected call of LogInfo.
func (mr *MockLoggerRepositoryMockRecorder) LogInfo(ctx, message, fields interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogInfo", reflect.TypeOf((*MockLoggerRepository)(nil).LogInfo), ctx, message, fields)
}

// LogQueryExecution mocks base method.
func (m *MockLoggerRepository) LogQueryExecution(ctx context.Context, username, query string, executionTimeMs int64, success bool, err error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogQueryExecution", ctx, username, query, executionTimeMs, success, err)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogQueryExecution indicates an expected call of LogQueryExecution.
func (mr *MockLoggerRepositoryMockRecorder) LogQueryExecution(ctx, username, query, executionTimeMs, success, err interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogQueryExecution", reflect.TypeOf((*MockLoggerRepository)(nil).LogQueryExecution), ctx, username, query, executionTimeMs, success, err)
}

// LogSecurityEvent mocks base method.
func (m *MockLoggerRepository) LogSecurityEvent(ctx context.Context, eventType, username string, details map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogSecurityEvent", ctx, eventType, username, details)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogSecurityEvent indicates an expected call of LogSecurityEvent.
func (mr *MockLoggerRepositoryMockRecorder) LogSecurityEvent(ctx, eventType, username, details interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogSecurityEvent", reflect.TypeOf((*MockLoggerRepository)(nil).LogSecurityEvent), ctx, eventType, username, details)
}

// LogTransactionEvent mocks base method.
func (m *MockLoggerRepository) LogTransactionEvent(ctx context.Context, username, eventType string, details map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogTransactionEvent", ctx, username, eventType, details)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogTransactionEvent indicates an expected call of LogTransactionEvent.
func (mr *MockLoggerRepositoryMockRecorder) LogTransactionEvent(ctx, username, eventType, details interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogTransactionEvent", reflect.TypeOf((*MockLoggerRepository)(nil).LogTransactionEvent), ctx, username, eventType, details)
}

// LogWarn mocks base method.
func (m *MockLoggerRepository) LogWarn(ctx context.Context, message string, fields map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogWarn", ctx, message, fields)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogWarn indicates an expected call of LogWarn.
func (mr *MockLoggerRepositoryMockRecorder) LogWarn(ctx, message, fields interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogWarn", reflect.TypeOf((*MockLoggerRepository)(nil).LogWarn), ctx, message, fields)
}
