// Code generated by MockGen. DO NOT EDIT.
// Source: /home/kamil5b/REDIKRU/lumen-pg/internal/interfaces/repository/transaction_repository.go

// Package mockrepository is a generated GoMock package.
package mockrepository

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/kamil5b/lumen-pg/internal/domain"
)

// MockTransactionRepository is a mock of TransactionRepository interface.
type MockTransactionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionRepositoryMockRecorder
}

// MockTransactionRepositoryMockRecorder is the mock recorder for MockTransactionRepository.
type MockTransactionRepositoryMockRecorder struct {
	mock *MockTransactionRepository
}

// NewMockTransactionRepository creates a new mock instance.
func NewMockTransactionRepository(ctrl *gomock.Controller) *MockTransactionRepository {
	mock := &MockTransactionRepository{ctrl: ctrl}
	mock.recorder = &MockTransactionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionRepository) EXPECT() *MockTransactionRepositoryMockRecorder {
	return m.recorder
}

// AddRowDelete mocks base method.
func (m *MockTransactionRepository) AddRowDelete(ctx context.Context, transactionID string, rowIndex int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRowDelete", ctx, transactionID, rowIndex)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRowDelete indicates an expected call of AddRowDelete.
func (mr *MockTransactionRepositoryMockRecorder) AddRowDelete(ctx, transactionID, rowIndex interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRowDelete", reflect.TypeOf((*MockTransactionRepository)(nil).AddRowDelete), ctx, transactionID, rowIndex)
}

// AddRowEdit mocks base method.
func (m *MockTransactionRepository) AddRowEdit(ctx context.Context, transactionID string, edit domain.RowEdit) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRowEdit", ctx, transactionID, edit)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRowEdit indicates an expected call of AddRowEdit.
func (mr *MockTransactionRepositoryMockRecorder) AddRowEdit(ctx, transactionID, edit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRowEdit", reflect.TypeOf((*MockTransactionRepository)(nil).AddRowEdit), ctx, transactionID, edit)
}

// AddRowInsert mocks base method.
func (m *MockTransactionRepository) AddRowInsert(ctx context.Context, transactionID string, insert domain.RowInsert) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRowInsert", ctx, transactionID, insert)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRowInsert indicates an expected call of AddRowInsert.
func (mr *MockTransactionRepositoryMockRecorder) AddRowInsert(ctx, transactionID, insert interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRowInsert", reflect.TypeOf((*MockTransactionRepository)(nil).AddRowInsert), ctx, transactionID, insert)
}

// ClearRowDeletes mocks base method.
func (m *MockTransactionRepository) ClearRowDeletes(ctx context.Context, transactionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearRowDeletes", ctx, transactionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearRowDeletes indicates an expected call of ClearRowDeletes.
func (mr *MockTransactionRepositoryMockRecorder) ClearRowDeletes(ctx, transactionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearRowDeletes", reflect.TypeOf((*MockTransactionRepository)(nil).ClearRowDeletes), ctx, transactionID)
}

// ClearRowEdits mocks base method.
func (m *MockTransactionRepository) ClearRowEdits(ctx context.Context, transactionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearRowEdits", ctx, transactionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearRowEdits indicates an expected call of ClearRowEdits.
func (mr *MockTransactionRepositoryMockRecorder) ClearRowEdits(ctx, transactionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearRowEdits", reflect.TypeOf((*MockTransactionRepository)(nil).ClearRowEdits), ctx, transactionID)
}

// ClearRowInserts mocks base method.
func (m *MockTransactionRepository) ClearRowInserts(ctx context.Context, transactionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearRowInserts", ctx, transactionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearRowInserts indicates an expected call of ClearRowInserts.
func (mr *MockTransactionRepositoryMockRecorder) ClearRowInserts(ctx, transactionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearRowInserts", reflect.TypeOf((*MockTransactionRepository)(nil).ClearRowInserts), ctx, transactionID)
}

// CreateTransaction mocks base method.
func (m *MockTransactionRepository) CreateTransaction(ctx context.Context, transaction *domain.TransactionState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransaction", ctx, transaction)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTransaction indicates an expected call of CreateTransaction.
func (mr *MockTransactionRepositoryMockRecorder) CreateTransaction(ctx, transaction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransaction", reflect.TypeOf((*MockTransactionRepository)(nil).CreateTransaction), ctx, transaction)
}

// DeleteTransaction mocks base method.
func (m *MockTransactionRepository) DeleteTransaction(ctx context.Context, transactionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTransaction", ctx, transactionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTransaction indicates an expected call of DeleteTransaction.
func (mr *MockTransactionRepositoryMockRecorder) DeleteTransaction(ctx, transactionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTransaction", reflect.TypeOf((*MockTransactionRepository)(nil).DeleteTransaction), ctx, transactionID)
}

// GetRowDeletes mocks base method.
func (m *MockTransactionRepository) GetRowDeletes(ctx context.Context, transactionID string) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRowDeletes", ctx, transactionID)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRowDeletes indicates an expected call of GetRowDeletes.
func (mr *MockTransactionRepositoryMockRecorder) GetRowDeletes(ctx, transactionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRowDeletes", reflect.TypeOf((*MockTransactionRepository)(nil).GetRowDeletes), ctx, transactionID)
}

// GetRowEdits mocks base method.
func (m *MockTransactionRepository) GetRowEdits(ctx context.Context, transactionID string) (map[int]domain.RowEdit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRowEdits", ctx, transactionID)
	ret0, _ := ret[0].(map[int]domain.RowEdit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRowEdits indicates an expected call of GetRowEdits.
func (mr *MockTransactionRepositoryMockRecorder) GetRowEdits(ctx, transactionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRowEdits", reflect.TypeOf((*MockTransactionRepository)(nil).GetRowEdits), ctx, transactionID)
}

// GetRowInserts mocks base method.
func (m *MockTransactionRepository) GetRowInserts(ctx context.Context, transactionID string) ([]domain.RowInsert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRowInserts", ctx, transactionID)
	ret0, _ := ret[0].([]domain.RowInsert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRowInserts indicates an expected call of GetRowInserts.
func (mr *MockTransactionRepositoryMockRecorder) GetRowInserts(ctx, transactionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRowInserts", reflect.TypeOf((*MockTransactionRepository)(nil).GetRowInserts), ctx, transactionID)
}

// GetTransaction mocks base method.
func (m *MockTransactionRepository) GetTransaction(ctx context.Context, transactionID string) (*domain.TransactionState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransaction", ctx, transactionID)
	ret0, _ := ret[0].(*domain.TransactionState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransaction indicates an expected call of GetTransaction.
func (mr *MockTransactionRepositoryMockRecorder) GetTransaction(ctx, transactionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransaction", reflect.TypeOf((*MockTransactionRepository)(nil).GetTransaction), ctx, transactionID)
}

// GetUserTransaction mocks base method.
func (m *MockTransactionRepository) GetUserTransaction(ctx context.Context, username string) (*domain.TransactionState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserTransaction", ctx, username)
	ret0, _ := ret[0].(*domain.TransactionState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserTransaction indicates an expected call of GetUserTransaction.
func (mr *MockTransactionRepositoryMockRecorder) GetUserTransaction(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserTransaction", reflect.TypeOf((*MockTransactionRepository)(nil).GetUserTransaction), ctx, username)
}

// InvalidateExpiredTransactions mocks base method.
func (m *MockTransactionRepository) InvalidateExpiredTransactions(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateExpiredTransactions", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateExpiredTransactions indicates an expected call of InvalidateExpiredTransactions.
func (mr *MockTransactionRepositoryMockRecorder) InvalidateExpiredTransactions(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateExpiredTransactions", reflect.TypeOf((*MockTransactionRepository)(nil).InvalidateExpiredTransactions), ctx)
}

// TransactionExists mocks base method.
func (m *MockTransactionRepository) TransactionExists(ctx context.Context, transactionID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransactionExists", ctx, transactionID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransactionExists indicates an expected call of TransactionExists.
func (mr *MockTransactionRepositoryMockRecorder) TransactionExists(ctx, transactionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransactionExists", reflect.TypeOf((*MockTransactionRepository)(nil).TransactionExists), ctx, transactionID)
}

// UpdateTransaction mocks base method.
func (m *MockTransactionRepository) UpdateTransaction(ctx context.Context, transaction *domain.TransactionState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTransaction", ctx, transaction)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTransaction indicates an expected call of UpdateTransaction.
func (mr *MockTransactionRepositoryMockRecorder) UpdateTransaction(ctx, transaction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTransaction", reflect.TypeOf((*MockTransactionRepository)(nil).UpdateTransaction), ctx, transaction)
}
