// Code generated by MockGen. DO NOT EDIT.
// Source: /home/kamil5b/REDIKRU/lumen-pg/internal/interfaces/repository/database_repository.go

// Package mockrepository is a generated GoMock package.
package mockrepository

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/kamil5b/lumen-pg/internal/domain"
)

// MockDatabaseRepository is a mock of DatabaseRepository interface.
type MockDatabaseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseRepositoryMockRecorder
}

// MockDatabaseRepositoryMockRecorder is the mock recorder for MockDatabaseRepository.
type MockDatabaseRepositoryMockRecorder struct {
	mock *MockDatabaseRepository
}

// NewMockDatabaseRepository creates a new mock instance.
func NewMockDatabaseRepository(ctrl *gomock.Controller) *MockDatabaseRepository {
	mock := &MockDatabaseRepository{ctrl: ctrl}
	mock.recorder = &MockDatabaseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabaseRepository) EXPECT() *MockDatabaseRepositoryMockRecorder {
	return m.recorder
}

// BeginTransaction mocks base method.
func (m *MockDatabaseRepository) BeginTransaction(ctx context.Context) (*sql.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTransaction", ctx)
	ret0, _ := ret[0].(*sql.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTransaction indicates an expected call of BeginTransaction.
func (mr *MockDatabaseRepositoryMockRecorder) BeginTransaction(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTransaction", reflect.TypeOf((*MockDatabaseRepository)(nil).BeginTransaction), ctx)
}

// CommitTransaction mocks base method.
func (m *MockDatabaseRepository) CommitTransaction(ctx context.Context, tx *sql.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitTransaction", ctx, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitTransaction indicates an expected call of CommitTransaction.
func (mr *MockDatabaseRepositoryMockRecorder) CommitTransaction(ctx, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitTransaction", reflect.TypeOf((*MockDatabaseRepository)(nil).CommitTransaction), ctx, tx)
}

// Connect mocks base method.
func (m *MockDatabaseRepository) Connect(ctx context.Context, connString string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", ctx, connString)
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockDatabaseRepositoryMockRecorder) Connect(ctx, connString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockDatabaseRepository)(nil).Connect), ctx, connString)
}

// DeleteRow mocks base method.
func (m *MockDatabaseRepository) DeleteRow(ctx context.Context, database, schema, table string, pkValues map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRow", ctx, database, schema, table, pkValues)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRow indicates an expected call of DeleteRow.
func (mr *MockDatabaseRepositoryMockRecorder) DeleteRow(ctx, database, schema, table, pkValues interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRow", reflect.TypeOf((*MockDatabaseRepository)(nil).DeleteRow), ctx, database, schema, table, pkValues)
}

// Disconnect mocks base method.
func (m *MockDatabaseRepository) Disconnect(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disconnect", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Disconnect indicates an expected call of Disconnect.
func (mr *MockDatabaseRepositoryMockRecorder) Disconnect(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disconnect", reflect.TypeOf((*MockDatabaseRepository)(nil).Disconnect), ctx)
}

// ExecuteMultipleQueries mocks base method.
func (m *MockDatabaseRepository) ExecuteMultipleQueries(ctx context.Context, queries string) ([]domain.QueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteMultipleQueries", ctx, queries)
	ret0, _ := ret[0].([]domain.QueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteMultipleQueries indicates an expected call of ExecuteMultipleQueries.
func (mr *MockDatabaseRepositoryMockRecorder) ExecuteMultipleQueries(ctx, queries interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteMultipleQueries", reflect.TypeOf((*MockDatabaseRepository)(nil).ExecuteMultipleQueries), ctx, queries)
}

// ExecuteQuery mocks base method.
func (m *MockDatabaseRepository) ExecuteQuery(ctx context.Context, query string, args ...interface{}) (*domain.QueryResult, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExecuteQuery", varargs...)
	ret0, _ := ret[0].(*domain.QueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteQuery indicates an expected call of ExecuteQuery.
func (mr *MockDatabaseRepositoryMockRecorder) ExecuteQuery(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteQuery", reflect.TypeOf((*MockDatabaseRepository)(nil).ExecuteQuery), varargs...)
}

// ExecuteQueryWithPagination mocks base method.
func (m *MockDatabaseRepository) ExecuteQueryWithPagination(ctx context.Context, params domain.QueryParams) (*domain.QueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteQueryWithPagination", ctx, params)
	ret0, _ := ret[0].(*domain.QueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteQueryWithPagination indicates an expected call of ExecuteQueryWithPagination.
func (mr *MockDatabaseRepositoryMockRecorder) ExecuteQueryWithPagination(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteQueryWithPagination", reflect.TypeOf((*MockDatabaseRepository)(nil).ExecuteQueryWithPagination), ctx, params)
}

// GetConnection mocks base method.
func (m *MockDatabaseRepository) GetConnection() *sql.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnection")
	ret0, _ := ret[0].(*sql.DB)
	return ret0
}

// GetConnection indicates an expected call of GetConnection.
func (mr *MockDatabaseRepositoryMockRecorder) GetConnection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnection", reflect.TypeOf((*MockDatabaseRepository)(nil).GetConnection))
}

// GetDatabaseMetadata mocks base method.
func (m *MockDatabaseRepository) GetDatabaseMetadata(ctx context.Context, database string) (*domain.DatabaseMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatabaseMetadata", ctx, database)
	ret0, _ := ret[0].(*domain.DatabaseMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDatabaseMetadata indicates an expected call of GetDatabaseMetadata.
func (mr *MockDatabaseRepositoryMockRecorder) GetDatabaseMetadata(ctx, database interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabaseMetadata", reflect.TypeOf((*MockDatabaseRepository)(nil).GetDatabaseMetadata), ctx, database)
}

// GetDatabases mocks base method.
func (m *MockDatabaseRepository) GetDatabases(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatabases", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDatabases indicates an expected call of GetDatabases.
func (mr *MockDatabaseRepositoryMockRecorder) GetDatabases(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabases", reflect.TypeOf((*MockDatabaseRepository)(nil).GetDatabases), ctx)
}

// GetRowCount mocks base method.
func (m *MockDatabaseRepository) GetRowCount(ctx context.Context, database, schema, table, whereClause string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRowCount", ctx, database, schema, table, whereClause)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRowCount indicates an expected call of GetRowCount.
func (mr *MockDatabaseRepositoryMockRecorder) GetRowCount(ctx, database, schema, table, whereClause interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRowCount", reflect.TypeOf((*MockDatabaseRepository)(nil).GetRowCount), ctx, database, schema, table, whereClause)
}

// GetSchemas mocks base method.
func (m *MockDatabaseRepository) GetSchemas(ctx context.Context, database string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSchemas", ctx, database)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSchemas indicates an expected call of GetSchemas.
func (mr *MockDatabaseRepositoryMockRecorder) GetSchemas(ctx, database interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSchemas", reflect.TypeOf((*MockDatabaseRepository)(nil).GetSchemas), ctx, database)
}

// GetTableData mocks base method.
func (m *MockDatabaseRepository) GetTableData(ctx context.Context, params domain.TableDataParams) (*domain.QueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTableData", ctx, params)
	ret0, _ := ret[0].(*domain.QueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTableData indicates an expected call of GetTableData.
func (mr *MockDatabaseRepositoryMockRecorder) GetTableData(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTableData", reflect.TypeOf((*MockDatabaseRepository)(nil).GetTableData), ctx, params)
}

// GetTableMetadata mocks base method.
func (m *MockDatabaseRepository) GetTableMetadata(ctx context.Context, database, schema, table string) (*domain.TableMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTableMetadata", ctx, database, schema, table)
	ret0, _ := ret[0].(*domain.TableMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTableMetadata indicates an expected call of GetTableMetadata.
func (mr *MockDatabaseRepositoryMockRecorder) GetTableMetadata(ctx, database, schema, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTableMetadata", reflect.TypeOf((*MockDatabaseRepository)(nil).GetTableMetadata), ctx, database, schema, table)
}

// GetTables mocks base method.
func (m *MockDatabaseRepository) GetTables(ctx context.Context, database, schema string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTables", ctx, database, schema)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTables indicates an expected call of GetTables.
func (mr *MockDatabaseRepositoryMockRecorder) GetTables(ctx, database, schema interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTables", reflect.TypeOf((*MockDatabaseRepository)(nil).GetTables), ctx, database, schema)
}

// InsertRow mocks base method.
func (m *MockDatabaseRepository) InsertRow(ctx context.Context, database, schema, table string, values map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertRow", ctx, database, schema, table, values)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertRow indicates an expected call of InsertRow.
func (mr *MockDatabaseRepositoryMockRecorder) InsertRow(ctx, database, schema, table, values interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertRow", reflect.TypeOf((*MockDatabaseRepository)(nil).InsertRow), ctx, database, schema, table, values)
}

// RollbackTransaction mocks base method.
func (m *MockDatabaseRepository) RollbackTransaction(ctx context.Context, tx *sql.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackTransaction", ctx, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RollbackTransaction indicates an expected call of RollbackTransaction.
func (mr *MockDatabaseRepositoryMockRecorder) RollbackTransaction(ctx, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackTransaction", reflect.TypeOf((*MockDatabaseRepository)(nil).RollbackTransaction), ctx, tx)
}

// TestConnection mocks base method.
func (m *MockDatabaseRepository) TestConnection(ctx context.Context, connString string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TestConnection", ctx, connString)
	ret0, _ := ret[0].(error)
	return ret0
}

// TestConnection indicates an expected call of TestConnection.
func (mr *MockDatabaseRepositoryMockRecorder) TestConnection(ctx, connString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestConnection", reflect.TypeOf((*MockDatabaseRepository)(nil).TestConnection), ctx, connString)
}

// UpdateRow mocks base method.
func (m *MockDatabaseRepository) UpdateRow(ctx context.Context, database, schema, table string, pkValues, values map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRow", ctx, database, schema, table, pkValues, values)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRow indicates an expected call of UpdateRow.
func (mr *MockDatabaseRepositoryMockRecorder) UpdateRow(ctx, database, schema, table, pkValues, values interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRow", reflect.TypeOf((*MockDatabaseRepository)(nil).UpdateRow), ctx, database, schema, table, pkValues, values)
}
