// Code generated by MockGen. DO NOT EDIT.
// Source: /home/kamil5b/REDIKRU/lumen-pg/internal/interfaces/handler/login_handler.go

// Package mockhandler is a generated GoMock package.
package mockhandler

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLoginHandler is a mock of LoginHandler interface.
type MockLoginHandler struct {
	ctrl     *gomock.Controller
	recorder *MockLoginHandlerMockRecorder
}

// MockLoginHandlerMockRecorder is the mock recorder for MockLoginHandler.
type MockLoginHandlerMockRecorder struct {
	mock *MockLoginHandler
}

// NewMockLoginHandler creates a new mock instance.
func NewMockLoginHandler(ctrl *gomock.Controller) *MockLoginHandler {
	mock := &MockLoginHandler{ctrl: ctrl}
	mock.recorder = &MockLoginHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoginHandler) EXPECT() *MockLoginHandlerMockRecorder {
	return m.recorder
}

// HandleLogin mocks base method.
func (m *MockLoginHandler) HandleLogin(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleLogin", w, r)
}

// HandleLogin indicates an expected call of HandleLogin.
func (mr *MockLoginHandlerMockRecorder) HandleLogin(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleLogin", reflect.TypeOf((*MockLoginHandler)(nil).HandleLogin), w, r)
}

// HandleLoginPage mocks base method.
func (m *MockLoginHandler) HandleLoginPage(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleLoginPage", w, r)
}

// HandleLoginPage indicates an expected call of HandleLoginPage.
func (mr *MockLoginHandlerMockRecorder) HandleLoginPage(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleLoginPage", reflect.TypeOf((*MockLoginHandler)(nil).HandleLoginPage), w, r)
}

// HandleLogout mocks base method.
func (m *MockLoginHandler) HandleLogout(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleLogout", w, r)
}

// HandleLogout indicates an expected call of HandleLogout.
func (mr *MockLoginHandlerMockRecorder) HandleLogout(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleLogout", reflect.TypeOf((*MockLoginHandler)(nil).HandleLogout), w, r)
}

// ServeHTTP mocks base method.
func (m *MockLoginHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ServeHTTP", w, r)
}

// ServeHTTP indicates an expected call of ServeHTTP.
func (mr *MockLoginHandlerMockRecorder) ServeHTTP(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServeHTTP", reflect.TypeOf((*MockLoginHandler)(nil).ServeHTTP), w, r)
}
