// Code generated by MockGen. DO NOT EDIT.
// Source: /home/kamil5b/REDIKRU/lumen-pg/internal/interfaces/handler/main_view_handler.go

// Package mockhandler is a generated GoMock package.
package mockhandler

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMainViewHandler is a mock of MainViewHandler interface.
type MockMainViewHandler struct {
	ctrl     *gomock.Controller
	recorder *MockMainViewHandlerMockRecorder
}

// MockMainViewHandlerMockRecorder is the mock recorder for MockMainViewHandler.
type MockMainViewHandlerMockRecorder struct {
	mock *MockMainViewHandler
}

// NewMockMainViewHandler creates a new mock instance.
func NewMockMainViewHandler(ctrl *gomock.Controller) *MockMainViewHandler {
	mock := &MockMainViewHandler{ctrl: ctrl}
	mock.recorder = &MockMainViewHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMainViewHandler) EXPECT() *MockMainViewHandlerMockRecorder {
	return m.recorder
}

// HandleFilterTable mocks base method.
func (m *MockMainViewHandler) HandleFilterTable(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleFilterTable", w, r)
}

// HandleFilterTable indicates an expected call of HandleFilterTable.
func (mr *MockMainViewHandlerMockRecorder) HandleFilterTable(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleFilterTable", reflect.TypeOf((*MockMainViewHandler)(nil).HandleFilterTable), w, r)
}

// HandleLoadTableData mocks base method.
func (m *MockMainViewHandler) HandleLoadTableData(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleLoadTableData", w, r)
}

// HandleLoadTableData indicates an expected call of HandleLoadTableData.
func (mr *MockMainViewHandlerMockRecorder) HandleLoadTableData(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleLoadTableData", reflect.TypeOf((*MockMainViewHandler)(nil).HandleLoadTableData), w, r)
}

// HandleMainViewPage mocks base method.
func (m *MockMainViewHandler) HandleMainViewPage(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleMainViewPage", w, r)
}

// HandleMainViewPage indicates an expected call of HandleMainViewPage.
func (mr *MockMainViewHandlerMockRecorder) HandleMainViewPage(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleMainViewPage", reflect.TypeOf((*MockMainViewHandler)(nil).HandleMainViewPage), w, r)
}

// HandlePaginationNext mocks base method.
func (m *MockMainViewHandler) HandlePaginationNext(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandlePaginationNext", w, r)
}

// HandlePaginationNext indicates an expected call of HandlePaginationNext.
func (mr *MockMainViewHandlerMockRecorder) HandlePaginationNext(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandlePaginationNext", reflect.TypeOf((*MockMainViewHandler)(nil).HandlePaginationNext), w, r)
}

// HandlePaginationPrevious mocks base method.
func (m *MockMainViewHandler) HandlePaginationPrevious(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandlePaginationPrevious", w, r)
}

// HandlePaginationPrevious indicates an expected call of HandlePaginationPrevious.
func (mr *MockMainViewHandlerMockRecorder) HandlePaginationPrevious(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandlePaginationPrevious", reflect.TypeOf((*MockMainViewHandler)(nil).HandlePaginationPrevious), w, r)
}

// HandleSortTable mocks base method.
func (m *MockMainViewHandler) HandleSortTable(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleSortTable", w, r)
}

// HandleSortTable indicates an expected call of HandleSortTable.
func (mr *MockMainViewHandlerMockRecorder) HandleSortTable(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleSortTable", reflect.TypeOf((*MockMainViewHandler)(nil).HandleSortTable), w, r)
}

// HandleTableSelect mocks base method.
func (m *MockMainViewHandler) HandleTableSelect(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleTableSelect", w, r)
}

// HandleTableSelect indicates an expected call of HandleTableSelect.
func (mr *MockMainViewHandlerMockRecorder) HandleTableSelect(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleTableSelect", reflect.TypeOf((*MockMainViewHandler)(nil).HandleTableSelect), w, r)
}

// ServeHTTP mocks base method.
func (m *MockMainViewHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ServeHTTP", w, r)
}

// ServeHTTP indicates an expected call of ServeHTTP.
func (mr *MockMainViewHandlerMockRecorder) ServeHTTP(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServeHTTP", reflect.TypeOf((*MockMainViewHandler)(nil).ServeHTTP), w, r)
}
