// Code generated by MockGen. DO NOT EDIT.
// Source: /home/kamil5b/REDIKRU/lumen-pg/internal/interfaces/handler/navigation_handler.go

// Package mockhandler is a generated GoMock package.
package mockhandler

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockNavigationHandler is a mock of NavigationHandler interface.
type MockNavigationHandler struct {
	ctrl     *gomock.Controller
	recorder *MockNavigationHandlerMockRecorder
}

// MockNavigationHandlerMockRecorder is the mock recorder for MockNavigationHandler.
type MockNavigationHandlerMockRecorder struct {
	mock *MockNavigationHandler
}

// NewMockNavigationHandler creates a new mock instance.
func NewMockNavigationHandler(ctrl *gomock.Controller) *MockNavigationHandler {
	mock := &MockNavigationHandler{ctrl: ctrl}
	mock.recorder = &MockNavigationHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNavigationHandler) EXPECT() *MockNavigationHandlerMockRecorder {
	return m.recorder
}

// HandleGetChildTableReferences mocks base method.
func (m *MockNavigationHandler) HandleGetChildTableReferences(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleGetChildTableReferences", w, r)
}

// HandleGetChildTableReferences indicates an expected call of HandleGetChildTableReferences.
func (mr *MockNavigationHandlerMockRecorder) HandleGetChildTableReferences(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleGetChildTableReferences", reflect.TypeOf((*MockNavigationHandler)(nil).HandleGetChildTableReferences), w, r)
}

// HandleNavigateToChildRows mocks base method.
func (m *MockNavigationHandler) HandleNavigateToChildRows(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleNavigateToChildRows", w, r)
}

// HandleNavigateToChildRows indicates an expected call of HandleNavigateToChildRows.
func (mr *MockNavigationHandlerMockRecorder) HandleNavigateToChildRows(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleNavigateToChildRows", reflect.TypeOf((*MockNavigationHandler)(nil).HandleNavigateToChildRows), w, r)
}

// HandleNavigateToParentRow mocks base method.
func (m *MockNavigationHandler) HandleNavigateToParentRow(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleNavigateToParentRow", w, r)
}

// HandleNavigateToParentRow indicates an expected call of HandleNavigateToParentRow.
func (mr *MockNavigationHandlerMockRecorder) HandleNavigateToParentRow(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleNavigateToParentRow", reflect.TypeOf((*MockNavigationHandler)(nil).HandleNavigateToParentRow), w, r)
}

// ServeHTTP mocks base method.
func (m *MockNavigationHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ServeHTTP", w, r)
}

// ServeHTTP indicates an expected call of ServeHTTP.
func (mr *MockNavigationHandlerMockRecorder) ServeHTTP(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServeHTTP", reflect.TypeOf((*MockNavigationHandler)(nil).ServeHTTP), w, r)
}
