// Code generated by MockGen. DO NOT EDIT.
// Source: /home/kamil5b/REDIKRU/lumen-pg/internal/interfaces/handler/metadata_handler.go

// Package mockhandler is a generated GoMock package.
package mockhandler

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMetadataHandler is a mock of MetadataHandler interface.
type MockMetadataHandler struct {
	ctrl     *gomock.Controller
	recorder *MockMetadataHandlerMockRecorder
}

// MockMetadataHandlerMockRecorder is the mock recorder for MockMetadataHandler.
type MockMetadataHandlerMockRecorder struct {
	mock *MockMetadataHandler
}

// NewMockMetadataHandler creates a new mock instance.
func NewMockMetadataHandler(ctrl *gomock.Controller) *MockMetadataHandler {
	mock := &MockMetadataHandler{ctrl: ctrl}
	mock.recorder = &MockMetadataHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetadataHandler) EXPECT() *MockMetadataHandlerMockRecorder {
	return m.recorder
}

// HandleGetDatabaseMetadata mocks base method.
func (m *MockMetadataHandler) HandleGetDatabaseMetadata(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleGetDatabaseMetadata", w, r)
}

// HandleGetDatabaseMetadata indicates an expected call of HandleGetDatabaseMetadata.
func (mr *MockMetadataHandlerMockRecorder) HandleGetDatabaseMetadata(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleGetDatabaseMetadata", reflect.TypeOf((*MockMetadataHandler)(nil).HandleGetDatabaseMetadata), w, r)
}

// HandleGetSchemaMetadata mocks base method.
func (m *MockMetadataHandler) HandleGetSchemaMetadata(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleGetSchemaMetadata", w, r)
}

// HandleGetSchemaMetadata indicates an expected call of HandleGetSchemaMetadata.
func (mr *MockMetadataHandlerMockRecorder) HandleGetSchemaMetadata(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleGetSchemaMetadata", reflect.TypeOf((*MockMetadataHandler)(nil).HandleGetSchemaMetadata), w, r)
}

// HandleGetTableMetadata mocks base method.
func (m *MockMetadataHandler) HandleGetTableMetadata(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleGetTableMetadata", w, r)
}

// HandleGetTableMetadata indicates an expected call of HandleGetTableMetadata.
func (mr *MockMetadataHandlerMockRecorder) HandleGetTableMetadata(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleGetTableMetadata", reflect.TypeOf((*MockMetadataHandler)(nil).HandleGetTableMetadata), w, r)
}

// HandleRefreshMetadata mocks base method.
func (m *MockMetadataHandler) HandleRefreshMetadata(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleRefreshMetadata", w, r)
}

// HandleRefreshMetadata indicates an expected call of HandleRefreshMetadata.
func (mr *MockMetadataHandlerMockRecorder) HandleRefreshMetadata(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleRefreshMetadata", reflect.TypeOf((*MockMetadataHandler)(nil).HandleRefreshMetadata), w, r)
}

// ServeHTTP mocks base method.
func (m *MockMetadataHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ServeHTTP", w, r)
}

// ServeHTTP indicates an expected call of ServeHTTP.
func (mr *MockMetadataHandlerMockRecorder) ServeHTTP(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServeHTTP", reflect.TypeOf((*MockMetadataHandler)(nil).ServeHTTP), w, r)
}
