// Code generated by MockGen. DO NOT EDIT.
// Source: /home/kamil5b/REDIKRU/lumen-pg/internal/interfaces/handler/http_handler.go

// Package mockhandler is a generated GoMock package.
package mockhandler

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockHTTPHandler is a mock of HTTPHandler interface.
type MockHTTPHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPHandlerMockRecorder
}

// MockHTTPHandlerMockRecorder is the mock recorder for MockHTTPHandler.
type MockHTTPHandlerMockRecorder struct {
	mock *MockHTTPHandler
}

// NewMockHTTPHandler creates a new mock instance.
func NewMockHTTPHandler(ctrl *gomock.Controller) *MockHTTPHandler {
	mock := &MockHTTPHandler{ctrl: ctrl}
	mock.recorder = &MockHTTPHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPHandler) EXPECT() *MockHTTPHandlerMockRecorder {
	return m.recorder
}

// ServeHTTP mocks base method.
func (m *MockHTTPHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ServeHTTP", w, r)
}

// ServeHTTP indicates an expected call of ServeHTTP.
func (mr *MockHTTPHandlerMockRecorder) ServeHTTP(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServeHTTP", reflect.TypeOf((*MockHTTPHandler)(nil).ServeHTTP), w, r)
}

// MockHealthHandler is a mock of HealthHandler interface.
type MockHealthHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHealthHandlerMockRecorder
}

// MockHealthHandlerMockRecorder is the mock recorder for MockHealthHandler.
type MockHealthHandlerMockRecorder struct {
	mock *MockHealthHandler
}

// NewMockHealthHandler creates a new mock instance.
func NewMockHealthHandler(ctrl *gomock.Controller) *MockHealthHandler {
	mock := &MockHealthHandler{ctrl: ctrl}
	mock.recorder = &MockHealthHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHealthHandler) EXPECT() *MockHealthHandlerMockRecorder {
	return m.recorder
}

// HandleHealthCheck mocks base method.
func (m *MockHealthHandler) HandleHealthCheck(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleHealthCheck", w, r)
}

// HandleHealthCheck indicates an expected call of HandleHealthCheck.
func (mr *MockHealthHandlerMockRecorder) HandleHealthCheck(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleHealthCheck", reflect.TypeOf((*MockHealthHandler)(nil).HandleHealthCheck), w, r)
}

// HandleIsInitialized mocks base method.
func (m *MockHealthHandler) HandleIsInitialized(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleIsInitialized", w, r)
}

// HandleIsInitialized indicates an expected call of HandleIsInitialized.
func (mr *MockHealthHandlerMockRecorder) HandleIsInitialized(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleIsInitialized", reflect.TypeOf((*MockHealthHandler)(nil).HandleIsInitialized), w, r)
}

// ServeHTTP mocks base method.
func (m *MockHealthHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ServeHTTP", w, r)
}

// ServeHTTP indicates an expected call of ServeHTTP.
func (mr *MockHealthHandlerMockRecorder) ServeHTTP(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServeHTTP", reflect.TypeOf((*MockHealthHandler)(nil).ServeHTTP), w, r)
}
