// Code generated by MockGen. DO NOT EDIT.
// Source: /home/kamil5b/REDIKRU/lumen-pg/internal/interfaces/handler/data_explorer_handler.go

// Package mockhandler is a generated GoMock package.
package mockhandler

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDataExplorerHandler is a mock of DataExplorerHandler interface.
type MockDataExplorerHandler struct {
	ctrl     *gomock.Controller
	recorder *MockDataExplorerHandlerMockRecorder
}

// MockDataExplorerHandlerMockRecorder is the mock recorder for MockDataExplorerHandler.
type MockDataExplorerHandlerMockRecorder struct {
	mock *MockDataExplorerHandler
}

// NewMockDataExplorerHandler creates a new mock instance.
func NewMockDataExplorerHandler(ctrl *gomock.Controller) *MockDataExplorerHandler {
	mock := &MockDataExplorerHandler{ctrl: ctrl}
	mock.recorder = &MockDataExplorerHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataExplorerHandler) EXPECT() *MockDataExplorerHandlerMockRecorder {
	return m.recorder
}

// HandleLoadDataExplorer mocks base method.
func (m *MockDataExplorerHandler) HandleLoadDataExplorer(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleLoadDataExplorer", w, r)
}

// HandleLoadDataExplorer indicates an expected call of HandleLoadDataExplorer.
func (mr *MockDataExplorerHandlerMockRecorder) HandleLoadDataExplorer(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleLoadDataExplorer", reflect.TypeOf((*MockDataExplorerHandler)(nil).HandleLoadDataExplorer), w, r)
}

// HandleSelectDatabase mocks base method.
func (m *MockDataExplorerHandler) HandleSelectDatabase(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleSelectDatabase", w, r)
}

// HandleSelectDatabase indicates an expected call of HandleSelectDatabase.
func (mr *MockDataExplorerHandlerMockRecorder) HandleSelectDatabase(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleSelectDatabase", reflect.TypeOf((*MockDataExplorerHandler)(nil).HandleSelectDatabase), w, r)
}

// HandleSelectSchema mocks base method.
func (m *MockDataExplorerHandler) HandleSelectSchema(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleSelectSchema", w, r)
}

// HandleSelectSchema indicates an expected call of HandleSelectSchema.
func (mr *MockDataExplorerHandlerMockRecorder) HandleSelectSchema(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleSelectSchema", reflect.TypeOf((*MockDataExplorerHandler)(nil).HandleSelectSchema), w, r)
}

// HandleSelectTable mocks base method.
func (m *MockDataExplorerHandler) HandleSelectTable(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleSelectTable", w, r)
}

// HandleSelectTable indicates an expected call of HandleSelectTable.
func (mr *MockDataExplorerHandlerMockRecorder) HandleSelectTable(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleSelectTable", reflect.TypeOf((*MockDataExplorerHandler)(nil).HandleSelectTable), w, r)
}

// ServeHTTP mocks base method.
func (m *MockDataExplorerHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ServeHTTP", w, r)
}

// ServeHTTP indicates an expected call of ServeHTTP.
func (mr *MockDataExplorerHandlerMockRecorder) ServeHTTP(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServeHTTP", reflect.TypeOf((*MockDataExplorerHandler)(nil).ServeHTTP), w, r)
}
