// Code generated by MockGen. DO NOT EDIT.
// Source: /home/kamil5b/REDIKRU/lumen-pg/internal/interfaces/handler/query_editor_handler.go

// Package mockhandler is a generated GoMock package.
package mockhandler

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockQueryEditorHandler is a mock of QueryEditorHandler interface.
type MockQueryEditorHandler struct {
	ctrl     *gomock.Controller
	recorder *MockQueryEditorHandlerMockRecorder
}

// MockQueryEditorHandlerMockRecorder is the mock recorder for MockQueryEditorHandler.
type MockQueryEditorHandlerMockRecorder struct {
	mock *MockQueryEditorHandler
}

// NewMockQueryEditorHandler creates a new mock instance.
func NewMockQueryEditorHandler(ctrl *gomock.Controller) *MockQueryEditorHandler {
	mock := &MockQueryEditorHandler{ctrl: ctrl}
	mock.recorder = &MockQueryEditorHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryEditorHandler) EXPECT() *MockQueryEditorHandlerMockRecorder {
	return m.recorder
}

// HandleExecuteMultipleQueries mocks base method.
func (m *MockQueryEditorHandler) HandleExecuteMultipleQueries(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleExecuteMultipleQueries", w, r)
}

// HandleExecuteMultipleQueries indicates an expected call of HandleExecuteMultipleQueries.
func (mr *MockQueryEditorHandlerMockRecorder) HandleExecuteMultipleQueries(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleExecuteMultipleQueries", reflect.TypeOf((*MockQueryEditorHandler)(nil).HandleExecuteMultipleQueries), w, r)
}

// HandleExecuteQuery mocks base method.
func (m *MockQueryEditorHandler) HandleExecuteQuery(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleExecuteQuery", w, r)
}

// HandleExecuteQuery indicates an expected call of HandleExecuteQuery.
func (mr *MockQueryEditorHandlerMockRecorder) HandleExecuteQuery(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleExecuteQuery", reflect.TypeOf((*MockQueryEditorHandler)(nil).HandleExecuteQuery), w, r)
}

// HandleQueryEditorPage mocks base method.
func (m *MockQueryEditorHandler) HandleQueryEditorPage(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleQueryEditorPage", w, r)
}

// HandleQueryEditorPage indicates an expected call of HandleQueryEditorPage.
func (mr *MockQueryEditorHandlerMockRecorder) HandleQueryEditorPage(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleQueryEditorPage", reflect.TypeOf((*MockQueryEditorHandler)(nil).HandleQueryEditorPage), w, r)
}

// ServeHTTP mocks base method.
func (m *MockQueryEditorHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ServeHTTP", w, r)
}

// ServeHTTP indicates an expected call of ServeHTTP.
func (mr *MockQueryEditorHandlerMockRecorder) ServeHTTP(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServeHTTP", reflect.TypeOf((*MockQueryEditorHandler)(nil).ServeHTTP), w, r)
}
