// Code generated by MockGen. DO NOT EDIT.
// Source: /home/kamil5b/REDIKRU/lumen-pg/internal/interfaces/handler/transaction_handler.go

// Package mockhandler is a generated GoMock package.
package mockhandler

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTransactionHandler is a mock of TransactionHandler interface.
type MockTransactionHandler struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionHandlerMockRecorder
}

// MockTransactionHandlerMockRecorder is the mock recorder for MockTransactionHandler.
type MockTransactionHandlerMockRecorder struct {
	mock *MockTransactionHandler
}

// NewMockTransactionHandler creates a new mock instance.
func NewMockTransactionHandler(ctrl *gomock.Controller) *MockTransactionHandler {
	mock := &MockTransactionHandler{ctrl: ctrl}
	mock.recorder = &MockTransactionHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionHandler) EXPECT() *MockTransactionHandlerMockRecorder {
	return m.recorder
}

// HandleCommitTransaction mocks base method.
func (m *MockTransactionHandler) HandleCommitTransaction(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleCommitTransaction", w, r)
}

// HandleCommitTransaction indicates an expected call of HandleCommitTransaction.
func (mr *MockTransactionHandlerMockRecorder) HandleCommitTransaction(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleCommitTransaction", reflect.TypeOf((*MockTransactionHandler)(nil).HandleCommitTransaction), w, r)
}

// HandleDeleteRow mocks base method.
func (m *MockTransactionHandler) HandleDeleteRow(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleDeleteRow", w, r)
}

// HandleDeleteRow indicates an expected call of HandleDeleteRow.
func (mr *MockTransactionHandlerMockRecorder) HandleDeleteRow(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleDeleteRow", reflect.TypeOf((*MockTransactionHandler)(nil).HandleDeleteRow), w, r)
}

// HandleEditCell mocks base method.
func (m *MockTransactionHandler) HandleEditCell(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleEditCell", w, r)
}

// HandleEditCell indicates an expected call of HandleEditCell.
func (mr *MockTransactionHandlerMockRecorder) HandleEditCell(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleEditCell", reflect.TypeOf((*MockTransactionHandler)(nil).HandleEditCell), w, r)
}

// HandleGetTransactionStatus mocks base method.
func (m *MockTransactionHandler) HandleGetTransactionStatus(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleGetTransactionStatus", w, r)
}

// HandleGetTransactionStatus indicates an expected call of HandleGetTransactionStatus.
func (mr *MockTransactionHandlerMockRecorder) HandleGetTransactionStatus(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleGetTransactionStatus", reflect.TypeOf((*MockTransactionHandler)(nil).HandleGetTransactionStatus), w, r)
}

// HandleInsertRow mocks base method.
func (m *MockTransactionHandler) HandleInsertRow(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleInsertRow", w, r)
}

// HandleInsertRow indicates an expected call of HandleInsertRow.
func (mr *MockTransactionHandlerMockRecorder) HandleInsertRow(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleInsertRow", reflect.TypeOf((*MockTransactionHandler)(nil).HandleInsertRow), w, r)
}

// HandleRollbackTransaction mocks base method.
func (m *MockTransactionHandler) HandleRollbackTransaction(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleRollbackTransaction", w, r)
}

// HandleRollbackTransaction indicates an expected call of HandleRollbackTransaction.
func (mr *MockTransactionHandlerMockRecorder) HandleRollbackTransaction(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleRollbackTransaction", reflect.TypeOf((*MockTransactionHandler)(nil).HandleRollbackTransaction), w, r)
}

// HandleStartTransaction mocks base method.
func (m *MockTransactionHandler) HandleStartTransaction(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleStartTransaction", w, r)
}

// HandleStartTransaction indicates an expected call of HandleStartTransaction.
func (mr *MockTransactionHandlerMockRecorder) HandleStartTransaction(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleStartTransaction", reflect.TypeOf((*MockTransactionHandler)(nil).HandleStartTransaction), w, r)
}

// ServeHTTP mocks base method.
func (m *MockTransactionHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ServeHTTP", w, r)
}

// ServeHTTP indicates an expected call of ServeHTTP.
func (mr *MockTransactionHandlerMockRecorder) ServeHTTP(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServeHTTP", reflect.TypeOf((*MockTransactionHandler)(nil).ServeHTTP), w, r)
}
