// Code generated by MockGen. DO NOT EDIT.
// Source: /home/kamil5b/REDIKRU/lumen-pg/internal/interfaces/handler/erd_viewer_handler.go

// Package mockhandler is a generated GoMock package.
package mockhandler

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockERDViewerHandler is a mock of ERDViewerHandler interface.
type MockERDViewerHandler struct {
	ctrl     *gomock.Controller
	recorder *MockERDViewerHandlerMockRecorder
}

// MockERDViewerHandlerMockRecorder is the mock recorder for MockERDViewerHandler.
type MockERDViewerHandlerMockRecorder struct {
	mock *MockERDViewerHandler
}

// NewMockERDViewerHandler creates a new mock instance.
func NewMockERDViewerHandler(ctrl *gomock.Controller) *MockERDViewerHandler {
	mock := &MockERDViewerHandler{ctrl: ctrl}
	mock.recorder = &MockERDViewerHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockERDViewerHandler) EXPECT() *MockERDViewerHandlerMockRecorder {
	return m.recorder
}

// HandleERDPan mocks base method.
func (m *MockERDViewerHandler) HandleERDPan(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleERDPan", w, r)
}

// HandleERDPan indicates an expected call of HandleERDPan.
func (mr *MockERDViewerHandlerMockRecorder) HandleERDPan(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleERDPan", reflect.TypeOf((*MockERDViewerHandler)(nil).HandleERDPan), w, r)
}

// HandleERDViewerPage mocks base method.
func (m *MockERDViewerHandler) HandleERDViewerPage(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleERDViewerPage", w, r)
}

// HandleERDViewerPage indicates an expected call of HandleERDViewerPage.
func (mr *MockERDViewerHandlerMockRecorder) HandleERDViewerPage(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleERDViewerPage", reflect.TypeOf((*MockERDViewerHandler)(nil).HandleERDViewerPage), w, r)
}

// HandleERDZoom mocks base method.
func (m *MockERDViewerHandler) HandleERDZoom(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleERDZoom", w, r)
}

// HandleERDZoom indicates an expected call of HandleERDZoom.
func (mr *MockERDViewerHandlerMockRecorder) HandleERDZoom(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleERDZoom", reflect.TypeOf((*MockERDViewerHandler)(nil).HandleERDZoom), w, r)
}

// HandleGenerateERD mocks base method.
func (m *MockERDViewerHandler) HandleGenerateERD(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleGenerateERD", w, r)
}

// HandleGenerateERD indicates an expected call of HandleGenerateERD.
func (mr *MockERDViewerHandlerMockRecorder) HandleGenerateERD(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleGenerateERD", reflect.TypeOf((*MockERDViewerHandler)(nil).HandleGenerateERD), w, r)
}

// HandleTableClickInERD mocks base method.
func (m *MockERDViewerHandler) HandleTableClickInERD(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleTableClickInERD", w, r)
}

// HandleTableClickInERD indicates an expected call of HandleTableClickInERD.
func (mr *MockERDViewerHandlerMockRecorder) HandleTableClickInERD(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleTableClickInERD", reflect.TypeOf((*MockERDViewerHandler)(nil).HandleTableClickInERD), w, r)
}

// ServeHTTP mocks base method.
func (m *MockERDViewerHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ServeHTTP", w, r)
}

// ServeHTTP indicates an expected call of ServeHTTP.
func (mr *MockERDViewerHandlerMockRecorder) ServeHTTP(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServeHTTP", reflect.TypeOf((*MockERDViewerHandler)(nil).ServeHTTP), w, r)
}
