// Code generated by MockGen. DO NOT EDIT.
// Source: /home/kamil5b/REDIKRU/lumen-pg/internal/interfaces/middleware/response_middleware.go

// Package mockmiddleware is a generated GoMock package.
package mockmiddleware

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockResponseMiddleware is a mock of ResponseMiddleware interface.
type MockResponseMiddleware struct {
	ctrl     *gomock.Controller
	recorder *MockResponseMiddlewareMockRecorder
}

// MockResponseMiddlewareMockRecorder is the mock recorder for MockResponseMiddleware.
type MockResponseMiddlewareMockRecorder struct {
	mock *MockResponseMiddleware
}

// NewMockResponseMiddleware creates a new mock instance.
func NewMockResponseMiddleware(ctrl *gomock.Controller) *MockResponseMiddleware {
	mock := &MockResponseMiddleware{ctrl: ctrl}
	mock.recorder = &MockResponseMiddlewareMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResponseMiddleware) EXPECT() *MockResponseMiddlewareMockRecorder {
	return m.recorder
}

// CompressResponse mocks base method.
func (m *MockResponseMiddleware) CompressResponse(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompressResponse", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// CompressResponse indicates an expected call of CompressResponse.
func (mr *MockResponseMiddlewareMockRecorder) CompressResponse(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompressResponse", reflect.TypeOf((*MockResponseMiddleware)(nil).CompressResponse), next)
}

// ContentNegotiation mocks base method.
func (m *MockResponseMiddleware) ContentNegotiation(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContentNegotiation", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// ContentNegotiation indicates an expected call of ContentNegotiation.
func (mr *MockResponseMiddlewareMockRecorder) ContentNegotiation(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContentNegotiation", reflect.TypeOf((*MockResponseMiddleware)(nil).ContentNegotiation), next)
}

// SetDefaultHeaders mocks base method.
func (m *MockResponseMiddleware) SetDefaultHeaders(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDefaultHeaders", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// SetDefaultHeaders indicates an expected call of SetDefaultHeaders.
func (mr *MockResponseMiddlewareMockRecorder) SetDefaultHeaders(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDefaultHeaders", reflect.TypeOf((*MockResponseMiddleware)(nil).SetDefaultHeaders), next)
}
