// Code generated by MockGen. DO NOT EDIT.
// Source: /home/kamil5b/REDIKRU/lumen-pg/internal/interfaces/middleware/security_middleware.go

// Package mockmiddleware is a generated GoMock package.
package mockmiddleware

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSecurityMiddleware is a mock of SecurityMiddleware interface.
type MockSecurityMiddleware struct {
	ctrl     *gomock.Controller
	recorder *MockSecurityMiddlewareMockRecorder
}

// MockSecurityMiddlewareMockRecorder is the mock recorder for MockSecurityMiddleware.
type MockSecurityMiddlewareMockRecorder struct {
	mock *MockSecurityMiddleware
}

// NewMockSecurityMiddleware creates a new mock instance.
func NewMockSecurityMiddleware(ctrl *gomock.Controller) *MockSecurityMiddleware {
	mock := &MockSecurityMiddleware{ctrl: ctrl}
	mock.recorder = &MockSecurityMiddlewareMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecurityMiddleware) EXPECT() *MockSecurityMiddlewareMockRecorder {
	return m.recorder
}

// EnforceSameSiteCookie mocks base method.
func (m *MockSecurityMiddleware) EnforceSameSiteCookie(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnforceSameSiteCookie", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// EnforceSameSiteCookie indicates an expected call of EnforceSameSiteCookie.
func (mr *MockSecurityMiddlewareMockRecorder) EnforceSameSiteCookie(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnforceSameSiteCookie", reflect.TypeOf((*MockSecurityMiddleware)(nil).EnforceSameSiteCookie), next)
}

// PreventCSRF mocks base method.
func (m *MockSecurityMiddleware) PreventCSRF(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreventCSRF", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// PreventCSRF indicates an expected call of PreventCSRF.
func (mr *MockSecurityMiddlewareMockRecorder) PreventCSRF(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreventCSRF", reflect.TypeOf((*MockSecurityMiddleware)(nil).PreventCSRF), next)
}

// RateLimiter mocks base method.
func (m *MockSecurityMiddleware) RateLimiter(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RateLimiter", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// RateLimiter indicates an expected call of RateLimiter.
func (mr *MockSecurityMiddlewareMockRecorder) RateLimiter(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RateLimiter", reflect.TypeOf((*MockSecurityMiddleware)(nil).RateLimiter), next)
}

// RequireHTTPSForCookies mocks base method.
func (m *MockSecurityMiddleware) RequireHTTPSForCookies(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequireHTTPSForCookies", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// RequireHTTPSForCookies indicates an expected call of RequireHTTPSForCookies.
func (mr *MockSecurityMiddlewareMockRecorder) RequireHTTPSForCookies(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequireHTTPSForCookies", reflect.TypeOf((*MockSecurityMiddleware)(nil).RequireHTTPSForCookies), next)
}

// SetSecurityHeaders mocks base method.
func (m *MockSecurityMiddleware) SetSecurityHeaders(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSecurityHeaders", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// SetSecurityHeaders indicates an expected call of SetSecurityHeaders.
func (mr *MockSecurityMiddlewareMockRecorder) SetSecurityHeaders(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSecurityHeaders", reflect.TypeOf((*MockSecurityMiddleware)(nil).SetSecurityHeaders), next)
}

// ValidateCookieIntegrity mocks base method.
func (m *MockSecurityMiddleware) ValidateCookieIntegrity(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateCookieIntegrity", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// ValidateCookieIntegrity indicates an expected call of ValidateCookieIntegrity.
func (mr *MockSecurityMiddlewareMockRecorder) ValidateCookieIntegrity(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateCookieIntegrity", reflect.TypeOf((*MockSecurityMiddleware)(nil).ValidateCookieIntegrity), next)
}
