// Code generated by MockGen. DO NOT EDIT.
// Source: /home/kamil5b/REDIKRU/lumen-pg/internal/interfaces/middleware/authorization_middleware.go

// Package mockmiddleware is a generated GoMock package.
package mockmiddleware

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAuthorizationMiddleware is a mock of AuthorizationMiddleware interface.
type MockAuthorizationMiddleware struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorizationMiddlewareMockRecorder
}

// MockAuthorizationMiddlewareMockRecorder is the mock recorder for MockAuthorizationMiddleware.
type MockAuthorizationMiddlewareMockRecorder struct {
	mock *MockAuthorizationMiddleware
}

// NewMockAuthorizationMiddleware creates a new mock instance.
func NewMockAuthorizationMiddleware(ctrl *gomock.Controller) *MockAuthorizationMiddleware {
	mock := &MockAuthorizationMiddleware{ctrl: ctrl}
	mock.recorder = &MockAuthorizationMiddlewareMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorizationMiddleware) EXPECT() *MockAuthorizationMiddlewareMockRecorder {
	return m.recorder
}

// RequireDatabaseAccess mocks base method.
func (m *MockAuthorizationMiddleware) RequireDatabaseAccess(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequireDatabaseAccess", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// RequireDatabaseAccess indicates an expected call of RequireDatabaseAccess.
func (mr *MockAuthorizationMiddlewareMockRecorder) RequireDatabaseAccess(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequireDatabaseAccess", reflect.TypeOf((*MockAuthorizationMiddleware)(nil).RequireDatabaseAccess), next)
}

// RequireDeletePermission mocks base method.
func (m *MockAuthorizationMiddleware) RequireDeletePermission(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequireDeletePermission", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// RequireDeletePermission indicates an expected call of RequireDeletePermission.
func (mr *MockAuthorizationMiddlewareMockRecorder) RequireDeletePermission(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequireDeletePermission", reflect.TypeOf((*MockAuthorizationMiddleware)(nil).RequireDeletePermission), next)
}

// RequireInsertPermission mocks base method.
func (m *MockAuthorizationMiddleware) RequireInsertPermission(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequireInsertPermission", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// RequireInsertPermission indicates an expected call of RequireInsertPermission.
func (mr *MockAuthorizationMiddlewareMockRecorder) RequireInsertPermission(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequireInsertPermission", reflect.TypeOf((*MockAuthorizationMiddleware)(nil).RequireInsertPermission), next)
}

// RequireSelectPermission mocks base method.
func (m *MockAuthorizationMiddleware) RequireSelectPermission(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequireSelectPermission", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// RequireSelectPermission indicates an expected call of RequireSelectPermission.
func (mr *MockAuthorizationMiddlewareMockRecorder) RequireSelectPermission(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequireSelectPermission", reflect.TypeOf((*MockAuthorizationMiddleware)(nil).RequireSelectPermission), next)
}

// RequireTableAccess mocks base method.
func (m *MockAuthorizationMiddleware) RequireTableAccess(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequireTableAccess", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// RequireTableAccess indicates an expected call of RequireTableAccess.
func (mr *MockAuthorizationMiddlewareMockRecorder) RequireTableAccess(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequireTableAccess", reflect.TypeOf((*MockAuthorizationMiddleware)(nil).RequireTableAccess), next)
}

// RequireUpdatePermission mocks base method.
func (m *MockAuthorizationMiddleware) RequireUpdatePermission(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequireUpdatePermission", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// RequireUpdatePermission indicates an expected call of RequireUpdatePermission.
func (mr *MockAuthorizationMiddlewareMockRecorder) RequireUpdatePermission(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequireUpdatePermission", reflect.TypeOf((*MockAuthorizationMiddleware)(nil).RequireUpdatePermission), next)
}
