// Code generated by MockGen. DO NOT EDIT.
// Source: /home/kamil5b/REDIKRU/lumen-pg/internal/interfaces/middleware/error_handling_middleware.go

// Package mockmiddleware is a generated GoMock package.
package mockmiddleware

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockErrorHandlingMiddleware is a mock of ErrorHandlingMiddleware interface.
type MockErrorHandlingMiddleware struct {
	ctrl     *gomock.Controller
	recorder *MockErrorHandlingMiddlewareMockRecorder
}

// MockErrorHandlingMiddlewareMockRecorder is the mock recorder for MockErrorHandlingMiddleware.
type MockErrorHandlingMiddlewareMockRecorder struct {
	mock *MockErrorHandlingMiddleware
}

// NewMockErrorHandlingMiddleware creates a new mock instance.
func NewMockErrorHandlingMiddleware(ctrl *gomock.Controller) *MockErrorHandlingMiddleware {
	mock := &MockErrorHandlingMiddleware{ctrl: ctrl}
	mock.recorder = &MockErrorHandlingMiddlewareMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockErrorHandlingMiddleware) EXPECT() *MockErrorHandlingMiddlewareMockRecorder {
	return m.recorder
}

// HandleErrors mocks base method.
func (m *MockErrorHandlingMiddleware) HandleErrors(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleErrors", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// HandleErrors indicates an expected call of HandleErrors.
func (mr *MockErrorHandlingMiddlewareMockRecorder) HandleErrors(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleErrors", reflect.TypeOf((*MockErrorHandlingMiddleware)(nil).HandleErrors), next)
}

// RecoverFromPanic mocks base method.
func (m *MockErrorHandlingMiddleware) RecoverFromPanic(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecoverFromPanic", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// RecoverFromPanic indicates an expected call of RecoverFromPanic.
func (mr *MockErrorHandlingMiddlewareMockRecorder) RecoverFromPanic(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecoverFromPanic", reflect.TypeOf((*MockErrorHandlingMiddleware)(nil).RecoverFromPanic), next)
}

// ValidateHTTPMethod mocks base method.
func (m *MockErrorHandlingMiddleware) ValidateHTTPMethod(allowedMethods ...string) func(http.Handler) http.Handler {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range allowedMethods {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ValidateHTTPMethod", varargs...)
	ret0, _ := ret[0].(func(http.Handler) http.Handler)
	return ret0
}

// ValidateHTTPMethod indicates an expected call of ValidateHTTPMethod.
func (mr *MockErrorHandlingMiddlewareMockRecorder) ValidateHTTPMethod(allowedMethods ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateHTTPMethod", reflect.TypeOf((*MockErrorHandlingMiddleware)(nil).ValidateHTTPMethod), allowedMethods...)
}
