// Code generated by MockGen. DO NOT EDIT.
// Source: /home/kamil5b/REDIKRU/lumen-pg/internal/interfaces/middleware/request_id_middleware.go

// Package mockmiddleware is a generated GoMock package.
package mockmiddleware

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRequestIDMiddleware is a mock of RequestIDMiddleware interface.
type MockRequestIDMiddleware struct {
	ctrl     *gomock.Controller
	recorder *MockRequestIDMiddlewareMockRecorder
}

// MockRequestIDMiddlewareMockRecorder is the mock recorder for MockRequestIDMiddleware.
type MockRequestIDMiddlewareMockRecorder struct {
	mock *MockRequestIDMiddleware
}

// NewMockRequestIDMiddleware creates a new mock instance.
func NewMockRequestIDMiddleware(ctrl *gomock.Controller) *MockRequestIDMiddleware {
	mock := &MockRequestIDMiddleware{ctrl: ctrl}
	mock.recorder = &MockRequestIDMiddlewareMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestIDMiddleware) EXPECT() *MockRequestIDMiddlewareMockRecorder {
	return m.recorder
}

// InjectRequestID mocks base method.
func (m *MockRequestIDMiddleware) InjectRequestID(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InjectRequestID", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// InjectRequestID indicates an expected call of InjectRequestID.
func (mr *MockRequestIDMiddlewareMockRecorder) InjectRequestID(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InjectRequestID", reflect.TypeOf((*MockRequestIDMiddleware)(nil).InjectRequestID), next)
}
