// Code generated by MockGen. DO NOT EDIT.
// Source: /home/kamil5b/REDIKRU/lumen-pg/internal/interfaces/middleware/validation_middleware.go

// Package mockmiddleware is a generated GoMock package.
package mockmiddleware

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockValidationMiddleware is a mock of ValidationMiddleware interface.
type MockValidationMiddleware struct {
	ctrl     *gomock.Controller
	recorder *MockValidationMiddlewareMockRecorder
}

// MockValidationMiddlewareMockRecorder is the mock recorder for MockValidationMiddleware.
type MockValidationMiddlewareMockRecorder struct {
	mock *MockValidationMiddleware
}

// NewMockValidationMiddleware creates a new mock instance.
func NewMockValidationMiddleware(ctrl *gomock.Controller) *MockValidationMiddleware {
	mock := &MockValidationMiddleware{ctrl: ctrl}
	mock.recorder = &MockValidationMiddlewareMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidationMiddleware) EXPECT() *MockValidationMiddlewareMockRecorder {
	return m.recorder
}

// ValidateQueryParams mocks base method.
func (m *MockValidationMiddleware) ValidateQueryParams(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateQueryParams", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// ValidateQueryParams indicates an expected call of ValidateQueryParams.
func (mr *MockValidationMiddlewareMockRecorder) ValidateQueryParams(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateQueryParams", reflect.TypeOf((*MockValidationMiddleware)(nil).ValidateQueryParams), next)
}

// ValidateRequestBody mocks base method.
func (m *MockValidationMiddleware) ValidateRequestBody(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateRequestBody", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// ValidateRequestBody indicates an expected call of ValidateRequestBody.
func (mr *MockValidationMiddlewareMockRecorder) ValidateRequestBody(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateRequestBody", reflect.TypeOf((*MockValidationMiddleware)(nil).ValidateRequestBody), next)
}

// ValidateSQLQuery mocks base method.
func (m *MockValidationMiddleware) ValidateSQLQuery(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSQLQuery", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// ValidateSQLQuery indicates an expected call of ValidateSQLQuery.
func (mr *MockValidationMiddlewareMockRecorder) ValidateSQLQuery(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSQLQuery", reflect.TypeOf((*MockValidationMiddleware)(nil).ValidateSQLQuery), next)
}

// ValidateWhereClause mocks base method.
func (m *MockValidationMiddleware) ValidateWhereClause(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateWhereClause", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// ValidateWhereClause indicates an expected call of ValidateWhereClause.
func (mr *MockValidationMiddlewareMockRecorder) ValidateWhereClause(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateWhereClause", reflect.TypeOf((*MockValidationMiddleware)(nil).ValidateWhereClause), next)
}
