// Code generated by MockGen. DO NOT EDIT.
// Source: /home/kamil5b/REDIKRU/lumen-pg/internal/interfaces/middleware/logging_middleware.go

// Package mockmiddleware is a generated GoMock package.
package mockmiddleware

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLoggingMiddleware is a mock of LoggingMiddleware interface.
type MockLoggingMiddleware struct {
	ctrl     *gomock.Controller
	recorder *MockLoggingMiddlewareMockRecorder
}

// MockLoggingMiddlewareMockRecorder is the mock recorder for MockLoggingMiddleware.
type MockLoggingMiddlewareMockRecorder struct {
	mock *MockLoggingMiddleware
}

// NewMockLoggingMiddleware creates a new mock instance.
func NewMockLoggingMiddleware(ctrl *gomock.Controller) *MockLoggingMiddleware {
	mock := &MockLoggingMiddleware{ctrl: ctrl}
	mock.recorder = &MockLoggingMiddlewareMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoggingMiddleware) EXPECT() *MockLoggingMiddlewareMockRecorder {
	return m.recorder
}

// LogQueryExecution mocks base method.
func (m *MockLoggingMiddleware) LogQueryExecution(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogQueryExecution", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// LogQueryExecution indicates an expected call of LogQueryExecution.
func (mr *MockLoggingMiddlewareMockRecorder) LogQueryExecution(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogQueryExecution", reflect.TypeOf((*MockLoggingMiddleware)(nil).LogQueryExecution), next)
}

// LogRequest mocks base method.
func (m *MockLoggingMiddleware) LogRequest(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogRequest", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// LogRequest indicates an expected call of LogRequest.
func (mr *MockLoggingMiddlewareMockRecorder) LogRequest(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogRequest", reflect.TypeOf((*MockLoggingMiddleware)(nil).LogRequest), next)
}

// LogSecurityEvents mocks base method.
func (m *MockLoggingMiddleware) LogSecurityEvents(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogSecurityEvents", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// LogSecurityEvents indicates an expected call of LogSecurityEvents.
func (mr *MockLoggingMiddlewareMockRecorder) LogSecurityEvents(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogSecurityEvents", reflect.TypeOf((*MockLoggingMiddleware)(nil).LogSecurityEvents), next)
}

// LogTransactionEvents mocks base method.
func (m *MockLoggingMiddleware) LogTransactionEvents(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogTransactionEvents", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// LogTransactionEvents indicates an expected call of LogTransactionEvents.
func (mr *MockLoggingMiddlewareMockRecorder) LogTransactionEvents(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogTransactionEvents", reflect.TypeOf((*MockLoggingMiddleware)(nil).LogTransactionEvents), next)
}
