// Code generated by MockGen. DO NOT EDIT.
// Source: /home/kamil5b/REDIKRU/lumen-pg/internal/interfaces/middleware/cors_middleware.go

// Package mockmiddleware is a generated GoMock package.
package mockmiddleware

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCORSMiddleware is a mock of CORSMiddleware interface.
type MockCORSMiddleware struct {
	ctrl     *gomock.Controller
	recorder *MockCORSMiddlewareMockRecorder
}

// MockCORSMiddlewareMockRecorder is the mock recorder for MockCORSMiddleware.
type MockCORSMiddlewareMockRecorder struct {
	mock *MockCORSMiddleware
}

// NewMockCORSMiddleware creates a new mock instance.
func NewMockCORSMiddleware(ctrl *gomock.Controller) *MockCORSMiddleware {
	mock := &MockCORSMiddleware{ctrl: ctrl}
	mock.recorder = &MockCORSMiddlewareMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCORSMiddleware) EXPECT() *MockCORSMiddlewareMockRecorder {
	return m.recorder
}

// HandleCORS mocks base method.
func (m *MockCORSMiddleware) HandleCORS(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleCORS", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// HandleCORS indicates an expected call of HandleCORS.
func (mr *MockCORSMiddlewareMockRecorder) HandleCORS(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleCORS", reflect.TypeOf((*MockCORSMiddleware)(nil).HandleCORS), next)
}
