// Code generated by MockGen. DO NOT EDIT.
// Source: /home/kamil5b/REDIKRU/lumen-pg/internal/interfaces/middleware/authentication_middleware.go

// Package mockmiddleware is a generated GoMock package.
package mockmiddleware

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAuthenticationMiddleware is a mock of AuthenticationMiddleware interface.
type MockAuthenticationMiddleware struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticationMiddlewareMockRecorder
}

// MockAuthenticationMiddlewareMockRecorder is the mock recorder for MockAuthenticationMiddleware.
type MockAuthenticationMiddlewareMockRecorder struct {
	mock *MockAuthenticationMiddleware
}

// NewMockAuthenticationMiddleware creates a new mock instance.
func NewMockAuthenticationMiddleware(ctrl *gomock.Controller) *MockAuthenticationMiddleware {
	mock := &MockAuthenticationMiddleware{ctrl: ctrl}
	mock.recorder = &MockAuthenticationMiddlewareMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthenticationMiddleware) EXPECT() *MockAuthenticationMiddlewareMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockAuthenticationMiddleware) Authenticate(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockAuthenticationMiddlewareMockRecorder) Authenticate(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockAuthenticationMiddleware)(nil).Authenticate), next)
}

// OptionalAuth mocks base method.
func (m *MockAuthenticationMiddleware) OptionalAuth(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OptionalAuth", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// OptionalAuth indicates an expected call of OptionalAuth.
func (mr *MockAuthenticationMiddlewareMockRecorder) OptionalAuth(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OptionalAuth", reflect.TypeOf((*MockAuthenticationMiddleware)(nil).OptionalAuth), next)
}

// RequireAuth mocks base method.
func (m *MockAuthenticationMiddleware) RequireAuth(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequireAuth", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// RequireAuth indicates an expected call of RequireAuth.
func (mr *MockAuthenticationMiddlewareMockRecorder) RequireAuth(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequireAuth", reflect.TypeOf((*MockAuthenticationMiddleware)(nil).RequireAuth), next)
}
