// Code generated by MockGen. DO NOT EDIT.
// Source: /home/kamil5b/REDIKRU/lumen-pg/internal/interfaces/middleware/middleware_type.go

// Package mockmiddleware is a generated GoMock package.
package mockmiddleware
