// Code generated by MockGen. DO NOT EDIT.
// Source: /home/kamil5b/REDIKRU/lumen-pg/internal/interfaces/middleware/context_middleware.go

// Package mockmiddleware is a generated GoMock package.
package mockmiddleware

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockContextMiddleware is a mock of ContextMiddleware interface.
type MockContextMiddleware struct {
	ctrl     *gomock.Controller
	recorder *MockContextMiddlewareMockRecorder
}

// MockContextMiddlewareMockRecorder is the mock recorder for MockContextMiddleware.
type MockContextMiddlewareMockRecorder struct {
	mock *MockContextMiddleware
}

// NewMockContextMiddleware creates a new mock instance.
func NewMockContextMiddleware(ctrl *gomock.Controller) *MockContextMiddleware {
	mock := &MockContextMiddleware{ctrl: ctrl}
	mock.recorder = &MockContextMiddlewareMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContextMiddleware) EXPECT() *MockContextMiddlewareMockRecorder {
	return m.recorder
}

// InjectMetadata mocks base method.
func (m *MockContextMiddleware) InjectMetadata(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InjectMetadata", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// InjectMetadata indicates an expected call of InjectMetadata.
func (mr *MockContextMiddlewareMockRecorder) InjectMetadata(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InjectMetadata", reflect.TypeOf((*MockContextMiddleware)(nil).InjectMetadata), next)
}

// InjectSession mocks base method.
func (m *MockContextMiddleware) InjectSession(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InjectSession", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// InjectSession indicates an expected call of InjectSession.
func (mr *MockContextMiddlewareMockRecorder) InjectSession(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InjectSession", reflect.TypeOf((*MockContextMiddleware)(nil).InjectSession), next)
}

// InjectTransaction mocks base method.
func (m *MockContextMiddleware) InjectTransaction(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InjectTransaction", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// InjectTransaction indicates an expected call of InjectTransaction.
func (mr *MockContextMiddlewareMockRecorder) InjectTransaction(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InjectTransaction", reflect.TypeOf((*MockContextMiddleware)(nil).InjectTransaction), next)
}

// InjectUser mocks base method.
func (m *MockContextMiddleware) InjectUser(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InjectUser", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// InjectUser indicates an expected call of InjectUser.
func (mr *MockContextMiddlewareMockRecorder) InjectUser(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InjectUser", reflect.TypeOf((*MockContextMiddleware)(nil).InjectUser), next)
}

// InjectUserPermissions mocks base method.
func (m *MockContextMiddleware) InjectUserPermissions(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InjectUserPermissions", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// InjectUserPermissions indicates an expected call of InjectUserPermissions.
func (mr *MockContextMiddlewareMockRecorder) InjectUserPermissions(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InjectUserPermissions", reflect.TypeOf((*MockContextMiddleware)(nil).InjectUserPermissions), next)
}
