// Code generated by MockGen. DO NOT EDIT.
// Source: internal/interfaces/repository/connection.go
//
// Generated by this command:
//
//	mockgen -source=internal/interfaces/repository/connection.go -destination=internal/implementations/mocks/connection_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/kamil5b/lumen-pg/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockConnectionRepository is a mock of ConnectionRepository interface.
type MockConnectionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockConnectionRepositoryMockRecorder
	isgomock struct{}
}

// MockConnectionRepositoryMockRecorder is the mock recorder for MockConnectionRepository.
type MockConnectionRepositoryMockRecorder struct {
	mock *MockConnectionRepository
}

// NewMockConnectionRepository creates a new mock instance.
func NewMockConnectionRepository(ctrl *gomock.Controller) *MockConnectionRepository {
	mock := &MockConnectionRepository{ctrl: ctrl}
	mock.recorder = &MockConnectionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectionRepository) EXPECT() *MockConnectionRepositoryMockRecorder {
	return m.recorder
}

// Connect mocks base method.
func (m *MockConnectionRepository) Connect(ctx context.Context, conn *domain.Connection) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", ctx, conn)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Connect indicates an expected call of Connect.
func (mr *MockConnectionRepositoryMockRecorder) Connect(ctx, conn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockConnectionRepository)(nil).Connect), ctx, conn)
}

// ParseConnectionString mocks base method.
func (m *MockConnectionRepository) ParseConnectionString(connStr string) (*domain.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseConnectionString", connStr)
	ret0, _ := ret[0].(*domain.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseConnectionString indicates an expected call of ParseConnectionString.
func (mr *MockConnectionRepositoryMockRecorder) ParseConnectionString(connStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseConnectionString", reflect.TypeOf((*MockConnectionRepository)(nil).ParseConnectionString), connStr)
}

// ValidateConnection mocks base method.
func (m *MockConnectionRepository) ValidateConnection(ctx context.Context, conn *domain.Connection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateConnection", ctx, conn)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateConnection indicates an expected call of ValidateConnection.
func (mr *MockConnectionRepositoryMockRecorder) ValidateConnection(ctx, conn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateConnection", reflect.TypeOf((*MockConnectionRepository)(nil).ValidateConnection), ctx, conn)
}
