// Code generated by MockGen. DO NOT EDIT.
// Source: internal/interfaces/usecase/connection.go
//
// Generated by this command:
//
//	mockgen -source=internal/interfaces/usecase/connection.go -destination=internal/implementations/mocks/connection_usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockConnectionUseCase is a mock of ConnectionUseCase interface.
type MockConnectionUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockConnectionUseCaseMockRecorder
	isgomock struct{}
}

// MockConnectionUseCaseMockRecorder is the mock recorder for MockConnectionUseCase.
type MockConnectionUseCaseMockRecorder struct {
	mock *MockConnectionUseCase
}

// NewMockConnectionUseCase creates a new mock instance.
func NewMockConnectionUseCase(ctrl *gomock.Controller) *MockConnectionUseCase {
	mock := &MockConnectionUseCase{ctrl: ctrl}
	mock.recorder = &MockConnectionUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectionUseCase) EXPECT() *MockConnectionUseCaseMockRecorder {
	return m.recorder
}

// TestConnection mocks base method.
func (m *MockConnectionUseCase) TestConnection(ctx context.Context, connStr string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TestConnection", ctx, connStr)
	ret0, _ := ret[0].(error)
	return ret0
}

// TestConnection indicates an expected call of TestConnection.
func (mr *MockConnectionUseCaseMockRecorder) TestConnection(ctx, connStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestConnection", reflect.TypeOf((*MockConnectionUseCase)(nil).TestConnection), ctx, connStr)
}

// ValidateConnectionString mocks base method.
func (m *MockConnectionUseCase) ValidateConnectionString(connStr string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateConnectionString", connStr)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateConnectionString indicates an expected call of ValidateConnectionString.
func (mr *MockConnectionUseCaseMockRecorder) ValidateConnectionString(connStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateConnectionString", reflect.TypeOf((*MockConnectionUseCase)(nil).ValidateConnectionString), connStr)
}
