// Code generated by MockGen. DO NOT EDIT.
// Source: internal/interfaces/usecase/handler.go
//
// Generated by this command:
//
//	mockgen -source=internal/interfaces/usecase/handler.go -destination=internal/implementations/mocks/handler_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	chi "github.com/go-chi/chi/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthHandler is a mock of AuthHandler interface.
type MockAuthHandler struct {
	ctrl     *gomock.Controller
	recorder *MockAuthHandlerMockRecorder
	isgomock struct{}
}

// MockAuthHandlerMockRecorder is the mock recorder for MockAuthHandler.
type MockAuthHandlerMockRecorder struct {
	mock *MockAuthHandler
}

// NewMockAuthHandler creates a new mock instance.
func NewMockAuthHandler(ctrl *gomock.Controller) *MockAuthHandler {
	mock := &MockAuthHandler{ctrl: ctrl}
	mock.recorder = &MockAuthHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthHandler) EXPECT() *MockAuthHandlerMockRecorder {
	return m.recorder
}

// RegisterRoutes mocks base method.
func (m *MockAuthHandler) RegisterRoutes(r chi.Router) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterRoutes", r)
}

// RegisterRoutes indicates an expected call of RegisterRoutes.
func (mr *MockAuthHandlerMockRecorder) RegisterRoutes(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterRoutes", reflect.TypeOf((*MockAuthHandler)(nil).RegisterRoutes), r)
}

// MockDataExplorerHandler is a mock of DataExplorerHandler interface.
type MockDataExplorerHandler struct {
	ctrl     *gomock.Controller
	recorder *MockDataExplorerHandlerMockRecorder
	isgomock struct{}
}

// MockDataExplorerHandlerMockRecorder is the mock recorder for MockDataExplorerHandler.
type MockDataExplorerHandlerMockRecorder struct {
	mock *MockDataExplorerHandler
}

// NewMockDataExplorerHandler creates a new mock instance.
func NewMockDataExplorerHandler(ctrl *gomock.Controller) *MockDataExplorerHandler {
	mock := &MockDataExplorerHandler{ctrl: ctrl}
	mock.recorder = &MockDataExplorerHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataExplorerHandler) EXPECT() *MockDataExplorerHandlerMockRecorder {
	return m.recorder
}

// RegisterRoutes mocks base method.
func (m *MockDataExplorerHandler) RegisterRoutes(r chi.Router) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterRoutes", r)
}

// RegisterRoutes indicates an expected call of RegisterRoutes.
func (mr *MockDataExplorerHandlerMockRecorder) RegisterRoutes(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterRoutes", reflect.TypeOf((*MockDataExplorerHandler)(nil).RegisterRoutes), r)
}

// MockQueryEditorHandler is a mock of QueryEditorHandler interface.
type MockQueryEditorHandler struct {
	ctrl     *gomock.Controller
	recorder *MockQueryEditorHandlerMockRecorder
	isgomock struct{}
}

// MockQueryEditorHandlerMockRecorder is the mock recorder for MockQueryEditorHandler.
type MockQueryEditorHandlerMockRecorder struct {
	mock *MockQueryEditorHandler
}

// NewMockQueryEditorHandler creates a new mock instance.
func NewMockQueryEditorHandler(ctrl *gomock.Controller) *MockQueryEditorHandler {
	mock := &MockQueryEditorHandler{ctrl: ctrl}
	mock.recorder = &MockQueryEditorHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryEditorHandler) EXPECT() *MockQueryEditorHandlerMockRecorder {
	return m.recorder
}

// RegisterRoutes mocks base method.
func (m *MockQueryEditorHandler) RegisterRoutes(r chi.Router) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterRoutes", r)
}

// RegisterRoutes indicates an expected call of RegisterRoutes.
func (mr *MockQueryEditorHandlerMockRecorder) RegisterRoutes(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterRoutes", reflect.TypeOf((*MockQueryEditorHandler)(nil).RegisterRoutes), r)
}

// MockERDHandler is a mock of ERDHandler interface.
type MockERDHandler struct {
	ctrl     *gomock.Controller
	recorder *MockERDHandlerMockRecorder
	isgomock struct{}
}

// MockERDHandlerMockRecorder is the mock recorder for MockERDHandler.
type MockERDHandlerMockRecorder struct {
	mock *MockERDHandler
}

// NewMockERDHandler creates a new mock instance.
func NewMockERDHandler(ctrl *gomock.Controller) *MockERDHandler {
	mock := &MockERDHandler{ctrl: ctrl}
	mock.recorder = &MockERDHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockERDHandler) EXPECT() *MockERDHandlerMockRecorder {
	return m.recorder
}

// RegisterRoutes mocks base method.
func (m *MockERDHandler) RegisterRoutes(r chi.Router) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterRoutes", r)
}

// RegisterRoutes indicates an expected call of RegisterRoutes.
func (mr *MockERDHandlerMockRecorder) RegisterRoutes(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterRoutes", reflect.TypeOf((*MockERDHandler)(nil).RegisterRoutes), r)
}
