// Code generated by MockGen. DO NOT EDIT.
// Source: internal/interfaces/repository/metadata.go
//
// Generated by this command:
//
//	mockgen -source=internal/interfaces/repository/metadata.go -destination=internal/implementations/mocks/metadata_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/kamil5b/lumen-pg/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockMetadataRepository is a mock of MetadataRepository interface.
type MockMetadataRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMetadataRepositoryMockRecorder
	isgomock struct{}
}

// MockMetadataRepositoryMockRecorder is the mock recorder for MockMetadataRepository.
type MockMetadataRepositoryMockRecorder struct {
	mock *MockMetadataRepository
}

// NewMockMetadataRepository creates a new mock instance.
func NewMockMetadataRepository(ctrl *gomock.Controller) *MockMetadataRepository {
	mock := &MockMetadataRepository{ctrl: ctrl}
	mock.recorder = &MockMetadataRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetadataRepository) EXPECT() *MockMetadataRepositoryMockRecorder {
	return m.recorder
}

// LoadDatabaseMetadata mocks base method.
func (m *MockMetadataRepository) LoadDatabaseMetadata(ctx context.Context, dbName string) (*domain.DatabaseMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadDatabaseMetadata", ctx, dbName)
	ret0, _ := ret[0].(*domain.DatabaseMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadDatabaseMetadata indicates an expected call of LoadDatabaseMetadata.
func (mr *MockMetadataRepositoryMockRecorder) LoadDatabaseMetadata(ctx, dbName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadDatabaseMetadata", reflect.TypeOf((*MockMetadataRepository)(nil).LoadDatabaseMetadata), ctx, dbName)
}

// LoadGlobalMetadata mocks base method.
func (m *MockMetadataRepository) LoadGlobalMetadata(ctx context.Context) (*domain.GlobalMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadGlobalMetadata", ctx)
	ret0, _ := ret[0].(*domain.GlobalMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadGlobalMetadata indicates an expected call of LoadGlobalMetadata.
func (mr *MockMetadataRepositoryMockRecorder) LoadGlobalMetadata(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadGlobalMetadata", reflect.TypeOf((*MockMetadataRepository)(nil).LoadGlobalMetadata), ctx)
}

// LoadRolePermissions mocks base method.
func (m *MockMetadataRepository) LoadRolePermissions(ctx context.Context, roleName string) (*domain.RoleMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadRolePermissions", ctx, roleName)
	ret0, _ := ret[0].(*domain.RoleMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadRolePermissions indicates an expected call of LoadRolePermissions.
func (mr *MockMetadataRepositoryMockRecorder) LoadRolePermissions(ctx, roleName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadRolePermissions", reflect.TypeOf((*MockMetadataRepository)(nil).LoadRolePermissions), ctx, roleName)
}

// LoadRoles mocks base method.
func (m *MockMetadataRepository) LoadRoles(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadRoles", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadRoles indicates an expected call of LoadRoles.
func (mr *MockMetadataRepositoryMockRecorder) LoadRoles(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadRoles", reflect.TypeOf((*MockMetadataRepository)(nil).LoadRoles), ctx)
}

// LoadTableMetadata mocks base method.
func (m *MockMetadataRepository) LoadTableMetadata(ctx context.Context, schemaName, tableName string) (*domain.TableMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadTableMetadata", ctx, schemaName, tableName)
	ret0, _ := ret[0].(*domain.TableMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadTableMetadata indicates an expected call of LoadTableMetadata.
func (mr *MockMetadataRepositoryMockRecorder) LoadTableMetadata(ctx, schemaName, tableName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadTableMetadata", reflect.TypeOf((*MockMetadataRepository)(nil).LoadTableMetadata), ctx, schemaName, tableName)
}
