// Code generated by MockGen. DO NOT EDIT.
// Source: internal/interfaces/usecase/metadata.go
//
// Generated by this command:
//
//	mockgen -source=internal/interfaces/usecase/metadata.go -destination=internal/implementations/mocks/metadata_usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/kamil5b/lumen-pg/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockMetadataUseCase is a mock of MetadataUseCase interface.
type MockMetadataUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockMetadataUseCaseMockRecorder
	isgomock struct{}
}

// MockMetadataUseCaseMockRecorder is the mock recorder for MockMetadataUseCase.
type MockMetadataUseCaseMockRecorder struct {
	mock *MockMetadataUseCase
}

// NewMockMetadataUseCase creates a new mock instance.
func NewMockMetadataUseCase(ctrl *gomock.Controller) *MockMetadataUseCase {
	mock := &MockMetadataUseCase{ctrl: ctrl}
	mock.recorder = &MockMetadataUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetadataUseCase) EXPECT() *MockMetadataUseCaseMockRecorder {
	return m.recorder
}

// LoadGlobalMetadata mocks base method.
func (m *MockMetadataUseCase) LoadGlobalMetadata(ctx context.Context) (*domain.GlobalMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadGlobalMetadata", ctx)
	ret0, _ := ret[0].(*domain.GlobalMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadGlobalMetadata indicates an expected call of LoadGlobalMetadata.
func (mr *MockMetadataUseCaseMockRecorder) LoadGlobalMetadata(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadGlobalMetadata", reflect.TypeOf((*MockMetadataUseCase)(nil).LoadGlobalMetadata), ctx)
}

// LoadRoleAccessibleResources mocks base method.
func (m *MockMetadataUseCase) LoadRoleAccessibleResources(ctx context.Context, roleName string) (*domain.RoleMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadRoleAccessibleResources", ctx, roleName)
	ret0, _ := ret[0].(*domain.RoleMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadRoleAccessibleResources indicates an expected call of LoadRoleAccessibleResources.
func (mr *MockMetadataUseCaseMockRecorder) LoadRoleAccessibleResources(ctx, roleName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadRoleAccessibleResources", reflect.TypeOf((*MockMetadataUseCase)(nil).LoadRoleAccessibleResources), ctx, roleName)
}
