// Code generated by MockGen. DO NOT EDIT.
// Source: internal/interfaces/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/interfaces/repository.go -destination=internal/implementations/mocks/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	domain "github.com/kamil5b/lumen-pg/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockConnectionRepository is a mock of ConnectionRepository interface.
type MockConnectionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockConnectionRepositoryMockRecorder
	isgomock struct{}
}

// MockConnectionRepositoryMockRecorder is the mock recorder for MockConnectionRepository.
type MockConnectionRepositoryMockRecorder struct {
	mock *MockConnectionRepository
}

// NewMockConnectionRepository creates a new mock instance.
func NewMockConnectionRepository(ctrl *gomock.Controller) *MockConnectionRepository {
	mock := &MockConnectionRepository{ctrl: ctrl}
	mock.recorder = &MockConnectionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectionRepository) EXPECT() *MockConnectionRepositoryMockRecorder {
	return m.recorder
}

// GetConnection mocks base method.
func (m *MockConnectionRepository) GetConnection(ctx context.Context, username, password, database string) (*sql.DB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnection", ctx, username, password, database)
	ret0, _ := ret[0].(*sql.DB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConnection indicates an expected call of GetConnection.
func (mr *MockConnectionRepositoryMockRecorder) GetConnection(ctx, username, password, database any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnection", reflect.TypeOf((*MockConnectionRepository)(nil).GetConnection), ctx, username, password, database)
}

// ProbeFirstAccessible mocks base method.
func (m *MockConnectionRepository) ProbeFirstAccessible(ctx context.Context, username, password string, metadata *domain.GlobalMetadata) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProbeFirstAccessible", ctx, username, password, metadata)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProbeFirstAccessible indicates an expected call of ProbeFirstAccessible.
func (mr *MockConnectionRepositoryMockRecorder) ProbeFirstAccessible(ctx, username, password, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProbeFirstAccessible", reflect.TypeOf((*MockConnectionRepository)(nil).ProbeFirstAccessible), ctx, username, password, metadata)
}

// TestConnection mocks base method.
func (m *MockConnectionRepository) TestConnection(ctx context.Context, connStr string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TestConnection", ctx, connStr)
	ret0, _ := ret[0].(error)
	return ret0
}

// TestConnection indicates an expected call of TestConnection.
func (mr *MockConnectionRepositoryMockRecorder) TestConnection(ctx, connStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestConnection", reflect.TypeOf((*MockConnectionRepository)(nil).TestConnection), ctx, connStr)
}

// ValidateConnectionString mocks base method.
func (m *MockConnectionRepository) ValidateConnectionString(connStr string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateConnectionString", connStr)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateConnectionString indicates an expected call of ValidateConnectionString.
func (mr *MockConnectionRepositoryMockRecorder) ValidateConnectionString(connStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateConnectionString", reflect.TypeOf((*MockConnectionRepository)(nil).ValidateConnectionString), connStr)
}

// MockMetadataRepository is a mock of MetadataRepository interface.
type MockMetadataRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMetadataRepositoryMockRecorder
	isgomock struct{}
}

// MockMetadataRepositoryMockRecorder is the mock recorder for MockMetadataRepository.
type MockMetadataRepositoryMockRecorder struct {
	mock *MockMetadataRepository
}

// NewMockMetadataRepository creates a new mock instance.
func NewMockMetadataRepository(ctrl *gomock.Controller) *MockMetadataRepository {
	mock := &MockMetadataRepository{ctrl: ctrl}
	mock.recorder = &MockMetadataRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetadataRepository) EXPECT() *MockMetadataRepositoryMockRecorder {
	return m.recorder
}

// GetERDData mocks base method.
func (m *MockMetadataRepository) GetERDData(ctx context.Context, db *sql.DB, database, schema string) (*domain.ERDData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetERDData", ctx, db, database, schema)
	ret0, _ := ret[0].(*domain.ERDData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetERDData indicates an expected call of GetERDData.
func (mr *MockMetadataRepositoryMockRecorder) GetERDData(ctx, db, database, schema any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetERDData", reflect.TypeOf((*MockMetadataRepository)(nil).GetERDData), ctx, db, database, schema)
}

// GetTableMetadata mocks base method.
func (m *MockMetadataRepository) GetTableMetadata(ctx context.Context, db *sql.DB, schema, table string) (*domain.TableMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTableMetadata", ctx, db, schema, table)
	ret0, _ := ret[0].(*domain.TableMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTableMetadata indicates an expected call of GetTableMetadata.
func (mr *MockMetadataRepositoryMockRecorder) GetTableMetadata(ctx, db, schema, table any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTableMetadata", reflect.TypeOf((*MockMetadataRepository)(nil).GetTableMetadata), ctx, db, schema, table)
}

// LoadDatabaseMetadata mocks base method.
func (m *MockMetadataRepository) LoadDatabaseMetadata(ctx context.Context, db *sql.DB, database string) (*domain.DatabaseMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadDatabaseMetadata", ctx, db, database)
	ret0, _ := ret[0].(*domain.DatabaseMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadDatabaseMetadata indicates an expected call of LoadDatabaseMetadata.
func (mr *MockMetadataRepositoryMockRecorder) LoadDatabaseMetadata(ctx, db, database any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadDatabaseMetadata", reflect.TypeOf((*MockMetadataRepository)(nil).LoadDatabaseMetadata), ctx, db, database)
}

// LoadGlobalMetadata mocks base method.
func (m *MockMetadataRepository) LoadGlobalMetadata(ctx context.Context, db *sql.DB) (*domain.GlobalMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadGlobalMetadata", ctx, db)
	ret0, _ := ret[0].(*domain.GlobalMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadGlobalMetadata indicates an expected call of LoadGlobalMetadata.
func (mr *MockMetadataRepositoryMockRecorder) LoadGlobalMetadata(ctx, db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadGlobalMetadata", reflect.TypeOf((*MockMetadataRepository)(nil).LoadGlobalMetadata), ctx, db)
}

// LoadRolePermissions mocks base method.
func (m *MockMetadataRepository) LoadRolePermissions(ctx context.Context, db *sql.DB) (map[string]*domain.RolePermissions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadRolePermissions", ctx, db)
	ret0, _ := ret[0].(map[string]*domain.RolePermissions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadRolePermissions indicates an expected call of LoadRolePermissions.
func (mr *MockMetadataRepositoryMockRecorder) LoadRolePermissions(ctx, db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadRolePermissions", reflect.TypeOf((*MockMetadataRepository)(nil).LoadRolePermissions), ctx, db)
}

// MockQueryRepository is a mock of QueryRepository interface.
type MockQueryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockQueryRepositoryMockRecorder
	isgomock struct{}
}

// MockQueryRepositoryMockRecorder is the mock recorder for MockQueryRepository.
type MockQueryRepositoryMockRecorder struct {
	mock *MockQueryRepository
}

// NewMockQueryRepository creates a new mock instance.
func NewMockQueryRepository(ctrl *gomock.Controller) *MockQueryRepository {
	mock := &MockQueryRepository{ctrl: ctrl}
	mock.recorder = &MockQueryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryRepository) EXPECT() *MockQueryRepositoryMockRecorder {
	return m.recorder
}

// ExecuteMultipleQueries mocks base method.
func (m *MockQueryRepository) ExecuteMultipleQueries(ctx context.Context, db *sql.DB, arg2 string) ([]*domain.QueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteMultipleQueries", ctx, db, arg2)
	ret0, _ := ret[0].([]*domain.QueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteMultipleQueries indicates an expected call of ExecuteMultipleQueries.
func (mr *MockQueryRepositoryMockRecorder) ExecuteMultipleQueries(ctx, db, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteMultipleQueries", reflect.TypeOf((*MockQueryRepository)(nil).ExecuteMultipleQueries), ctx, db, arg2)
}

// ExecuteQuery mocks base method.
func (m *MockQueryRepository) ExecuteQuery(ctx context.Context, db *sql.DB, req domain.QueryRequest) (*domain.QueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteQuery", ctx, db, req)
	ret0, _ := ret[0].(*domain.QueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteQuery indicates an expected call of ExecuteQuery.
func (mr *MockQueryRepositoryMockRecorder) ExecuteQuery(ctx, db, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteQuery", reflect.TypeOf((*MockQueryRepository)(nil).ExecuteQuery), ctx, db, req)
}

// GetReferencingTables mocks base method.
func (m *MockQueryRepository) GetReferencingTables(ctx context.Context, db *sql.DB, schema, table, pkColumn string, pkValue any) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReferencingTables", ctx, db, schema, table, pkColumn, pkValue)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReferencingTables indicates an expected call of GetReferencingTables.
func (mr *MockQueryRepositoryMockRecorder) GetReferencingTables(ctx, db, schema, table, pkColumn, pkValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReferencingTables", reflect.TypeOf((*MockQueryRepository)(nil).GetReferencingTables), ctx, db, schema, table, pkColumn, pkValue)
}

// GetTableData mocks base method.
func (m *MockQueryRepository) GetTableData(ctx context.Context, db *sql.DB, req domain.TableDataRequest) (*domain.TableDataResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTableData", ctx, db, req)
	ret0, _ := ret[0].(*domain.TableDataResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTableData indicates an expected call of GetTableData.
func (mr *MockQueryRepositoryMockRecorder) GetTableData(ctx, db, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTableData", reflect.TypeOf((*MockQueryRepository)(nil).GetTableData), ctx, db, req)
}

// MockTransactionRepository is a mock of TransactionRepository interface.
type MockTransactionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionRepositoryMockRecorder
	isgomock struct{}
}

// MockTransactionRepositoryMockRecorder is the mock recorder for MockTransactionRepository.
type MockTransactionRepositoryMockRecorder struct {
	mock *MockTransactionRepository
}

// NewMockTransactionRepository creates a new mock instance.
func NewMockTransactionRepository(ctrl *gomock.Controller) *MockTransactionRepository {
	mock := &MockTransactionRepository{ctrl: ctrl}
	mock.recorder = &MockTransactionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionRepository) EXPECT() *MockTransactionRepositoryMockRecorder {
	return m.recorder
}

// BeginTransaction mocks base method.
func (m *MockTransactionRepository) BeginTransaction(ctx context.Context, db *sql.DB) (*sql.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTransaction", ctx, db)
	ret0, _ := ret[0].(*sql.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTransaction indicates an expected call of BeginTransaction.
func (mr *MockTransactionRepositoryMockRecorder) BeginTransaction(ctx, db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTransaction", reflect.TypeOf((*MockTransactionRepository)(nil).BeginTransaction), ctx, db)
}

// CommitTransaction mocks base method.
func (m *MockTransactionRepository) CommitTransaction(ctx context.Context, tx *sql.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitTransaction", ctx, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitTransaction indicates an expected call of CommitTransaction.
func (mr *MockTransactionRepositoryMockRecorder) CommitTransaction(ctx, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitTransaction", reflect.TypeOf((*MockTransactionRepository)(nil).CommitTransaction), ctx, tx)
}

// ExecuteOperations mocks base method.
func (m *MockTransactionRepository) ExecuteOperations(ctx context.Context, tx *sql.Tx, operations []domain.Operation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteOperations", ctx, tx, operations)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteOperations indicates an expected call of ExecuteOperations.
func (mr *MockTransactionRepositoryMockRecorder) ExecuteOperations(ctx, tx, operations any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteOperations", reflect.TypeOf((*MockTransactionRepository)(nil).ExecuteOperations), ctx, tx, operations)
}

// RollbackTransaction mocks base method.
func (m *MockTransactionRepository) RollbackTransaction(ctx context.Context, tx *sql.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackTransaction", ctx, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RollbackTransaction indicates an expected call of RollbackTransaction.
func (mr *MockTransactionRepositoryMockRecorder) RollbackTransaction(ctx, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackTransaction", reflect.TypeOf((*MockTransactionRepository)(nil).RollbackTransaction), ctx, tx)
}
