// Code generated by MockGen. DO NOT EDIT.
// Source: internal/interfaces/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/interfaces/service.go -destination=internal/implementations/mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/kamil5b/lumen-pg/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
	isgomock struct{}
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// DecryptPassword mocks base method.
func (m *MockAuthService) DecryptPassword(encrypted string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptPassword", encrypted)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecryptPassword indicates an expected call of DecryptPassword.
func (mr *MockAuthServiceMockRecorder) DecryptPassword(encrypted any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptPassword", reflect.TypeOf((*MockAuthService)(nil).DecryptPassword), encrypted)
}

// EncryptPassword mocks base method.
func (m *MockAuthService) EncryptPassword(password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptPassword", password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncryptPassword indicates an expected call of EncryptPassword.
func (mr *MockAuthServiceMockRecorder) EncryptPassword(password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptPassword", reflect.TypeOf((*MockAuthService)(nil).EncryptPassword), password)
}

// Login mocks base method.
func (m *MockAuthService) Login(ctx context.Context, input domain.LoginInput) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, input)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthServiceMockRecorder) Login(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthService)(nil).Login), ctx, input)
}

// Logout mocks base method.
func (m *MockAuthService) Logout(ctx context.Context, sessionToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, sessionToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthServiceMockRecorder) Logout(ctx, sessionToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthService)(nil).Logout), ctx, sessionToken)
}

// ValidateSession mocks base method.
func (m *MockAuthService) ValidateSession(ctx context.Context, sessionToken string) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSession", ctx, sessionToken)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateSession indicates an expected call of ValidateSession.
func (mr *MockAuthServiceMockRecorder) ValidateSession(ctx, sessionToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSession", reflect.TypeOf((*MockAuthService)(nil).ValidateSession), ctx, sessionToken)
}

// MockMetadataService is a mock of MetadataService interface.
type MockMetadataService struct {
	ctrl     *gomock.Controller
	recorder *MockMetadataServiceMockRecorder
	isgomock struct{}
}

// MockMetadataServiceMockRecorder is the mock recorder for MockMetadataService.
type MockMetadataServiceMockRecorder struct {
	mock *MockMetadataService
}

// NewMockMetadataService creates a new mock instance.
func NewMockMetadataService(ctrl *gomock.Controller) *MockMetadataService {
	mock := &MockMetadataService{ctrl: ctrl}
	mock.recorder = &MockMetadataServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetadataService) EXPECT() *MockMetadataServiceMockRecorder {
	return m.recorder
}

// GetAccessibleResources mocks base method.
func (m *MockMetadataService) GetAccessibleResources(ctx context.Context, roleName string) (*domain.RolePermissions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessibleResources", ctx, roleName)
	ret0, _ := ret[0].(*domain.RolePermissions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessibleResources indicates an expected call of GetAccessibleResources.
func (mr *MockMetadataServiceMockRecorder) GetAccessibleResources(ctx, roleName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessibleResources", reflect.TypeOf((*MockMetadataService)(nil).GetAccessibleResources), ctx, roleName)
}

// GetERDData mocks base method.
func (m *MockMetadataService) GetERDData(ctx context.Context, username, database, schema string) (*domain.ERDData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetERDData", ctx, username, database, schema)
	ret0, _ := ret[0].(*domain.ERDData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetERDData indicates an expected call of GetERDData.
func (mr *MockMetadataServiceMockRecorder) GetERDData(ctx, username, database, schema any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetERDData", reflect.TypeOf((*MockMetadataService)(nil).GetERDData), ctx, username, database, schema)
}

// InitializeMetadata mocks base method.
func (m *MockMetadataService) InitializeMetadata(ctx context.Context, superAdminConnStr string) (*domain.GlobalMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitializeMetadata", ctx, superAdminConnStr)
	ret0, _ := ret[0].(*domain.GlobalMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitializeMetadata indicates an expected call of InitializeMetadata.
func (mr *MockMetadataServiceMockRecorder) InitializeMetadata(ctx, superAdminConnStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitializeMetadata", reflect.TypeOf((*MockMetadataService)(nil).InitializeMetadata), ctx, superAdminConnStr)
}

// RefreshMetadata mocks base method.
func (m *MockMetadataService) RefreshMetadata(ctx context.Context) (*domain.GlobalMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshMetadata", ctx)
	ret0, _ := ret[0].(*domain.GlobalMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshMetadata indicates an expected call of RefreshMetadata.
func (mr *MockMetadataServiceMockRecorder) RefreshMetadata(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshMetadata", reflect.TypeOf((*MockMetadataService)(nil).RefreshMetadata), ctx)
}

// MockQueryService is a mock of QueryService interface.
type MockQueryService struct {
	ctrl     *gomock.Controller
	recorder *MockQueryServiceMockRecorder
	isgomock struct{}
}

// MockQueryServiceMockRecorder is the mock recorder for MockQueryService.
type MockQueryServiceMockRecorder struct {
	mock *MockQueryService
}

// NewMockQueryService creates a new mock instance.
func NewMockQueryService(ctrl *gomock.Controller) *MockQueryService {
	mock := &MockQueryService{ctrl: ctrl}
	mock.recorder = &MockQueryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryService) EXPECT() *MockQueryServiceMockRecorder {
	return m.recorder
}

// ExecuteMultipleQueries mocks base method.
func (m *MockQueryService) ExecuteMultipleQueries(ctx context.Context, username, database, sql string) ([]*domain.QueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteMultipleQueries", ctx, username, database, sql)
	ret0, _ := ret[0].([]*domain.QueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteMultipleQueries indicates an expected call of ExecuteMultipleQueries.
func (mr *MockQueryServiceMockRecorder) ExecuteMultipleQueries(ctx, username, database, sql any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteMultipleQueries", reflect.TypeOf((*MockQueryService)(nil).ExecuteMultipleQueries), ctx, username, database, sql)
}

// ExecuteQuery mocks base method.
func (m *MockQueryService) ExecuteQuery(ctx context.Context, username, database string, req domain.QueryRequest) (*domain.QueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteQuery", ctx, username, database, req)
	ret0, _ := ret[0].(*domain.QueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteQuery indicates an expected call of ExecuteQuery.
func (mr *MockQueryServiceMockRecorder) ExecuteQuery(ctx, username, database, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteQuery", reflect.TypeOf((*MockQueryService)(nil).ExecuteQuery), ctx, username, database, req)
}

// SplitQueries mocks base method.
func (m *MockQueryService) SplitQueries(sql string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SplitQueries", sql)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SplitQueries indicates an expected call of SplitQueries.
func (mr *MockQueryServiceMockRecorder) SplitQueries(sql any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SplitQueries", reflect.TypeOf((*MockQueryService)(nil).SplitQueries), sql)
}

// ValidateWhereClause mocks base method.
func (m *MockQueryService) ValidateWhereClause(whereClause string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateWhereClause", whereClause)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateWhereClause indicates an expected call of ValidateWhereClause.
func (mr *MockQueryServiceMockRecorder) ValidateWhereClause(whereClause any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateWhereClause", reflect.TypeOf((*MockQueryService)(nil).ValidateWhereClause), whereClause)
}

// MockDataExplorerService is a mock of DataExplorerService interface.
type MockDataExplorerService struct {
	ctrl     *gomock.Controller
	recorder *MockDataExplorerServiceMockRecorder
	isgomock struct{}
}

// MockDataExplorerServiceMockRecorder is the mock recorder for MockDataExplorerService.
type MockDataExplorerServiceMockRecorder struct {
	mock *MockDataExplorerService
}

// NewMockDataExplorerService creates a new mock instance.
func NewMockDataExplorerService(ctrl *gomock.Controller) *MockDataExplorerService {
	mock := &MockDataExplorerService{ctrl: ctrl}
	mock.recorder = &MockDataExplorerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataExplorerService) EXPECT() *MockDataExplorerServiceMockRecorder {
	return m.recorder
}

// GetReferencingTables mocks base method.
func (m *MockDataExplorerService) GetReferencingTables(ctx context.Context, username, database, schema, table, pkColumn string, pkValue any) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReferencingTables", ctx, username, database, schema, table, pkColumn, pkValue)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReferencingTables indicates an expected call of GetReferencingTables.
func (mr *MockDataExplorerServiceMockRecorder) GetReferencingTables(ctx, username, database, schema, table, pkColumn, pkValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReferencingTables", reflect.TypeOf((*MockDataExplorerService)(nil).GetReferencingTables), ctx, username, database, schema, table, pkColumn, pkValue)
}

// GetTableData mocks base method.
func (m *MockDataExplorerService) GetTableData(ctx context.Context, username, database string, req domain.TableDataRequest) (*domain.TableDataResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTableData", ctx, username, database, req)
	ret0, _ := ret[0].(*domain.TableDataResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTableData indicates an expected call of GetTableData.
func (mr *MockDataExplorerServiceMockRecorder) GetTableData(ctx, username, database, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTableData", reflect.TypeOf((*MockDataExplorerService)(nil).GetTableData), ctx, username, database, req)
}

// NavigateToForeignKey mocks base method.
func (m *MockDataExplorerService) NavigateToForeignKey(ctx context.Context, username, database, schema, table, fkColumn string, fkValue any) (*domain.TableDataResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NavigateToForeignKey", ctx, username, database, schema, table, fkColumn, fkValue)
	ret0, _ := ret[0].(*domain.TableDataResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NavigateToForeignKey indicates an expected call of NavigateToForeignKey.
func (mr *MockDataExplorerServiceMockRecorder) NavigateToForeignKey(ctx, username, database, schema, table, fkColumn, fkValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NavigateToForeignKey", reflect.TypeOf((*MockDataExplorerService)(nil).NavigateToForeignKey), ctx, username, database, schema, table, fkColumn, fkValue)
}

// MockTransactionService is a mock of TransactionService interface.
type MockTransactionService struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionServiceMockRecorder
	isgomock struct{}
}

// MockTransactionServiceMockRecorder is the mock recorder for MockTransactionService.
type MockTransactionServiceMockRecorder struct {
	mock *MockTransactionService
}

// NewMockTransactionService creates a new mock instance.
func NewMockTransactionService(ctrl *gomock.Controller) *MockTransactionService {
	mock := &MockTransactionService{ctrl: ctrl}
	mock.recorder = &MockTransactionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionService) EXPECT() *MockTransactionServiceMockRecorder {
	return m.recorder
}

// BufferOperation mocks base method.
func (m *MockTransactionService) BufferOperation(ctx context.Context, username string, op domain.Operation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BufferOperation", ctx, username, op)
	ret0, _ := ret[0].(error)
	return ret0
}

// BufferOperation indicates an expected call of BufferOperation.
func (mr *MockTransactionServiceMockRecorder) BufferOperation(ctx, username, op any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BufferOperation", reflect.TypeOf((*MockTransactionService)(nil).BufferOperation), ctx, username, op)
}

// CheckTransactionTimeout mocks base method.
func (m *MockTransactionService) CheckTransactionTimeout(ctx context.Context, username string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckTransactionTimeout", ctx, username)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckTransactionTimeout indicates an expected call of CheckTransactionTimeout.
func (mr *MockTransactionServiceMockRecorder) CheckTransactionTimeout(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckTransactionTimeout", reflect.TypeOf((*MockTransactionService)(nil).CheckTransactionTimeout), ctx, username)
}

// CommitTransaction mocks base method.
func (m *MockTransactionService) CommitTransaction(ctx context.Context, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitTransaction", ctx, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitTransaction indicates an expected call of CommitTransaction.
func (mr *MockTransactionServiceMockRecorder) CommitTransaction(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitTransaction", reflect.TypeOf((*MockTransactionService)(nil).CommitTransaction), ctx, username)
}

// GetTransactionState mocks base method.
func (m *MockTransactionService) GetTransactionState(ctx context.Context, username string) (*domain.TransactionState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionState", ctx, username)
	ret0, _ := ret[0].(*domain.TransactionState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionState indicates an expected call of GetTransactionState.
func (mr *MockTransactionServiceMockRecorder) GetTransactionState(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionState", reflect.TypeOf((*MockTransactionService)(nil).GetTransactionState), ctx, username)
}

// RollbackTransaction mocks base method.
func (m *MockTransactionService) RollbackTransaction(ctx context.Context, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackTransaction", ctx, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// RollbackTransaction indicates an expected call of RollbackTransaction.
func (mr *MockTransactionServiceMockRecorder) RollbackTransaction(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackTransaction", reflect.TypeOf((*MockTransactionService)(nil).RollbackTransaction), ctx, username)
}

// StartTransaction mocks base method.
func (m *MockTransactionService) StartTransaction(ctx context.Context, username, database string) (*domain.TransactionState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartTransaction", ctx, username, database)
	ret0, _ := ret[0].(*domain.TransactionState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartTransaction indicates an expected call of StartTransaction.
func (mr *MockTransactionServiceMockRecorder) StartTransaction(ctx, username, database any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartTransaction", reflect.TypeOf((*MockTransactionService)(nil).StartTransaction), ctx, username, database)
}
