// Code generated by MockGen. DO NOT EDIT.
// Source: internal/interfaces/usecase/query.go
//
// Generated by this command:
//
//	mockgen -source=internal/interfaces/usecase/query.go -destination=internal/implementations/mocks/query_usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/kamil5b/lumen-pg/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockQueryUseCase is a mock of QueryUseCase interface.
type MockQueryUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockQueryUseCaseMockRecorder
	isgomock struct{}
}

// MockQueryUseCaseMockRecorder is the mock recorder for MockQueryUseCase.
type MockQueryUseCaseMockRecorder struct {
	mock *MockQueryUseCase
}

// NewMockQueryUseCase creates a new mock instance.
func NewMockQueryUseCase(ctrl *gomock.Controller) *MockQueryUseCase {
	mock := &MockQueryUseCase{ctrl: ctrl}
	mock.recorder = &MockQueryUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryUseCase) EXPECT() *MockQueryUseCaseMockRecorder {
	return m.recorder
}

// ExecuteMultipleQueries mocks base method.
func (m *MockQueryUseCase) ExecuteMultipleQueries(ctx context.Context, queries string) ([]*domain.QueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteMultipleQueries", ctx, queries)
	ret0, _ := ret[0].([]*domain.QueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteMultipleQueries indicates an expected call of ExecuteMultipleQueries.
func (mr *MockQueryUseCaseMockRecorder) ExecuteMultipleQueries(ctx, queries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteMultipleQueries", reflect.TypeOf((*MockQueryUseCase)(nil).ExecuteMultipleQueries), ctx, queries)
}

// ExecuteQuery mocks base method.
func (m *MockQueryUseCase) ExecuteQuery(ctx context.Context, sql string, params ...any) (*domain.QueryResult, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range params {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExecuteQuery", varargs...)
	ret0, _ := ret[0].(*domain.QueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteQuery indicates an expected call of ExecuteQuery.
func (mr *MockQueryUseCaseMockRecorder) ExecuteQuery(ctx, sql any, params ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, params...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteQuery", reflect.TypeOf((*MockQueryUseCase)(nil).ExecuteQuery), varargs...)
}
