// Code generated by MockGen. DO NOT EDIT.
// Source: internal/interfaces/repository/query.go
//
// Generated by this command:
//
//	mockgen -source=internal/interfaces/repository/query.go -destination=internal/implementations/mocks/query_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/kamil5b/lumen-pg/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockQueryRepository is a mock of QueryRepository interface.
type MockQueryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockQueryRepositoryMockRecorder
	isgomock struct{}
}

// MockQueryRepositoryMockRecorder is the mock recorder for MockQueryRepository.
type MockQueryRepositoryMockRecorder struct {
	mock *MockQueryRepository
}

// NewMockQueryRepository creates a new mock instance.
func NewMockQueryRepository(ctrl *gomock.Controller) *MockQueryRepository {
	mock := &MockQueryRepository{ctrl: ctrl}
	mock.recorder = &MockQueryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryRepository) EXPECT() *MockQueryRepositoryMockRecorder {
	return m.recorder
}

// ExecuteDDL mocks base method.
func (m *MockQueryRepository) ExecuteDDL(ctx context.Context, query string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteDDL", ctx, query)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteDDL indicates an expected call of ExecuteDDL.
func (mr *MockQueryRepositoryMockRecorder) ExecuteDDL(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteDDL", reflect.TypeOf((*MockQueryRepository)(nil).ExecuteDDL), ctx, query)
}

// ExecuteDML mocks base method.
func (m *MockQueryRepository) ExecuteDML(ctx context.Context, query string, params ...any) (*domain.QueryResult, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, query}
	for _, a := range params {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExecuteDML", varargs...)
	ret0, _ := ret[0].(*domain.QueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteDML indicates an expected call of ExecuteDML.
func (mr *MockQueryRepositoryMockRecorder) ExecuteDML(ctx, query any, params ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, query}, params...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteDML", reflect.TypeOf((*MockQueryRepository)(nil).ExecuteDML), varargs...)
}

// ExecuteMultiple mocks base method.
func (m *MockQueryRepository) ExecuteMultiple(ctx context.Context, queries string) ([]*domain.QueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteMultiple", ctx, queries)
	ret0, _ := ret[0].([]*domain.QueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteMultiple indicates an expected call of ExecuteMultiple.
func (mr *MockQueryRepositoryMockRecorder) ExecuteMultiple(ctx, queries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteMultiple", reflect.TypeOf((*MockQueryRepository)(nil).ExecuteMultiple), ctx, queries)
}

// ExecuteQuery mocks base method.
func (m *MockQueryRepository) ExecuteQuery(ctx context.Context, query string, params ...any) (*domain.QueryResult, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, query}
	for _, a := range params {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExecuteQuery", varargs...)
	ret0, _ := ret[0].(*domain.QueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteQuery indicates an expected call of ExecuteQuery.
func (mr *MockQueryRepositoryMockRecorder) ExecuteQuery(ctx, query any, params ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, query}, params...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteQuery", reflect.TypeOf((*MockQueryRepository)(nil).ExecuteQuery), varargs...)
}
