// Code generated by MockGen. DO NOT EDIT.
// Source: internal/interfaces/transaction.go
//
// Generated by this command:
//
//	mockgen -source=internal/interfaces/transaction.go -destination=internal/implementations/mocks/transaction_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/kamil5b/lumen-pg/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTransactionRepository is a mock of TransactionRepository interface.
type MockTransactionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionRepositoryMockRecorder
	isgomock struct{}
}

// MockTransactionRepositoryMockRecorder is the mock recorder for MockTransactionRepository.
type MockTransactionRepositoryMockRecorder struct {
	mock *MockTransactionRepository
}

// NewMockTransactionRepository creates a new mock instance.
func NewMockTransactionRepository(ctrl *gomock.Controller) *MockTransactionRepository {
	mock := &MockTransactionRepository{ctrl: ctrl}
	mock.recorder = &MockTransactionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionRepository) EXPECT() *MockTransactionRepositoryMockRecorder {
	return m.recorder
}

// BufferOperation mocks base method.
func (m *MockTransactionRepository) BufferOperation(ctx context.Context, txnID string, op domain.TransactionOperation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BufferOperation", ctx, txnID, op)
	ret0, _ := ret[0].(error)
	return ret0
}

// BufferOperation indicates an expected call of BufferOperation.
func (mr *MockTransactionRepositoryMockRecorder) BufferOperation(ctx, txnID, op any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BufferOperation", reflect.TypeOf((*MockTransactionRepository)(nil).BufferOperation), ctx, txnID, op)
}

// CommitTransaction mocks base method.
func (m *MockTransactionRepository) CommitTransaction(ctx context.Context, txnID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitTransaction", ctx, txnID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitTransaction indicates an expected call of CommitTransaction.
func (mr *MockTransactionRepositoryMockRecorder) CommitTransaction(ctx, txnID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitTransaction", reflect.TypeOf((*MockTransactionRepository)(nil).CommitTransaction), ctx, txnID)
}

// GetTransaction mocks base method.
func (m *MockTransactionRepository) GetTransaction(ctx context.Context, txnID string) (*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransaction", ctx, txnID)
	ret0, _ := ret[0].(*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransaction indicates an expected call of GetTransaction.
func (mr *MockTransactionRepositoryMockRecorder) GetTransaction(ctx, txnID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransaction", reflect.TypeOf((*MockTransactionRepository)(nil).GetTransaction), ctx, txnID)
}

// RollbackTransaction mocks base method.
func (m *MockTransactionRepository) RollbackTransaction(ctx context.Context, txnID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackTransaction", ctx, txnID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RollbackTransaction indicates an expected call of RollbackTransaction.
func (mr *MockTransactionRepositoryMockRecorder) RollbackTransaction(ctx, txnID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackTransaction", reflect.TypeOf((*MockTransactionRepository)(nil).RollbackTransaction), ctx, txnID)
}

// StartTransaction mocks base method.
func (m *MockTransactionRepository) StartTransaction(ctx context.Context, username, tableName string) (*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartTransaction", ctx, username, tableName)
	ret0, _ := ret[0].(*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartTransaction indicates an expected call of StartTransaction.
func (mr *MockTransactionRepositoryMockRecorder) StartTransaction(ctx, username, tableName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartTransaction", reflect.TypeOf((*MockTransactionRepository)(nil).StartTransaction), ctx, username, tableName)
}
