// Code generated by MockGen. DO NOT EDIT.
// Source: internal/interfaces/usecase/transaction.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/kamil5b/lumen-pg/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTransactionUseCase is a mock of TransactionUseCase interface.
type MockTransactionUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionUseCaseMockRecorder
}

// MockTransactionUseCaseMockRecorder is the mock recorder for MockTransactionUseCase.
type MockTransactionUseCaseMockRecorder struct {
	mock *MockTransactionUseCase
}

// NewMockTransactionUseCase creates a new mock instance.
func NewMockTransactionUseCase(ctrl *gomock.Controller) *MockTransactionUseCase {
	mock := &MockTransactionUseCase{ctrl: ctrl}
	mock.recorder = &MockTransactionUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionUseCase) EXPECT() *MockTransactionUseCaseMockRecorder {
	return m.recorder
}

// BufferEdit mocks base method.
func (m *MockTransactionUseCase) BufferEdit(ctx context.Context, txnID string, op domain.TransactionOperation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BufferEdit", ctx, txnID, op)
	ret0, _ := ret[0].(error)
	return ret0
}

// BufferEdit indicates an expected call of BufferEdit.
func (mr *MockTransactionUseCaseMockRecorder) BufferEdit(ctx, txnID, op interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BufferEdit", reflect.TypeOf((*MockTransactionUseCase)(nil).BufferEdit), ctx, txnID, op)
}

// CommitTransaction mocks base method.
func (m *MockTransactionUseCase) CommitTransaction(ctx context.Context, txnID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitTransaction", ctx, txnID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitTransaction indicates an expected call of CommitTransaction.
func (mr *MockTransactionUseCaseMockRecorder) CommitTransaction(ctx, txnID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitTransaction", reflect.TypeOf((*MockTransactionUseCase)(nil).CommitTransaction), ctx, txnID)
}

// GetTransaction mocks base method.
func (m *MockTransactionUseCase) GetTransaction(ctx context.Context, txnID string) (*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransaction", ctx, txnID)
	ret0, _ := ret[0].(*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransaction indicates an expected call of GetTransaction.
func (mr *MockTransactionUseCaseMockRecorder) GetTransaction(ctx, txnID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransaction", reflect.TypeOf((*MockTransactionUseCase)(nil).GetTransaction), ctx, txnID)
}

// RollbackTransaction mocks base method.
func (m *MockTransactionUseCase) RollbackTransaction(ctx context.Context, txnID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackTransaction", ctx, txnID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RollbackTransaction indicates an expected call of RollbackTransaction.
func (mr *MockTransactionUseCaseMockRecorder) RollbackTransaction(ctx, txnID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackTransaction", reflect.TypeOf((*MockTransactionUseCase)(nil).RollbackTransaction), ctx, txnID)
}

// StartTransaction mocks base method.
func (m *MockTransactionUseCase) StartTransaction(ctx context.Context, username, tableName string) (*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartTransaction", ctx, username, tableName)
	ret0, _ := ret[0].(*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartTransaction indicates an expected call of StartTransaction.
func (mr *MockTransactionUseCaseMockRecorder) StartTransaction(ctx, username, tableName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartTransaction", reflect.TypeOf((*MockTransactionUseCase)(nil).StartTransaction), ctx, username, tableName)
}
